### ISSUE TITLE
Single word ophans

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#100]
I thought I had read that ptxprint would avoid having single words on the last line of a paragraph (though I can't find reference to that in the issues now). Is that supposed to happen?

Here's an example of what's happening (surprisingly often).
![image](https://user-images.githubusercontent.com/30174022/83801854-6ee05e00-a66f-11ea-93c0-d4cac038eac8.png)

**Comment by markpenny** [comment]
@mhosken What are your thoughts on this one? I know that we _used to_ keep the last two words of ANY paragraph together, but that was causing other (unexpected) issues/problems. So we ended up restricting it to \q# markers only. Maybe we can think about how to be more selective in applying that "NBSP glue" - and it might even help make col-balancing easier.

**Comment by mhosken** [comment]
TeX never guarantees that it won't create a widow or orphan word. You can force it not to with a NBSP. Basically it looks at the paragraph and works out the best break. I'm not sure whether having contextual spaces messes that up at all. Given how rarely it happens in the text, probably not.

If you have TeXability then you could turn on \tracingparagraphs=1 before that paragraph and turn it off again after (due to digits not being numbers in sfm files, you'll need to create a couple of \def in your ptxprint-mods.tex to do the switching) Or trim down your sfm and have a big log file :)

**Comment by markpenny** [comment]
@mhosken  Perhaps we should have an option which says "Don't allow orphan words less than X characters to occur" - and X can be user-defined from 2 to 30 chars. Then we only apply the NBSP quite selectively to these "short" words at the end of \p \m etc. paragraphs (rather than the everywhere - as we were doing earlier).

**Comment by mhosken** [comment]
Perhaps although we have had problems with inserting NBSP where a true space was expected. Let's monitor this. Please use this big to report more any occurrences. One per NT is to be expected! Remember some paragraphs are just hard to break and TeX may need to have an orphan. Also if you ask for +1 in a .adj file then expect orphans.

**Comment by mnjames** [comment]
I just checked and found 11 occurrences in a printout of Matthew, out of a total of about 175 paragraphs. Of course changing font size and layout would affect that, but it gives you a general sense of the size of the problem.

I"m not using an .adj file.

Nastaliq words are so short it would actually be nice to have a minimum length in terms of size or a minimum number of characters, but just having the last 2 words tied by a NBSP so that there were no single word entries would be a vast improvement.

**Comment by mhosken** [comment]
I wonder if the cause of this is the narrow space in Awami (1/6 em vs say 0.3em for Charis). Not only does that tighten the text, but it also limits the amount of stretch and shrink that can be applied which reduces the flexibility in line breaking. One thing you could try is to turn on Spacing stretch in the Advanced tab and set a max of say 250%. Feel free to fiddle with the numbers to get something that looks nice.

**Comment by mhosken** [comment]
In 0.8.2 we have added a "Bad Breaking Space", subverting U+2000 EN QUAD for this purpose. So now if you say "Prevent Orphan Words" ptxprint will insert Bad Breaking Spaces before the last word in a paragraph (most of the time) which should mean that TeX will generally not break, but might break if it's otherwise going to be pretty ugly.

**Comment by mnjames** [comment]
The "Prevent Orphan Words" change doesn't appear to make much difference--I now count 9 cases of single word orphans in Matthew. However the suggestion about allowing stretch up to 250% seems to fully solve the problem--I don't see any orphans and the spacing isn't noticeably bad. So I think from my standpoint this can probably be closed.

**Comment by mhosken** [comment]
Awami has a very narrow space and as a result has very little glue to work with when it comes to line breaking. This means that TeX has very little wriggle room when it comes to line break choice. If I go to the advanced tab and enable space stretching and set min: 40, max:300 then the orphans go away (I haven't checked all of them). 300% stretch seems a lot, but remember the Awami space is about half the width of a normal space, so it's not that much.

**Comment by markpenny** [comment]
@mnjames - Please check if it is better now in 0.8.4

**Comment by mnjames** [comment]
Yes, setting the space to allow a larger stretch seems to solve the problem (when combined with the Prevent Orphan Words option).
