### ISSUE TITLE
"Secondary on Left (or Inner) has no effect

### ISSUE THREAD

**Issue by JDNystrom** [sillsdev/ptx2pdf#117]
Ticking or not ticking this box currently (beta 0.8.4) has no effect on the PDF. The primary is still on the left (inner).

**Comment by JDNystrom** [comment]
Same behaviour in 0.8.5.

**Comment by markpenny** [comment]
Yes, we're aware of this, but probably should disable the option when "aligned diglots" are being used (until it has been implemented). It does, however, work for the unaligned diglot because that's a whole 'nother process. We're waiting for the dust to settle and the bugs to come out of aligned diglots before we tell TeX "now listen carefully.... left is now right and right is now left!" :-)

**Comment by davidg-sil** [comment]
I don't understand why you need TeX to do anything. "Surely" you can just feed the secondary to the merge program first. OK,  I guess you'd also need to save all relevant parameters differently too, wouldn't you? 
Arranging the columns Right-Left is fairly trivial (it gets done every other page on inner-outer, after all), but things like 'left gets the footnote callers first' won't change. So unless we're talking about it ONLY being permitted for inner-outer, user/debugger de-confusion is going to be too hard, and I'd firmly recommend doing it in Python.
