### ISSUE TITLE
\s headings - remove \SpaceBefore at top of column/page

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#126]
For \s headings (and perhaps other sorts of headings?), it would be nice for the heading to have no padding above it when it appears at the top of a column or page.

![image](https://user-images.githubusercontent.com/915182/85839134-bbc5d900-b7c4-11ea-8a9f-5c5ca2cef366.png)

Is there a way, either in the stylesheet or in XeTeX, to pull this off?

**Comment by mhosken** [comment]
This should have been resolved in the latest version. Please take a look. This is quite a big change so it may affect a number of existing projects. Also do bear in mind that the heading block still has to be grown to make sure that the main body text stays on the grid. In your example above, unless your \SpaceAfter is 0, you aren't going to see any difference, because the \SpaceAfter results in the heading going off grid and so another line needs to be inserted in front.

**Comment by viverechristus** [comment]
You mean 0.8.6?

**Comment by markpenny** [comment]
No, this will only be in 0.8.7 - hopefully out in the next day or 2
