### ISSUE TITLE
Add a button to swich between companion project / configuration for diglots

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#127]
It's too easy to accidentally apply a setting intended for a monoglot configuration to the diglot configuration instead, and vice-versa. A nice button (not on a tabs?) to flip between the 2 companions would probably save a lot of frustration and time.

Maybe also a 'copy this configuration to X project' would also be handy.

**Comment by mhosken** [comment]
It's the return to primary button that is tricky. Since a secondary project config can be the secondary config for two different diglot projects, I don't think we can derive the primary for a secondary from the filesystem. I suggest, therefore, that the only way to get the 'go to primary' button active is to have pressed the 'go to secondary' and if you change the config via the Basic page then all buttons are lost.
