### ISSUE TITLE
span*0.6 in glossary 

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#135]
It's currently impossible to set a size in non-piclist image definitions, because TeX gets told to treat numbers as letters, and therefore 0.6\dimen0 is not recognised as any kind of measurement any more than fred\dimen0 would be..

Options... 

- somehow make them numbers again? 
- Some way of getting piclists working without verse numbers to hang things on? 
- Crude hack to spot this and 'behind-the-scenes' manipulate the image with white-padding at the sides of the image so that at "full-width"  the image only appears to be 0.6 of the column wdth?

**Comment by davidg-sil** [comment]
- Or: can  \pic handling be re-written so it temporarily changes catcode of numbers before number parsing?

**Comment by davidc86** [comment]
It would be helpful to us if non-scripture books would by default handle pictures "in-line", so that they are not positioned anywhere on the page in particular (not Top or Bottom), but rather dealt with paragraph by paragraph, so if a title or a paragraph occurs first, it goes above the picture, than the picture, then the next paragraph and text, etc. This would help me get my "Maps" section of the PDF to come out looking better than it does now (where PTXprint puts the first map ABOVE the title of the "book").

**Comment by davidg-sil** [comment]
I've opened a new issue for the in-line  pics. It makes it easier if there's just one issue per thread

**Comment by davidg-sil** [comment]
Fix for this issue committted.
