### ISSUE TITLE
Regression in v8.8 doesn't pay attention to the Reference caller settings

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#145]
I usually don't mark callers for \xt (cross-references) but I noticed that in the text, if the \xt ref is set to "empty"/don't show, PTXprint still leaves a blank spot for it. (Unfortunately Paratext tends to put the \xt refers at the beginning of a verse between the verse number and the first word, so the gap can be huge. But that is another issue.)

The problem is, I set it to show the † character in both the text and the references below, but it still doesn't show. So I'm guessing there is a bug in that setting.

Here is what I see in the config file:
![image](https://user-images.githubusercontent.com/65363206/87487861-caa5eb80-c60c-11ea-85fd-1192d44b4040.png)

Here is how it is set on the Head+Foot tab: 
![image](https://user-images.githubusercontent.com/65363206/87487902-e610f680-c60c-11ea-9c40-d2c108668880.png)

**Comment by markpenny** [comment]
I'm confused as to what you have in the SFM text (within Paratext), and what you want in the output.
PTXprint will only apply the 'dagger' as shown above if you're used '+' in the SFM. If there is a '-' or some other character, then I would expect no caller, or the non-standard caller to show in the PDF.
Are you wanting these settings to completely override whatever you've told Paratext? If so, then we need to think through the possible implications of doing so (for other users).

**Comment by davidc86** [comment]
Okay, right. I what you mean. I had assumed that this dialog would overwrite anything specified in the SFM because it gives the option to enter a user-defined "caller in the text". In Paratext, the text and cross-reference show a *. But the cross-reference is MARKED in the SFM with a "-" as in: \x - \xo 1:3-4 \xt 2Kor. 4:6\x*

Other export tools like Pathway and SAB allow us to specify output behavior different to the Paratext specifications, so I had assumed this acted the same way. 

I had wanted to be able to experiment with whether we'd actually like to see the callers marked in the text or not (without having to change all those SFM specs in the actual project text itself.

Still, I'm leaning towards not showing it anyway, but it does look bad in the text will a very large gap between the verse number and the first word. (I have wished for quite some time that the original PT specs would have but the \x fields at the END of the verses not at the beginning. (I mentioned in a meeting once that having them at the end would be more convenient for us, and Nathan Miles was kind of shocked by this! But it does make it easier for formatting and layout and spacing etc. if the verse numbers are connected to the first word with a mini-hard space. (But that is another issue.) I suppose I could run all the books through a fancy process that might work without messing stuff up that would move the \x fields to the end of a verse. (Gets trick with "words of Christ" formatting and other stuff like footnotes back there too.) 

Right. So if this won't allow us to override the "-" setting in the SFM, then it is not like those other apps, and maybe a wording tweak here might make it clear that if we accepted the default \x - markings when we inserted all of our \x fields in Paratext, then this option is irrelevant. 

(BUT this makes me wonder how PTXprint will handle it if in _some_ books people used \x + rather than then standard \x - . So in that sense, allowing the user to use these PTXprint settings to override both the \f - or \f + and \x - or \x + SFM listings would make the output consistent (where the user might not have been consistent across books.)

**Comment by davidg-sil** [comment]
There *shouldn't* be a gap where the caller would be if callers are turned off.  If there is, that's a bug.

Re: what paratext shows... if you ask paratext to show you the "preview", then you'll see that there are no callers shown for \x -. This is because, as you note, Paratext's  \x -  default actually means "No caller" according to the standard. This is fine if the \x 's are all at the start/end of the verse, but less useful if you carefully position it and expect a caller. Also the paratext help is unclear. In one place it says - means no caller, in another place it says 'paratext will show a star' or something like that, without mentioning that it only shows a star in some modes. A bug report has been submitted about this. Hopefully it'll get sorted in some future release.

The TeX macros will almost certainly continue to obey the "\x +" , "\x -" , or "\x SeeBelow"  that they get given... what PTXprint gets told to pass on to them is another issue, of course.

**Comment by davidc86** [comment]
That is very helpful information. Well, then there is a bug such that the gap where the \x field is stored in the text is still showing in the PDF even though there is no caller:

![image](https://user-images.githubusercontent.com/65363206/87669590-46528600-c73c-11ea-8197-ac339cc2f576.png)

If you look at the space after 5:1 and 5:3 you will clearly see that gap. Do we need to make a new "Issue" or just rename this one since this one is irrelevant?

**Comment by davidg-sil** [comment]
Don't bother renaming / making another issue, I've removed the space the caller normally goes in when there is no caller.

There's one gotcha though: You **must** have a space after the verse number (how else does it know the verse number stops?) and there's a pre-defined gap between the verse number and the the text.  But if you then have a space after the note like this:
```
\v 7 \x - \xo 1:7 \xt Psalms 104:4\x* “God makes his angels like wind
```
then because a space after the \x*  gets included in output, that makes two spaces, and you get this:
![image](https://user-images.githubusercontent.com/58848232/87769922-fdc3c700-c826-11ea-9639-12b61f2c61fc.png)
when normally you get this:
![image](https://user-images.githubusercontent.com/58848232/87770064-2ba90b80-c827-11ea-9e3c-f8cf1126439c.png)


So for a verse-initial, no-caller note,  to make there **really** be  no extra gap, the usfm should be like this:
```
\v 7 \x - \xo 1:7 \xt Psalms 104:4\x*“God makes his angels like wind
```
![image](https://user-images.githubusercontent.com/58848232/87769665-a291d480-c826-11ea-95db-857498a42329.png)

**Comment by davidc86** [comment]
I see how that would work, but unfortunately Paratext automatically puts in that extra space. And it is unlikely any normal user would notice it and think to delete it. So is there any way to have PTXprint preprocess the gap between the verse number and the first "real" text and truncate it to a single, fixed-space space?

**Comment by davidg-sil** [comment]
Removing the gap after the verse number breaks things, badly. removing the
gap after the note would normally break the layout. I don't envy someone
writing a regex to do it, but it is probably possible. It would be quite
specific and fragile too, I expect.
