### ISSUE TITLE
Title for ToC doesn't support Indic chars

### ISSUE THREAD

**Issue by beniza** [sillsdev/ptx2pdf#15]
When tried to change the title of the ToC, the text didn't appear correctly on the tool. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/12891019/69472943-63fe6400-0dd6-11ea-9cda-c0621f136f2d.png)

**Comment by beniza** [comment]
Okay, I've also noticed that the app is not able to read the font file. Here's the log

```
Reading Paratext stylesheet "E:/My Paratext 9 Projects/MAL10RO/custom.sty"...kpathsea:make_tex: Invalid filename `Rachana:', contains ':'

! Font \font<p>=Rachana: at 12.0pt not loadable: Metric (TFM) file or installed
 font not found.
\s@tfont ... =\typef@ce \space at \p@ram \dimen 0
                                                  \fi \csname font<#1>\endcs...

\@ddcvhooks ...numbersize <\dimen 255 \s@tfont {p}
                                                  \s@tfont {c}\setbox 0=\hbo...

\@netimesetup ...upsizes \defineheads \@ddcvhooks
                                                  \@ddspecialhooks \global \...

\ptxfile #1-> \@netimesetup
                            \gdef \ch@plabel {} \initp@rastyles \initn@testy...
l.148 \ptxfile{combined.toc}

No pages of output.
Transcript written on ptxprint-TITMAL10RO.log.
cd E:/My Paratext 9 Projects\MAL10RO\PrintDraft; xetex ptxprint-TITMAL10RO.tex -> 1
```

**Comment by beniza** [comment]
I tried using several other Malayalam fonts and I get the same error message
```Reading Paratext stylesheet "E:/My Paratext 9 Projects/MAL10RO/custom.sty"...kpathsea:make_tex: Invalid filename `RaghuMalayalamSans:', contains ':'

! Font \font<p>=RaghuMalayalamSans: at 12.0pt not loadable: Metric (TFM) file o
r installed font not found.```

```
Reading Paratext stylesheet "E:/My Paratext 9 Projects/MAL10RO/custom.sty"...kpathsea:make_tex: Invalid filename `Manjari:', contains ':'

! Font \font<p>=Manjari: at 12.0pt not loadable: Metric (TFM) file or installed
 font not found.
```

**Comment by markpenny** [comment]
Yes, I'm aware that *some* of the Indic scripts aren't rendering right in GTK+. I'm not sure why that is, as Devanagari is working fine (but most of the Dravidian ones are certainly not!) :-(  We'll see what we can find...
About the fonts, Windows now puts fonts in different locations on a per-user basis, and I'm wondering if that has tripped things up. Could you try this with at least one font to see if it solves the "can't find font problem": Uninstall it, and then right-click on the font and select the Administrator option of "Install for all users". You'll probably need to restart PTXprint for it to find the newly installed font.

**Comment by markpenny** [comment]
OK - the rendering of the fonts in the fields on the form has been fixed. I'm not yet sure what I can do about the Font Chooser not showing things in their native font/script. We may end up re-working this (font-chooser) area at some point. For now, I'm closing this issue.

**Comment by devosb** [comment]
Even with the fix I suspect that user installed fonts (as opposed to admin installed font) would still be a problem. I agree with Mark that fonts should be installed with admin privileges (I think the wording in Windows 10 is something like Install fonts for all users).

**Comment by markpenny** [comment]
Yes, it would be good to have more help readily available for these kinds of common issues that users can face. Maybe the tool itself could detect that a font hasn't been installed in the correct way and prompt the user to re-install the font (for all users) in order to make use of it. BdV - do you want to include the link to that information on the PT site?

**Comment by devosb** [comment]
A previous post on this issue is on a [Paratext Support](https://support.paratext.org/t/non-admin-installed-fonts-on-windows-are-not-found-by-printdraft/3030) site (might require a login). [Stack Exchange](https://tex.stackexchange.com/questions/482779/fontspec-and-microsoft-store-fonts-on-windows-10) has a useful thread on this. The Stack Exchange thread mentions adding the location of the user installed font to `fontconfig`, except that location seems to be unreadable. I have not looked into all the links in that thread, that is to say, I don't have complete information on this. Even if making the location of the user installed fonts readable by `fontconfig`, I don't know what else might break in Windows by doing this. Presumably Microsoft made it unreadable for a reason.

I suspect a solution is to look at the output of `fc-list.exe`, and if the requested font is not in output of `fc-list.exe`, then assume the font is user installed, and display a message saying to install the font with admin privileges.

**Comment by markpenny** [comment]
@mhosken I'm wondering whether, when a user selects a font (i.e. when font changes) we should just check to see if the (cached?) fc-list contains this font (as BdV suggests above). And if not, then issue a warning message with specific instructions on how to uninstall, and properly install the font for all users.
