### ISSUE TITLE
How to place a full-page image? (when we write that)

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#151]
I have a map that will look best if it takes up the whole page (I mean the main text area, not taking over header and footer space).

However, it's not clear that this is possible (at least with PicList?) because the image has to be placed with the verse it is attached to, as far as I can tell.

Is there a way to accomplish this? (Ideally I'd like to do it using PicList, so I can maintain control over the placement of other images via PTXPrint, too.) Thanks!

**Comment by davidg-sil** [comment]
Not yet.

**Comment by davidc86** [comment]
I too would find the occasional use for a "full-page" option for a picture.
Maybe v1.1 could consider a hack that would allow us to specify "next available full-page" (i.e. PTXprint would encounter this picture in the PicList and continue to fill up the page with verses until the page-break at which point it burps out the picture full size, sends a page-break, and continues sending verses. 

(Be aware that I have absolutely NO IDEA how PTXprint and the formatting process actually works, but as a user, this would be how I'd envision it working if I specified a "full-page" picture and attached it some verse. I would even expect the next chapter to be output if the bottom of the page still has a ways to go. Then at the page-break, out goes the full-page illustration.)

**Comment by davidg-sil** [comment]
That is almost certainly the way it will work, yes. But some things need nailing down before the code is written:

1) Given that 'p' is currently used for 'post-paragraph', would you suggest:
a) quickly thinking up a new letter for that functionality to reserve p for page,  before 1.0 gets published and people get used to using 'p' for 'paragraph'.

b) some other memorable code for page e.g. 'P' 'page is bigger than paragraph', 'w' for 'Whole page'.

2) Is there a case for an image entirely filling the page, without running-headers/footers?  How would this be specified and distinguished from a 'normal' page which still has the header, etc? (p/P might  be nice here, if 1(a) is chosen).  

3) At present,  images are scaled by setting the width. Within XeTeX they can be scaled to a given width or height without changing its aspect ratio. If both height and width are specified, the image will be distorted. We do not have access to the image's dimensions from the macros, so somethig must be specified.
 I assume there will be many cases where 'span' is not much use and an additional  measure  e.g. 'height*0.9'   will be wanted, which scales an image to 0.9 of the space within the vertical borders of the page.  If the image is being rotated, then scaling the image's width to 'height' is exactly what's wanted, but a tall-thin image would want scaling based on its height, not its width. Would Ph / Pw be a good way of specifying this question, or would some other method, e.g. capitalising height/span/col or using another USFM3-style tag be better to indicate what is getting scaled to what.

4)  At present the x-xetex USFM3 tag (or parameter 8(?) in USFM1 notation) allows adding e.g. "rotated 5' to give rotation by 5 degrees (or any fixed angle). I imagine that a page-number-dependent clockwise / anticlockwise 'rotate so image top is at binding' / 'rotate so image bottom is at binding' might be a preferred option. How should that be handled?  As part of the location? As an alternative to the (directly given to TeX) x-xetex tag? As another USFM-3 tag (e.g. rotated="binding" / rotated="edge" / rotated="5")?

**Comment by davidg-sil** [comment]
MH's current ideas:
"page" gets added to span/col options for a 'within the margins page' and "full" for a 'all the way to the edge" image
scale="0.65" as a scale factor in USFM3-style format (replacing "*0.65").

My thoughts:
I really prefer the idea of keeping page-position away from size, that seems cleaner to me. But, a pageful is a pageful, without much choice about things, so maybe it doesn't matter much.

scale="height*0.7" would solve instructing the code to scale the image's height rather than width, but if there's going to be decoding of the text*number, why not keep size="span*0.7", scale="height" ? (or perhaps rather than **scale**, **fit** might be a better name?) As in fit the (height/width) into size.

**Comment by mhosken** [comment]
Here's how I see it working: *size* and *scale* work together. The basic size allocation (column, page width, full page +/- margins) is specified by the *size* attribute. From there, the image may be further scaled by *scale* (usually < 1.0). Since scaling is always linear, there is no need for *scale* to be anything other than a simple float.

The current implementation does everything in terms of width. Therefore the only real difference between a size of span or page is that page allocates a whole page for the image, while span allows for text on the page. Clearly also the intended aspect ratio of a page image would fill the page. Ptxprint does some clever tricks behind the scenes when it copies the images used for figures to ensure that images have an appropriate aspect ratio for their intended size by adding transparent borders as needed. But that is an implementation detail.

Therefore *scale* should only need to be used for effect and not to get things to fit.

Notice that some *pgpos* values are not compatible with some *size* values. For example, `pgpos="p"` is incompatible with `size="span"` since inline images can only have a size of `col` when in 2 columns. The macros do the Right Thing in those situations and just treat inappropriate values as the most obvious appropriate value (everything becomes 'col'). In the case of cutout positioning, *scale* is useful to decide how much horizontal width of the column will be cutout, with the default 1.0 being the whole column width.

That's the proposal, which naturally implies that it hasn't been implemented yet. Once we agree the proposal, we will implement enough in v1 to support current behaviour and leave adding features like page and full support to a later version (falling them back to span in v1).

**Comment by davidg-sil** [comment]
In taking design decisions so far, I think there's been an implicit principle that while we don''t preserve everything in the USFM as is (e.g. stripping out pictures into a piclist) or inserting non-breaking spaces to end of paragraph if the user wants them,  we don't make it so that the macros fundamentally rely upon certain action having been perfomed by a front-end.  i.e the user interface enhances, verifies, hand-holds and makes things much simpler, but things don't actually start falling apart if you don't use it to make subsequent changes. 
Padding borders in python means that the user gets a differeint result between running the code "by hand" vs "by python" if they change the margins in the TeX code or swap  an image in a piclist.

That seems to me crossing a line which makes me feel very uncomfortable. 

I'm also wary of applying transparent borders to images because of licencing restrictions and also JPEG image quality is adversely affected by decoding-recoding, o it seems like a bad idea too. 
Supplying fit="height" seems to me much more appropriate.

Oh, FWIW, last time I looked at them the macros only gave a warning about using size="span*0.5" in a position  that was column-width. 

**Some worked examples...**
 * Tall-thin map (e.g. the Jordon valley, North-up):
```
size="page" fit="height" 
```
The hieght of the image is fitted to the height of the page

 * Squarish map:
```
size="page" fit="width" caption="Solomon's temple"
```
The width of the image is fitted to the width of the page.

 * Wide-short map (e.g. Paul's journey to Rome, rotated so the binding is image-top)
```
size="page" fit="width" rotate="binding"
```
(because of the 90 degree rotation, the code fits the width of the image to the height of the page)

* Tall-thin image, rotated  to a cutout in a single column glossary, 
```
size="span" scale=0.33 pgpos="cr2" rotate="85" fit="height" caption="Egyptian single-edged sword"
 ```
Because the image is rotated > 45 degrees, the code fits the height of the image to 0.33*span width.

**Comment by mhosken** [comment]
I see what you are proposing. I think we can avoid `fit` by having TeX work out whether the image is wider than it is tall according, since `fit` is really just asking the user to specify whether their image is wider than it is tall. If we do that, then we get the same agreement over `size` and `scale`.

I propose we push the question of `rotate` down the road. It's not the end of the world if people rotate their map images outside TeX, and we still have x-xetex for the moment.

**Comment by davidg-sil** [comment]
Yes. loading the image to measure it ought to work. so we can indeed avoid fit= at the cost of some CPU cycles. Are you proposong some parsing of x-xetex, to implement rotate=binding / rotated=edge? I suppose that's acceptable too.

**Comment by davidg-sil** [comment]
A few more implementation details:
Do captions make sense with full-page images?
I can imagine a full-page image where 'edge' alignment was wanted (i.e. push the image far from the binding). Should this even be the default? Are there other sane page for full or page images? Should the image 'bleed' over the edge of the paper?

**Comment by markpenny** [comment]
I would say that any normal image can be made bigger to fill almost the entire page and can (optionally) have a caption. BUT by definition, a full-page image needs to fill the whole printable area and therefore NOT have a caption, nor header/footer. I would expect it to take into consideration the page gutter and the margins, but nothing else.
I wouldn't encourage images that go right to the edge of the page and possibly even beyond (bleeding over the edge of the paper).

**Comment by davidg-sil** [comment]
I'm not fully happy about the current implementation, but here is what's in place now:

* `full` and `page` have been added  as sizes. `full` indicating the paper size, and `page` indicating the normal printable area (margins and gutter).
* new `pgpos=` values `F` and `P` for positions. [Until I hear a consensus around better codes].
* Images are scaled by width* relative to the paper (`full(*x)`) or margins (`page(*x)` and other measurements). But if they are taller* than the area it ought to fit in, it is reloaded  with the image height* scaled to the relevant dimension.  There's no way to request an image to be scaled relative to the page height.

*Note: for figures with new `x-xetex="rotated=binding"`, etc, read height and width as being swapped.

* The caption is still produced, but may be pushed off the page / margin area. If you don't want a caption, don't specify one!

Gotchas:
* If you specify conflicting parameters e.g. `size="full"` `pgpos="P"`, then the code will try do do what you've asked for.
* Unexpected behaviour if you specify 2 (full / page) images one after another [work in progress!]

**Comment by viverechristus** [comment]
This is behaving just as expected. Thank you!
