### ISSUE TITLE
Border placement with binding gutter

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#152]
I'm producing drafts with a standard page size of 5.25" x 8.25", and a binding gutter of 0.2". One (minor, slightly annoying) problem, the binding gutter is only defined in mm. So I've entered the closest approximation of 0.2", as 5.1mm. But the bigger problem is that I want a page border on each page, and that appears in the .tex file as:
\def\PageBorder{"path/to/file/MIGMA-NT Page Border.pdf" width 5.25in height 8.25in}

Note that the width and height are given as the **entire** page size. But the page border is likely defined by the page size MINUS the binding gutter. E.g. this page border PDF is actually defined as 5.05" x 8.25". But PTXPrint assumes it covers the whole page and applies the page size so distorts it. I think you want to make the width to be the page width MINUS the width of the binding gutter. Since they are given in different units, you'll have to decide on a common unit to do the calculation.

Another possibility is to not include width and height dimensions - whatever the user defined them as. That obviously doesn't work, however, when you try to use a page border that was designed for a different page size.

**Comment by davidc86** [comment]
I did wonder something: If the border is designed for say, A5 paper with equal margins. But then we add a gutter margin, then either: 1) the border will squish horizontally or, 2) the border will resize proportionally, making the top and bottom margins a bit larger than the outside margins. 

Neither of these are ideal. Seems to me border fig files need to be designed to look right with the exact margins we want including the gutter we need. Because I don't see how PTXprint can figure out which is better: squishing it horizontally, or scrunching it proportionally. 

But if I had to choose a behavior... I'd go with **proportional resizing** rather than scrunching in one direction. But that may totally depend on the border pattern/intricacies whether it is so complex no one would notice it slightly scrunched horizontally, or is it a clear pattern that would obviously look scrunched horizontally.

But maybe I totally off the mark on this. But on our publications, I'm seeing that we haven't yet made the gutter margin as big as it probably needs to be to look nice in a thicker, bound book (rather than say a booklet). So if we actually select an adequate gutter margin, that would significantly affect any border picture that was designed with the full page in mind. 

Your thoughts?

**Comment by jeffheath-sil** [comment]
I think you have to assume that someone who wants a page border does NOT want it to go crashing into the gutter, but only on the page remaining outside the gutter. (I think my original request handles that.) Someone who designs a page border specifically for that a publication would take the gutter size into consideration. People who are just choosing something that was pre-formed, maybe just as a proof of concept, should probably get the image that they chose stretched to the page size (minus the gutter) in both directions. If you do proportional, you might get the case where one set of borders encroaches too much into the page.

**Comment by davidg-sil** [comment]
The problem with stretching/scaling the image is that you end up with horizontal lines and vertical lines having different widths (for an ugly demo, try putting a section-decoration around the whole page like I did by accident).

A better approach would be for the decoration to be somehow generated based on the size of the page (probably it would still be more efficient if this was done as a separate file). There are programatic picture-describing packages for TeX, so perhaps someone brave could try writing a border-generator algorithm in TikZ.
Possibly using the approach [here](https://tex.stackexchange.com/questions/159463/fancy-styled-borders-in-latex), and output TikZ-code via inkskape would be a start, especially if the 'borders' could be made from corner-pieces and didn't need to actually join up in the middle, or could just be joined by a series of dots or sine-waves or something else that's easy to expand.

**Comment by davidg-sil** [comment]
I didn't read far enough! The  pgfornament  package looks very interesting for assembling borders!

**Comment by jeffheath-sil** [comment]
No doubt it would be best to have some package that automatically produced borders, but I imagine that would take some work to implement - probably not for version 1!

In the meantime, I think stretching the image chosen to the page size (minus the gutter) really is the best choice. Yes, you can make something really ugly (like your putting the section decoration around the whole page), but if you choose a border that is roughly the same aspect ratio as your page (minus the gutter), it should give you something reasonable. And if you want something better, then work with a graphic artist to produce something better (or load the PDF sample border in Inkscape and make modifications yourself).

**But I'm afraid that with this extra discussion my original request with this issue might get lost: The page border images need to get scaled to the page size minus the gutter.** Otherwise if you have a gutter, your page border will not be positioned properly.

**Comment by davidg-sil** [comment]
I'm "thinking aloud" here... Concerned about whether the border will be centred properly.
Please accept apologies... I want to work out if it does the right thing.
 For simplicity, if I imagine a sheet of paper which is 20units wide, 2 unit's margin and this 16 units of text width, and a border image of the same size as the page, with its own margin. The centre-line of my border just happens to be 1 unit from the text and 1 unit from the edge of the page, because this is a thought experiment. 
I then apply a 2 unit binding gutter, and shrink my border by 2 units. My text width is now going from 4-18, instead of 2-18. My border is now 18 units wide, not 20. The edge of the border is now 18/20= 0.9 of a unit from the left and right edges of the border-image.
So.. on the outer edge of the page, the text-edge hasn't moved, so I have 1.1 units from the text to the border, and 0.9 units from the border to the edge of the page. 
On the inner edge, which is what worried me, I now have 2 units until the binding gutter, and then 0.9 units until the border. So i get 1.1 units from the text to the border again. 
Excellent, it would scale almost-nicely.

Now to my question... This 
```\def\PageBorder{"path/to/file/MIGMA-NT Page Border.pdf" width 5.25in height 8.25in}``` Is problematic to me in two ways.
- How much history is there of such use (specifying an image size) - would we break everything if the macros handled it?
  If we could guarantee that the borders were always intended to be set edge-of-image = edge of page, it would make more sense if the macros themselves calculated the width and height. 
- BUT....  the code in the macros at present seems to assume that the border may have no/insufficient space around it, and adds horizontal and vertical spacing to centre it on the page (before shifting the resultant box by the  binding gutter).
If someone is using images that have approximately no outer margin, then the code blindly forcing the border to fill the page is the wrong thing. It would be better to calculate how much bigger the border ought to be than the text area. 

So in one case, (border image has margins) the border  ought to be scaled to \pagewidth - \BindingMargin, but in the other (no margins), the border ought to be scaled to a width of \textwidth + 2* the border thickness, in which case it would centre nicely in the gap between the text and the side of the page.

In any case, I agree that PTXprint forcing the image to page size is a mistake. Perhaps it should have a tick-box that says the pageborder has margins to determine how to calculate the size? 
i also think parsing the above ```\def ``` would be a pain, and I'm not sure how we should proceed. Full manual control of the width/height in an 'Advanced page borders' section?   Hopefully @markpenny or @mhosken have some input.

**Comment by mhosken** [comment]
I propose that if we want to do anything more with borders (using fonts, generating border images, etc.) that be raised as a separate issue.
