### ISSUE TITLE
Adjustments not spread across whole paragraph

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#161]
There seems to be a problem with adjustments. If I provide an adjustment of JAS 2.1 +1, it does this to the paragraph:
![image](https://user-images.githubusercontent.com/14953913/89175196-29f97a80-d57f-11ea-9ef8-848d10466629.png)
In other words, it looks like it tries to put the whole adjustment into the first verse of the paragraph, instead of spreading it out across the paragraph. This is a show-stopper for us...

**Comment by davidg-sil** [comment]
This looks really bad, and I'm very surprised TeX has allowed it: there are normally rules to stop such changes in the spacing. Some questions:
* Are there any non-breaking spaces? (in the temporary file that gets to XeTeX, e.g. near those short words). 
* Is this diglot, or monoglot?
* And is it at the bottom of a column? 
* Is there an image attached to any of those verses? 
I wonder if there has been some nasty interaction with the column-breaking / balancing and the adjust-list or image-placement code and adjust-list.

**Comment by jeffheath-sil** [comment]
This is a plain monoglot. No images. Not at the bottom of a column. There are no non-breaking spaces, but I change the space around some punctuation to basically non-breaking spaces with \kern.

As a sanity check, I went back to the ptx2pdf macros of Paratext 9 as of last September (before PTXPrint changes). Those versions of the macros work fine with the adjustments (MAT 5.31 +1):
![image](https://user-images.githubusercontent.com/14953913/89318227-6956c280-d676-11ea-8da7-73b2d72746d2.png)

But the latest macros (updated a few days ago), give this:
![image](https://user-images.githubusercontent.com/14953913/89318194-5fcd5a80-d676-11ea-8321-d5e94ea1aaf3.png)

I can send you those version of the ptx2pdf macros if you don't have them handy...

**Comment by mhosken** [comment]
Yes. I think this is due to my misunderstanding of how \emergencystretch works. I've dropped the value back to what it was back then. You can test this out by adding the line:
```
\emergencystretch=1in
```
To your ptxprint-mods.tex

**Comment by jeffheath-sil** [comment]
This does seem to be working correctly with the latest macros. Thanks.

**Comment by mhosken** [comment]
This is the flip side to #162. Rather than have two issues discussing the one issue, I will close #162. But that means we have to balance the danger of overfull boxes and against whitespace handling within paragraphs.

There are two controls open to us in controlling line breaking: `\tolerance` and `\emergencystretch`. There are potentially 3 passes over line breaking. If the badness of the paragraph is outside tolerance in the first 2 then then emergency pass happens and each line may expand (with no extra cost, sigh) by up to emergencystretch. So increasing emergency stretch makes spaces more stretchy and therefore the tolerance can be met and no overfull boxes will happen. Alternatively one can increase the tolerance, but then overfull boxes can happen. What I would really wish TeX had done would be for the emergency pass to allow infinite stretch tolerance and still keep a tight shrink tolerance. But noooo, that's not possible.

Anyway, the short of it is that we have to somehow set these two parameters automatically to handle making things look really good regardless of how long words are, etc. One option is to keep things loosy goosy until you want to fiddle with paragraph lines and then to tighten it right up. So if you say +1, then emergencystretch is dropped to 0 (so no emergency pass) and if you get overfull boxes, you just can't do that paragraph adjustment.

Thoughts and TeXnical wisdom gratefully received.

**Comment by jeffheath-sil** [comment]
I'm not that much help on TeXnical wisdom, but I would say it would be acceptable to refuse a paragraph adjustment. Just make sure you report it as an error in the log, so the user knows to try a different paragraph. But just to make sure we are hitting the right problem, I am not getting these overfull boxes because of paragraph adjustments. I just wanted to make sure that was clear.

**Comment by jeffheath-sil** [comment]
In case it's useful information... I thought I would try adding a paragraph adjustment +1 to the overfull \hbox paragraph (issue #162), but it didn't change anything:
![image](https://user-images.githubusercontent.com/14953913/89409836-978dde00-d71a-11ea-8dd9-f5a96e44eb36.png)

(This is result of MAT 4.3 +1) Furthermore, I also tried adding a +1 to MAT 4.1, and it shifted the words around, but didn't add a line. (The screen shot above is actually after the +1 adjustment on MAT 4.1.) I tried MAT 4.1 +2 and that gave the same result as +1.

I also tried an adjustment somewhere far from any overfull \hboxes, and it didn't adjust the number of lines in the paragraph. So I guess the adjustment code is broken now...

**Comment by davidg-sil** [comment]
I think this is why hyphenation got invented. There are these solutions
that I'm aware of:
1. inter-word spacing
2. intra-word spacing (ie between characters)
3. overfull boxes
4. hyphenation
5. ragged edges
6. [not applicable to scripture!] rephrasing
7. Alternate spellings [see Shakespere]

Personally, I'd opt for hyphenation.

**Comment by jeffheath-sil** [comment]
For my need (and I would guess for most people), hyphenation doesn't really have anything to do with this issue. Yes, hyphenation may be helpful in dealing with overfull \hboxes, but the issue I'm trying to deal with here is using paragraph adjustments to manually do column balancing. So if I just want to add one line to a paragraph, to better fill a page, I just want slightly more space between each of the words in the paragraph so that it spills onto the next line.

The issue here is that XeTeX is for some reason trying to stuff all of the extra space needed into that first verse of the paragraph. This isn't the way adjustments used to work...

(Hyphenation may be able to help this issue marginally, but I think it is missing the mark of this issue.)

**Comment by jeffheath-sil** [comment]
I tried a paragraph adjustment with the latest 0.9.1 beta, and (no surprise) the results are the same - all of the adjustment gets crammed into the first verse of the paragraph. But I did notice one thing that was a little strange. The last line of the adjusted paragraph is almost full. In past days, it would just put a word or two on that last line. I mention this just in case it helps figure out the problem.

Here are the before and after the paragraph adjustment:
![image](https://user-images.githubusercontent.com/14953913/89622852-97f9b680-d88b-11ea-9a29-82c32f7d82d8.png)

![image](https://user-images.githubusercontent.com/14953913/89622921-b1026780-d88b-11ea-97fb-e84ce62e7d71.png)

**Comment by jeffheath-sil** [comment]
And just FYI, I tested paragraph adjustment with the macros from 0.7 beta, and they properly spread the extra space of a +1 adjustment throughout the paragraph, putting just a word or two on that last line. (I pre-process to put a NBSP before short words at the end of a paragraph, so they don't sit by themselves on a line.)

**Comment by mhosken** [comment]
I am in the process of proposing a change to TeX that will help address this. It could take a while to get the community on side.

**Comment by jfkthame** [comment]
Before getting in to potential TeX engine changes, I think we need a better understanding of what has changed in the macros/setup. Things used to work OK for Jeff, and now he's seeing these issues. What, exactly, changed resulting in this issue and #162, and why can't things continue to work as they used to?

**Comment by jfkthame** [comment]
> I'm not that much help on TeXnical wisdom, but I would say it would be acceptable to refuse a paragraph adjustment. Just make sure you report it as an error in the log, so the user knows to try a different paragraph.

Just noting that it has always been the case that a paragraph adjustment request may not have any effect -- or may have a different effect than was requested. (E.g. I've seen cases where requesting +1 actually makes the paragraph two lines longer, and it's impossible -- short of manually inserting forced line-breaks or lots of ties -- to get a +1 result.)

So I've always viewed this as something to be done interactively, setting a few adjustment requests and then reviewing the result, and iterating towards a satisfactory solution.

**Comment by mhosken** [comment]
Previously `\emergencystretch` was 1inch, but that can cause overfull boxes as Jeff encountered. So we increased it to 11inch and then we get the spacing problems we see above. All ideas on how to get it to do nice spacing and not overfill boxes would be gratefully received. But we have tried both options and we get hammered one way or the other.

**Comment by jfkthame** [comment]
But (according to #162) he _wasn't_ previously getting overfull boxes (nor this spacing problem).

So there's more to this.... other things must have changed as well.

My instinct would be that `\emergencystretch` shouldn't normally be set to more than a significant fraction (20%? maybe as high as 50%?) of the column width. If you don't want any overfull boxes, no matter how bad the spacing may have to be to achieve this, set `\tolerance=10000`. Though my personal preference would be to keep it a bit lower, assuming the result is to be manually reviewed rather than expecting a completely automated process to produce a good result in every case.

Given long, non-hyphenatable words and narrow columns, there are going to be some appalling results no matter what. If you don't want to review them and tweak things manually, `\tolerance=10000` is the way to go.

Still wondering why Jeff's example that used to have _neither_ of these issues got broken, though.

**Comment by mhosken** [comment]
After JK's bike shedding. I have found the place where `\tolerance` had been lowered and cleared that so now `\tolerance=9000`. `\emergencystretch` is now back at 1 inch without lots of overfull boxes.

I've also written [some thoughts](https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/glue.md) that take one through the maths of what is going on with tolerance, space stretchiness and emergencystretch. Hopefully people won't need it. But it may help to remind me in the future, if no one else :)

**Comment by jeffheath-sil** [comment]
I am very grateful... Not only does it now seem possible to perform paragraph adjustments correctly (a  requirement, by the way, for the NT that I am currently typesetting, and I didn't want to go back to version 0.7), and I don't seem to be getting any nasty overfull \hboxes... But I have also learned the meaning of bike shedding! I can relate to that term since I tend to do quite a bit of dancing around the edges when it comes to XeTeX. (Being lazy and not wanting to spend the time it would take to really master it.)

**Thank you!** You have really made my day, which happens to be the Chadian independence day holiday. So much so that we just celebrated with a military jet and helicopter flyover!
