### ISSUE TITLE
Unchecking "Show callees in notes area" (under Cross-references) Blocks Printing

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#167]
I have been systematically going through two Config files to see which settings might be causing one to fail and the other to run just fine. In the broken Config file, I have "Show callees in notes area" _unchecked_, and it fails to print. But in the good Config file this is _checked_ (even though I have an '-' specified in all my \x fields). When I uncheck this option in the good Config file, it fails to print! So that is at least one difference that accounts for the failure. 

By the way, "callees" may be lexically correct, but it looks like a typo. Maybe "Show caller symbol in notes area" might be clearer? Just a thought.

Also, in the Config file, this field is labelled as "xromitcaller = True" --when we want to INCLUDE the "callees", and it is marked as "xromitcaller = False" when we want to EXCLUDE the "callees". I'm thinking this is backwards labelling left over from when you all flipped the negative terms to positive, right? 

In that same vein, the "fnomitcaller = True" actually means "Show Callee", so maybe both of these Config fields need to be changed to "xrshowcaller" and "fnshowcaller" ?

And I see in the Config file these are referred to as "callers" not "callees". So maybe the UI should just say "Show callers in notes area"?

**Comment by markpenny** [comment]
Thanks for the helpful comments. Here's the latest re-incarnation...
![image](https://user-images.githubusercontent.com/12962708/89968526-21542300-dca8-11ea-86ba-cab8fb30803d.png)
I have avoided the word 'symbol' because for some users it may be a letter or a digit rather than a symbol.

Regarding the question about wording in the config file, I'm beginning to regret switching from the "omit" to "include" - partly because it is so complicated behind the scenes. The 'omit' terminology comes from the switches in the .tex file, so the config file should line up with that - so I'l trying not to change it all yet again. My expectation is that no one would be looking into the raw .cfg file and making edits there. Everything they need should be accessible (and work reliably) through the UI.

I'm wondering if there are remnants of the old settings still sitting in your .cfg file. Have you tried blowing it away and then re-generating it when you print your first job for that project?

**Comment by davidc86** [comment]
That looks nice.
Yes. I am comparing an old Config file with a brand new one (using Beyond Compare), and I am making tweaks in the brand new one a little at a time, to carefully bring it closer and closer to the settings I had in my old Config file (as these are the settings I actually want), in order to see if and where it breaks.

It is this slow comparing and tweaking that showed me that "omit" = True, actually behaves as "Include". 

No biggie for normal humans who only look at the UI. But for anybody who is trying to debug a config file, that is a confusing one! 
If it currently works (UI => Results) then for now, who cares what the internal variable name is for that feature. 
Yes, changing anything is a drag, but "don't omit" is a bit harder to understand than "don't include" so it is probably a good thing you've done.
