### ISSUE TITLE
Getting First Ref on outside of left page, Last Ref on outside of right page with no headers over inner column

### ISSUE THREAD

**Issue by oj-gamache** [sillsdev/ptx2pdf#182]
I don't think this is currently possible - I'm forced to put first and last ref on both pages which gets cluttered.

I think if I set "Last Reference" on the "Outer/right" and select "Mirrored Layout" it should actually put the "First Reference" on the outer/left of the left page. (Currently if I use this setting I get the Last Ref on both outer corners which isn't helpful)

**Comment by mhosken** [comment]
Yes it is possible to have the macros do what you want. Currently this is beyond the ptxprint GUI to present this to you. So, as a workaround, you will need to do a small amount of TeX incantation.

- In the Header+Footer tab set mirrored layout and choose Outer to be Last Reference. That gets one side right.
- In the advanced tab, enable ptxprint-mods.tex and click the edit button next to it
- In the viewer tab, select the ptxprint-mods.tex tab, and add the following to the bottom of that file:
  `\def\RHevenleft{\firstref}` as a line on its own.
- Click save and then run.

Hopefully that will work.

I've marked this bug delayed since we need to decide how and if we want to support this in ptxprint itself without the need for such incantations.

**Comment by markpenny** [comment]
This has been fixed for non-diglot publications (so that First Ref and Last Ref on a page DON'T get mirrored). However, for diglots, we need to work out what should happen to the header(s) in these situations.

**Comment by markpenny** [comment]
@oj-gamache Please can you check that ver 1.1 behaves as you would expect it to with regards to mirroring. We have added Pri and Sec buttons for diglot headers so that you can ensure you get the right (side's) formatting.
Note that if you use these settings, you'll get the last ref on the odd(right) pages and automatically get the first ref on the even(left) page. I hope that's what you were expecting to see...
![image](https://user-images.githubusercontent.com/12962708/91236299-aef53f80-e78b-11ea-8807-9fbc2834b305.png)
If the issue has been fixed, then please close this issue. Thanks.

**Comment by oj-gamache** [comment]
Thanks!

**Comment by oj-gamache** [comment]
Thanks!

**Comment by oj-gamache** [comment]
Thanks!

**Comment by oj-gamache** [comment]
Thanks!

**Comment by oj-gamache** [comment]
closed

**Comment by oj-gamache** [comment]
closed

**Comment by oj-gamache** [comment]
closed
