### ISSUE TITLE
align br and bl images with bottom of next-door column

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#189]
I can imagine this would be a difficult or impossible task, but I'm wondering whether images that span a column and are placed at the bottom of that column can be placed so that they (or their captions) don't protrude below the level of the adjoining column? Here's an example of a moderately ugly protrusion. Some are worse.

![image](https://user-images.githubusercontent.com/915182/90864296-9fa47980-e3ba-11ea-8f29-7329972df788.png)

**Comment by mhosken** [comment]
I think it does but only within +/- a baselineskip (linespacing). You'll notice that your caption is within one line of the right column. So if it were to add a line to the right column, then it would be taller than the left. You can use scale to try to get your image to just the right height if you want so that the image plus caption remains on the grid.

**Comment by viverechristus** [comment]
Thanks.
