### ISSUE TITLE
provide "first/last reference" option for mirrored header

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#190]
Suppose ...

- I'm using the Mirrored Layout, and 
- I want the Outer edge header to have the reference in it, and suppose further that 
- I want the FIRST reference on the outer (left) edge of the left page, and 
- I want the LAST reference on the outer (right) edge of the right page. (But I don't want a range.) 

As far as I can tell, there's no way to do this. I can have each page's first reference, or last reference, on both pages. But not the first on the left and the last on the right. This would be a nice option.

**Comment by markpenny** [comment]
I am aware that we've worked on this recently and this will be part of ver 1.1
But notice from the image below that we also need to be able to specify which side's format settings should be used (font and size) - otherwise you end up with mismatching headers (which are often needed when different fonts/scripts are important).
![image](https://user-images.githubusercontent.com/12962708/91000631-b8f93000-e61d-11ea-8d1b-2a8ad3059566.png)

**Comment by markpenny** [comment]
@viverechristus Version 1.1 should have all the control that you need now, and the mirroring should be more logical too.
![image](https://user-images.githubusercontent.com/12962708/91235659-1a3e1200-e78a-11ea-8acf-32410b7a879c.png)

**Comment by viverechristus** [comment]
This is great, but the interface isn't intuitive. I wouldn't think to specify "Outer (Right)" as "Last Reference" in order to get "First Reference" on the left page!

But it works perfectly. Thanks.
