### ISSUE TITLE
Diglot documentation

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#197]
Is there any diglot documentation available? (I saw reference to an email in another thread, but I don't receive any emails.) All my attempts at making a diglot using various combinations of (e.g., main project plus back translation, main project plus transliteration, transliteration plus main project) have ended in dismal failure, typically resulting in something like this, or worse:

![image](https://user-images.githubusercontent.com/915182/91278296-3d7ab880-e7ae-11ea-958c-b55681e805db.png)

**Comment by markpenny** [comment]
@viverechristus Sorry to hear that this has been more difficult than it should be. I'm happy to add your e-mail address to the Beta-tester's announcement list but that list is probably going to disappear now that we've released ver 1.0 There isn't any documentation YET, but we hope to produce some "end-to-end" explanatory videos on "How to produce a diglot..." etc.

For the moment, here's a basic outline of what you need to do:
a. Open the Secondary(Right-side on odd page) project and ensure that the Diglot setting is DIS-abled/unchecked
b. Make sure that you can print successfully from that project (as it is - a monoglot)
c. Get the size and formatting right, and make sure that the CONTENT settings are the same as you will have them in the Primary (and therefore Diglot) publication (for example, check whether the introduction will be included or not, etc.)
d. (Optional) you can give this configuration a name and save it so that when it is "called" from the other project, you will get the exact settings replicated
e. Now switch to the Primary project (the text which will appear on the left of odd-pages)
f. Ensure the CONTENT settings (mostly on the Body tab) line up with the Secondary project's settings
g. Ensure that the Diglot setting is checked, and that the project (and config) settings for the secondary project are correct.
h. Hit Print, (pray!) and wait :-)

From what I can see above, it looks like one project is including the introduction to the book of Ruth and the other one isn't; so the merging process has become rather confused. [It looks like we may need to improve the robustness of the USFM merging program anyway to cope with unexpected/unmergeable texts better.]

If you still can't get it to work, could you please create a ZIP archive (using the button on the Advanced tab) and send it in an e-mail to <ptxprint support@sil.org> (with an underscore instead of the space). If you are sure it is just a merging issue, then just the following files from the PrintDraft folder should suffice: PrimaryText.tmp, 08RUT[SecPrj]-draft.SFM and 08RUT[PriPrj]-draft.SFM (which contains the merged USFM from both projects). 

Here is what you should be able to create:
![image](https://user-images.githubusercontent.com/12962708/91360659-f8589400-e84a-11ea-81e9-7e6a522f3640.png)
