### ISSUE TITLE
Question: what is the relationship between ptxprint-mods.sty and PrintDraft-mods.sty

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#198]
I just discovered that changes made to `PrintDraft-mods.sty` in `\My Paratext 8 Projects\[project]\PrintDraft` are not having an effect in output. So a little poking around revealed that now PTXprint uses `ptxprint-mods.sty`, and this file has multiple instantiations (one in each saved configuration, plus one in `\My Paratext 8 Projects\[project]\shared\ptxprint`.

I'm wondering what the relationship is among these stylesheets, and which one is called when I click "Print"? If I find a problem in the stylesheet, do I need to change it in all the configurations, or is there one place to change it?

**Comment by mhosken** [comment]
We used to use PrintDraft-mods.sty, but given that different job configurations often vary precisely in .sty styling, we need a configuration specific .sty file, hence ptxprint-mods.sty (as in `\My Paratext 8 Projects\[project]\shared\ptxprint\[config name]\ptxprint-mods.sty` (or `shared\ptxprint\ptxprint-mods.sty` if there is no config). Further, if there is no `shared\ptxprint\[config]\ptxprint-mods.sty` but there is a `shared\ptxprint\ptxprint-mods.sty` then that will be used. So that gives you some level of project shared styling if you need it.

We felt that having both custom.sty and PrintDraft-mods.sty as being project global .sty was overkill. So we took out PrintDraft-mods.sty.

**Comment by viverechristus** [comment]
Thanks. That's clear to me.
