### ISSUE TITLE
Footnotes in RTL text causing LTR flow

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/ptx2pdf#201]
Lines that have a footnote are getting broken and cause LTR flow. See image 1.

The footnote caller (a) should be in the middle of the line. Instead it's all the way to the left and the text that comes after it is put to the beginning of the line (on the right side).

![image](https://user-images.githubusercontent.com/7088137/91705889-e2660e80-eb7d-11ea-9d84-b0c188a4a51a.png)

**Comment by rmlockwood** [comment]
This is a show-stopper for us. Any idea of when this will get fixed?

**Comment by mnjames** [comment]
I can confirm this also happens in the RTL language I'm working in.

**Comment by davidg-sil** [comment]
I'm a long way from working in RTL languages, but trying to typeset English RTL using a test file, I see that there's a change in the output between fef747d9fb8f00199deab764c01d51aaf1fc2a8d (5 Aug):
![image](https://user-images.githubusercontent.com/58848232/93810006-b3abf700-fc56-11ea-93d6-680b4de18417.png)

and its immediate parent: 6fd9afd820e1dd7964fc874a802ed09bccebc503 (15 mins earlier):
![image](https://user-images.githubusercontent.com/58848232/93809932-924b0b00-fc56-11ea-9ac1-3caf7a5ff0f4.png)

(This is a paragraph containing a footnote, but a few lines above it, after a page and a half of introductory text which mostly has RTL word order, except for section titles).

I can't really understand what would causing that change, but if any RTL experts can confirm/deny that's when things broke, I expect it'll help @mhosken to work out how his patch might have broken stuff so badly.

**Comment by mhosken** [comment]
It would help to know when this last worked for you? 0.9?

**Comment by rmlockwood** [comment]
I’m not sure. In 0.4.9 it worked at least.

**Comment by mhosken** [comment]
Hmm 700 commits since then to the point David suggested! Any chance you could test 0.8.6 here https://software.sil.org/downloads/r/ptxprint/SetupPTXprint(0.8.6-beta).exe? That would reduce the search range as to what I may have changed to mess things up.

**Comment by rmlockwood** [comment]
The problem is there in 0.8.6. Got some other versions for me to try?

**Comment by mnjames** [comment]
0.7.0 worked
0.8.0 didn't

I can't test further because those are all the options on the
http://software.sil.org/ptxprint/#downloads page.

If it's possible to run it from command line from the git repository (I've
already downloaded that), I can try to narrow it down further. But someone
will need to let me know what command to use to run it.

--Malachi

**Comment by davidg-sil** [comment]
If you've got the git repository, then you could try the following (probably some improvisation needed):
Lets assume that PTXP represents the uppermost directory of ptxprint (the thing that holds the "examples" and "src" directories). Please forgive me for using / as a path-seperator, it's inbuilt into my brain/fingers.

cd PTXP
git checkout master
git bisect start
git bisect bad
git checkout 0.7.0

Then, run the ancient version of the GUI and generate whatever it is that works, keeping temporary files. (hopefully that option was around back then, I'm pretty sure run-from-command-line wasn't!).
Then, finding the relevant directory..  (paratext8projects/PROJECT/PrintDraft  is probably a good guess) I'm going to call that PD, later on.
TEXINPUTS=.:PTXP/src  xetex ptxprint-PROJECT.tex
If that seems to run wonderfully, great.  Check the resultant pdf (ptxprint-PROJECT.pdf, probably).
If it doesn't, you need to do whatever it is in windows command shell thing that sets 
the TEXINPUTS environment variable, and it needs to have "." (current directory) and PTXP/src (tex source dir). You might need a semicolon rather than colon, backslashes, etc. It's 2 decades since I did this on windows, so please forgive my lack of precision.

Then... it gets a bit easier you have 2 terminals. if you do, then take my cd commands as terminal-switching.
If the PDF is good (in terms of the RTL direction not breaking), then:

cd PTXP
git bisect good
if it's bad, then:
git bisect bad

cd PD
TEXINPUTS.... [[i.e. run the TeX file command]]
check output

cd PTXP
git bisect good   [[or bad as the case may be]]

cd PD
you get the idea, I hope.

The git bisect will jump around in history by an ever-decreasing number of history-points, roughly 9 cycles, according to my copy . 
Eventually it'll say it's found the change that made it go from good to bad (we hope!), 
"abcdef12234123dffacc is the first bad commit"
 and we can all call you an expert in tracking down where things broke.
Get back to normal (at any time you want to give up bisecting history) by typing:
git bisect reset

Hope this helps!

**Comment by mnjames** [comment]
Thank you--those were very clear instructions. And I've never done a
bisection search with git... that was surprisingly easy. You learn
something new every day.

The first bad commit appears to have been
db303caf6f9d3ee1e1d2525269196b25d0a2a123

--Malachi

**Comment by davidg-sil** [comment]
Thankyou! Glad it worked so well. Well, that commit is interesting... 
It was clearly trying to fix some weirdness in diglots with RTL-ness spreading from one side to another. It seems to me very likely that the patch was pretty much a poorly thought-through shot in the dark with entirely unintended consequences. 
Sorry.

I've now made the turning off RTL after a note only happen in diglots (where it gets turned back on quite regularly in the current method of switching things). Are you feeling brave? If you wanted to test to see if that's now working, you could type git pull.
I'd test it with the way that you were doing the bisecting (i.e TEXINPUTS=... and not involving ptxprint), so that if our friendly python experts are in the middle of something that stops the GUI running properly, you can still report back.
 
Thanks for your input on this, it'd be good if this does fix it!

**Comment by mnjames** [comment]
Yes, I pulled your change and checked and things look good now.

--Malachi

**Comment by rmlockwood** [comment]
Good work guys!
