### ISSUE TITLE
Crossreference caller overlaps text

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#206]
Khmer letters come in various widths, and I've noticed that extra-wide characters used as cross-reference callers don't position correctly. Here's a couple examples:

![6 13](https://user-images.githubusercontent.com/915182/93444219-b62aeb80-f8fa-11ea-92e5-cd0b7a15cda3.png)

![13 41](https://user-images.githubusercontent.com/915182/93444250-b88d4580-f8fa-11ea-8b6c-a605b71c1380.png)

It's possible this is a font problem (does XeTeX look at a table or something to see how wide a consonant is?). But these characters don't misbehave in running text.

**Comment by davidg-sil** [comment]
There used to be an issue where cross-references and footnotes (at the foot of the page) looked uneven if they were set in non-paragraphs, because of varying widths, so they're currently set in a 'standardised' box. Obviously that box needs to be bigger for your font.... bother.
I'll try to think about a good solution to this...

**Comment by davidg-sil** [comment]
Two changes made.
 1: user control over how wide the 'padding' box is rather than old hard-coded value of 1ex, via e.g. `\NoteCallerWidth=1.3ex`, but beware that at the moment this adds space for footnote both in text (plan is to fix this!) and in the notes area.  
2: if the marker is too wide, then ignore padding and just let it take up as much space as it likes. Crazy example:

![image](https://user-images.githubusercontent.com/58848232/93850997-f8b44580-fcb7-11ea-941d-181d4ace674a.png)

**Comment by davidg-sil** [comment]
Hopefully all is correct now. ```\NoteCallerWidth=1em``` (as below) or whatever now only applies in the notes area. 
![image](https://user-images.githubusercontent.com/58848232/93856407-a9731280-fcc1-11ea-93bc-3df713cb3995.png)

For reference, here it is with ```\NoteCallerWidth=0pt```, 
![image](https://user-images.githubusercontent.com/58848232/93856793-3a49ee00-fcc2-11ea-9c97-5d5d09f56d86.png)

And the default:
![image](https://user-images.githubusercontent.com/58848232/93864895-38862780-fcce-11ea-9d32-ff675d82f86a.png)

**Comment by davidg-sil** [comment]
Just in case anyone is planning on checking this in 1.1.8, sorry, the fix missed that deadline.

**Comment by viverechristus** [comment]
I'll check this once I'm able to Print again. :)

**Comment by viverechristus** [comment]
Fixed.
