### ISSUE TITLE
Could use an ALL CAPS option on the Thumbs Tab

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#218]
Where we work, ALL CAPS is a common way of doing things. So while the normal abbreviations (Luk.) in references are okay, in something like these Thumb Tabs, it more common to see them as LUK (all caps, no period/full stop).
Unfortunately Paratext does not have a specification for such a need. So if we had an "All Caps" check box, and a "No period/full stop" checkbox, on the Tabs page, we'd be cooking on gas! 

(Thanks for the Vertical option, and the Bold option, and the Italic option!)

**Comment by mhosken** [comment]
The tab text comes from \toc3. So whatever you have in there is what will appear in the tab. I would say you could use a changes.txt change to do the uppercasing, but you can't. Are you in fact wanting the 3 letter book id rather than a localised shortened name?

There is a workaround in your ptxprint-mods.tex:

```
\TOCthreetabfalse
```
Then in your .sfm file use:
```
\zthumbtab tabtext
```
where tabtext is what will appear on the tab for that book. You need to set that early in the usfm file, before the first page of the book ships.

I don't think that \toc3 is recommended to have a final period. But given the paucity of the USFM3 specification in this area, it is not surprising everyone is "doing what is right in their own eyes".

**Comment by davidg-sil** [comment]
A small correction, if ```\zthumbtab``` is being used in all books, there's no need for the 
```
\TOCthreetabfalse
``` 

 ```\TOCthreetabfalse``` means that you'd rather have an empty tab than what's in ```\toc3```.

Another possibility... I seem to remember seeing that some fonts have an all-caps glyph variant. It might have been graphite only,  I can't remember. Styling for \Marker toc3 could use this (or \SmallCaps, if that's acceptable?) It wouldn't help with the trailing dots though.

**Comment by davidc86** [comment]
It looks like the simplest solution is to add: 
\zthumbtab GAL 
etc.
to each header section of each book (along with the \toc and \h SFMs), this is all before the first Title field. 

The advantage of this approach is you don't have to add two new widgets to the PTXprint Tabs dialog, and I can be sure I know exactly what they will look like. 

I'm assuming this will work without further tweaking on my part?

**Comment by mhosken** [comment]
Just to clarify, you want the book id as the zthumb and not an uppercases
toc3?

**Comment by davidc86** [comment]
Apparently the Team//Community at this point wants the xrefs to all use "1Kor. 3:16" etc. And this specification is found in the Scripture specifications for TOC3 so we have a field: 
\toc3 1Kor. 
(which apparently needs to include the .)

But, this is rather ugly actually on the TABs so I thought an [*] All Caps [*] No Punctuation option on the Tabs dialog would solve this for us. But if we can get what we want by adding the field: 
\zthumbtab 1KOR 
then I'm okay with that too.
