### ISSUE TITLE
\vp ... \vp* markers aren't being handled as expected

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#228]
DHJ raised this issue:
PRXprint doesn't handle the \vp …\vp* market correctly: when this market is present, the regular verse number should not be output, only what's between the vp markers. Guess that's a bug

**Comment by davidg-sil** [comment]
Yes. Urm. We knew this back before 1.0 came out, and I lost track of it. 

The quick and dirty cheat's approach is to have a line in PrintDraftChanges that says something like:
```
'\\v [^ ]* \\vp (.*)\\vp\*'  > '\\v \1'
```

But that might break other things (e.g. will people expect that the piclist will use the `\vp` content  or `\v` ?)

To handle this in XeTeX, the problem is that as soon as the code gets to the  space (and it does need that space) after the verse number, then it outputs the number, wrapped in whatever decoration is being used, along with the content of any after-verse hook code.
Therefore, by the time the code has understood the \vp, there is already undefined *stuff* in the output queue. If there were never  verse decorations, hanging verse numbers, etc. then it would be possible to remove those items. But that approach isn't going to work. We're therefore probably in the scary realm of reading ahead and finding out if the next *thing* is a ```\vp```
or not.

I think it can be done, but will need a lot of testing.

**Comment by mhosken** [comment]
What if you turn off printing verse numbers and just style \vp
appropriately?

GB,
Martin

**Comment by davidg-sil** [comment]
Hmmm That's scary. Read-ahead  seems to be working and I can't make it crash :-) 

For 
```
\v 1 \vp VP\vp*
```
The current behaviour is:

|Context                          | What's used |
|--------------------------------|-----------------|
|Displayed as verse text: |  VP |
|Used in header/footer:  | VP |
|piclists / adjlists :           |  1  |
| \reference (shorthand for current verse)     | 1   |

(will obviously need more testing, I'll try to update this if I find anything else)

**Comment by davidg-sil** [comment]
Silly demonstration:
![image](https://user-images.githubusercontent.com/58848232/94929538-e57e5280-04cd-11eb-9386-0ef0e8a31fe9.png)

(only \v1 and \v8 have \vp's defined)

**Comment by davidg-sil** [comment]
> What if you turn off printing verse numbers and just style \vp appropriately? GB, Martin

Didn't think of that. Too late!

**Comment by davidg-sil** [comment]
Brave / needy people can test this on (I expect short-lived) testing branch [vp](https://github.com/sillsdev/ptx2pdf/tree/vp)  (initial commit 71b4bd6d861ca2c91838ccec5b8d04a080ea133d)
