### ISSUE TITLE
TOC4?

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#240]
In Paratext there are 3 levels of "references": 

![image](https://user-images.githubusercontent.com/65363206/95591952-f96a0d00-0a15-11eb-8118-821d730e4ef6.png)

The TOC1 is the full convoluted name of the book, like "**Various Acts of the Apostles of Jesus**"
While TOC2 is a shortened version, like "**Acts of the Apostles**"
And TOC3 is the abbreviated version, **Act.**, which is used for in all the footnotes and cross-references, parallel passage references, and "Read the Bible in a Year" references.

What we need though is a TOC4 which is a clean, all-caps, version of TOC3, so TOC4 can be tailored to the Thumb Indexes, like **ACT** etc.

_Originally posted by @davidc86 in https://github.com/sillsdev/ptx2pdf/issue_comments/706198411_

**Comment by davidg-sil** [comment]
If this is just for thumbtabs, we do have \zthumbtab (sp?). Might this also be used in e.g. Book choice menu in a scripture app? That seems a similar role.

**Comment by davidc86** [comment]
That would be great. I'd like to have that option. I'm just not sure how to use the \zthumbtab field. I tried it by putting it in all my SFM books, but it blew up PTXprint process with errors. So I don't know where the field needs to go nor how it should look. 

I tried this: 

\id 3JN - Selaru
**\zthumbtab 3YOH** 
\h 3 Yohanes 
\toc3 3Yoh. 
\toc2 3 Yohanes 
\toc1 3 Yohanes 
\mt1 Yohanes 
\mt2 wasi atyahy a kla-telw ikeskye 
...
And this crashed PTXprint. I don't know if I need to add \zthumbtab in any of my STY files or what. It would be nice if the user did NOT need to add these "mystery" fields to their USFM custom.sty file, as this would be something only used by PTXprint. It would be better if PTXprint had a lookup table for all books and we just fill in the ThumbTab labels the project needs.

**Comment by davidg-sil** [comment]
What you tried *was* working, last time I tried it, so something accidentally broke it. Now fixed, I hope.

**Comment by davidg-sil** [comment]
Thanks to MH, \zthumbtab is now working* in diglots. I assume it works in monoglots too. In terms of position, I'd recommend it goes next to the toc entries, rather than above the \h. It might make a difference to something, I'm not sure.

*(NB. in diglots, eventually the code will probably default to putting the primary \toc3 / \zthumbtab text on odd numbered pages and if there is one, the secondary versions on even numbered pages. At the moment there is only one value that is getting set, and the code will use whichever set it last)

**Comment by davidc86** [comment]
Unfortunately \zthumbtab is not working in my project. (Well it wasn't before PTXprint stopped working again, so now I can't test it for sure.)

But when I converted my \zthumbtab XYZ fields back to \rem zthumbtab XYZ, I could get PTXprint to Print again! 

So, something is fishy.

And to me, that \zthumbtab info should be something stored inside a PTXprint config file rather than in Paratext SFM files, since it is a made-up fieldmarker, not something that should be seen in an SFM file. It is something only used by PTXprint. I'm wondering if putting those markers in the SFM files might not mess up some other parser, or app, that uses those same files for other applications and products.

**Comment by mhosken** [comment]
Marking as now a duplicate of #258.
