### ISSUE TITLE
Location of credits info

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#247]
I think you said the planned automatic colophon for Credits is not quite working yet. Would it be possible to choose either to place it at the front or the back of the printed book, please? Some of us (e.g., PNG) require the credits to be on the reverse of the Title Page. If I include an extra Title-page.pdf, the colophon/credits follow it, and the TOC comes next, then maybe I've got my automatic front matter ready to go.... Almost. 

More than just picture credits and copyright info goes on the Credits page of a publication. It would be great to be able to add # copies, pub. date, "Trial edition", etc. I'm guessing this is harder to achieve than in Bloom, but perhaps another Tab where we can fill in that information (with a multiline free-text field for misc. other data) would really be nice. Someday.

**Comment by mhosken** [comment]
If you want proper front matter, then we recommend you create a FRT file and do the job properly. The automatic colophon is a convenience, typically targetting single books, to help them get some kind of copyright in their document rather than nothing. But for larger book collections and those wanting to make more formal publications, FRT is the way to go. What to add to your FRT can be seen in a typical colophon (if you click refresh). Copy the text there into your FRT.

**Comment by mhosken** [comment]
Merging with #267 which may contain a potential bug
