### ISSUE TITLE
Pic List Detail Window Not Updated in some scenarios

### ISSUE THREAD

**Issue by mabacon** [sillsdev/ptx2pdf#248]
Sometimes when going picture to picture, certain fields (i.e. Caption Ref:) are not being updated.
I then checked the "Preserve Immediate..." box, clicked Generate, and the issue went away for that project.

**Comment by davidc86** [comment]
But the "Generate" button blows away any and all carefully configured "scaling" and layout decisions on these pictures. The whole point (to our teams) for a PTXprint kind of function, is to be able to carefully setup all the picture in all the published books, so that anyone can regenerate the PDFs (say, after minor revisions of the text), and get a new, clean, well formatted, usable PDF copy of the published books without ANY hassle. So the Generate button is a MAJOR danger for our use-cases. In fact once we get this working and the illustrations and references and scaling and layout all working right, I'd like a way to lock these settings (PicList) files so the end-user can't accidentally blow it all away. (I don't mean to lock the whole project. But the "Generate" button.) Because text revisions might require a slight tweak in a picture's size on page 245, to get it to sit nicely like it used to. That kind of tweaking would be fine. Just wanting to make it harder to blow away hours of work with one or two clicks.

**Comment by markpenny** [comment]
@mabacon There were a bunch of fixes in the last few days - could you check in 1.2.9.5 that this has now been fixed.

We have now made it so that (a) there is a WARNING when you hit Generate, and an encouragement to Cancel if unsure about what you're doing, and (c) Lock Config (when saving a Config on the Basic tab) stops people overwriting PicLists etc.

**Comment by mabacon** [comment]
Resolved. Thanks
