### ISSUE TITLE
v1.2.9 View/Edit button should be gray if the Pic List is showing (if you aren't going to support editing it)

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#250]
The **View/Edit button** on the View + Edit page should **GRAY** when the Pic List tab is selected, if you are not going to support hackers hacking the PicList files outside of PTXprint. 

![image](https://user-images.githubusercontent.com/65363206/96610687-e682f280-12c9-11eb-9c85-02dafdb9e6b8.png)

Currently my computer is set to launch Notepad++ if a PicList file is clicked. But PTXprint's View/Edit button does nothing. 

For first time users who haven't yet found all the nooks and crannies in this software, it might helpful for that button to just shift the PicList tab view to the **Edit Details** option:

![image](https://user-images.githubusercontent.com/65363206/96612144-6a89aa00-12cb-11eb-9bcf-9a6e3748c55a.png)

The UI on this page especially is a bit complicated for new users. There are now options along the left side, tabs along the top, and options along the bottom. So if that button simply flipped the "View List" option to the "Edit Details" option, that might be helpful(?). But I'm not sure. Do you actually want to cut off the backend from users? Making global changes in the backend PicList files is way faster and easier than in a detailed one-by-one UI. 

Anyway, until you all decide how you want that button to behave, it should GRAY when the Pic List tab is showing, because pushing a button and then nothing happens is unsettling.

**Comment by markpenny** [comment]
1.2.9.5 and later fixes the issue. But (to help users discover things better) we would like to place ALL picture-related settings on the Pictures tab. It would have 3 or 4 horizontal tabs, with the 1st one being the settings.
For the moment we have hidden the raw .piclist file (and disabled the View/Edit) primarily because SO MANY people tripped up when editing things manually - and this rendered PTXprint useless to them. So I am inclined to keep it that way, and advanced users (who already know how to edit .piclists with a text editor and Find and Replace tools) can still do so, but not from within PTXprint. The code is all there anyway, and we can easily turn it back on and unhide it. But for the moment, I'd like to keep it 'safer'.
Another idea is to have 3 levels: Basic mode, Intermediate, Advanced - and show/hide various controls based on these settings. But that's not a high priority today!

**Comment by davidc86** [comment]
I agree, I messed mine up too on a few occasions. So, if the piclist editor works as planned, then there is NO need for an edit button on that. Hackers can hack. But MTTs don't need to if PTXprint provides what they need.
I think this can be closed now.
