### ISSUE TITLE
v1.2.9.5 Changing the Font size on the Thumb Tab settings page doesn't make any difference

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#260]
I've been testing the Thumb Tabs, and Font size doesn't seem to change anything in the look of the tabs in the final PDF. Is it possible the TOC3 style is overriding this setting?

**Comment by mhosken** [comment]
I'm thinking that this is caused by our introduction of the style editor which outputs its information over the NestedStyles. We need to refactor to feed the fontsize change into the style editor rather than producing NestedStyles. I.e. NestedStyles needs to go away and the changes be visible in the style editor.

**Comment by markpenny** [comment]
This is working now (by clicking on Adjust Style... and setting the parameters there), but note that the preview doesn't update the parameters specified on the Styles tab. This cosmetic tweak will happen soon.
