### ISSUE TITLE
Is there a place to choose a marker for the start of verse location when marginal verse numbers are used?

### ISSUE THREAD

**Issue by oj-gamache** [sillsdev/ptx2pdf#274]
I believe Publishing Assistant has this capability but I haven't seen it in PTXPrint 1.3. Burmese usually prefers a mark like a hyphen to mark the junction between verses while using marginal verse numbers.

**Comment by oj-gamache** [comment]
I should clarify that for Burmese, the marker might be better described as marking a "mid-paragraph end of verse". It does not occur at the end of a paragraph or line of poetry. If a new verse, not the start of a new paragraph, starts at the right margin (see verse 6 in example below), the hyphen occurs at the end of the line above, (marking the end of v5).
5   texttexttexttexttextetxt.-
6texttexttexttexttextexttext
  texttexttexttexttextexttext
7texttexttext.-texttextextte
  texttext.
8   texttexttexttexttextetxt
  texttexttexttexttex......

**Comment by markpenny** [comment]
Thanks for the clarification. I can't promise any progress on this in the short term, but it is now on the growing list of enhancement requests.

**Comment by davidg-sil** [comment]
Based on very limited testing, I think that that something like this has a fair chance of working:
```
\catcode`\@=11
\addtoversehooks{\ifx\prev@rsemode\empty \penalty10000 \endash\penalty5 \fi}
\catcode`\@=12
```
Put it in the ptxprintmods.tex file (advanced tab)
(\endash turns into the character at U+2013 (EN DASH), feel free to replace it with `\emdash` or `-` or other (literal) character of your choice.)

The ```\ifx\prev@rsemode\empty ..... \fi ``` test is relying on a bit of internal logic that sets `\prev@rsemode` to what sort of paragraph this was before the verse started, or makes it the empty string if the verse is in the middle of a paragraph already, so that meets your 'if we're not at the start of the paragraph' issue.

The ```\penalty 5``` means breaking the line after this point is allowed but not ideal. Reduce the number if you want it more partial to break there, increase if it's breaking too easily. The ```\penalty 10000``` means **never** break there.

Please let us know if it works!
