### ISSUE TITLE
Chapter selection lost on project restart

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#283]
To reproduce: Select single book project;  apply chapter range; save.
config file now contains correct chapfrom/chapto values.

Select alternate configuration and return to original configuration, -or- quit and restart. 

Config file remains unchanged, but from chapter / to chapter UI now read start and end of book.

My guess is that the values are not being copied from the config into settings, or if they are, they then overridden when the book is read (much later in config file)

**Comment by markpenny** [comment]
MH - can we chat about this one. It is a bit tricky as we can't guess what the user actually wants, and if they change a book, it should reset to '1' and 'chapters in book'. I think it is currently getting lost because these from+to fcb_s gets set first, and then the book is changed - which overwrites what is in the .cfg file.

**Comment by markpenny** [comment]
Yay! This is now fixed and will be available in 1.5.7
