### ISSUE TITLE
table cells broken in diglot if contain \v

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#295]
For some text like:
```
\tr \tc1
\v 4 Shephatiah \tcr2 372
```
There is a bug introduced in supporting diglots. This is a bit texnical.
In the \st@rtcell we redefine mark to chain the call to mark out to the outer group. But this isn't done for \marks1. Given the diglot code redefines \m@rkverse to call both \mark and \marks1, then \marks1 is output in the cell's vbox and this blocks the unboxing that is done on the cell to capture the text in the box and the contents of the box is lost.

I have fixed it for monoglot by turning off the call to \marks1 if \ifdiglot is not true. But this will break in a diglot situation. The current \dos@vedmark is not up to the job when it comes to diglots. I'm not sure what the best solution is for diglot here.

**Comment by davidg-sil** [comment]
I think the current ```\dos@vedmark``` (having looked at it) isn't up to the job at all, as a 2nd verse overwrites the value of ```\s@vedmark```, so if the page starts with the table, only the last mark in the table will get saved.

I anticipate future ```\marks``` getting used, e.g. for keywords in the glossary, so recommend a generic solution rather than special-casing things.
  
I therfore suggest that a tokenlist be used, so that calls to ```\mark``` or ```\marks``` get stuffed in there and executed in ```\dos@vedmark```. What I'm not sure about is what multiple calls to ```\aftergroup``` will do. Will that result in  ```\dos@vedmark``` geting called repeatedly?
