### ISSUE TITLE
Fuzzy diglot fails 

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#30]
I specify the secondary text on the basic tab, then come to Fuzzy Diglot, check "Create secondary text pdf" and specify the secondary text here, and click Apply. I get a PDF with the specified text in the left hand column, the right hand column is blank.

Then I check "Create Pri+Sec Diglot PDF, specify the second project and click Apply, and I get this message:

![image](https://user-images.githubusercontent.com/16904461/75184976-4ca37f80-5713-11ea-97d2-54e180250b4f.png)

**Comment by markpenny** [comment]
Hi Steve, we plan to re-work this whole area in the next few weeks. Several people have been unable to make it work, because there are so many little steps to get right. I can make it work, but certainly not on my first attempt either! So we might change the UI, get all the info that we need and then do BOTH steps in sequence automatically so that there is less chance of getting it wrong.

**Comment by markpenny** [comment]
@sewhite I believe that this particular issue has been fixed now (it was a path issue with \ / being mixed); but we haven't yet got around to re-working the UI for Diglots - which obviously needs to be done soon.
