### ISSUE TITLE
v1.4.1 Trying to spec Absolute Pt Line Space in Style tab fails to do anything

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#304]
When trying to tweak the **Line Spacing** value in the Style tab using the **Absolute Spacing (in pts)** option, I get this:

![image](https://user-images.githubusercontent.com/65363206/99717189-14995500-2a77-11eb-8a57-95551bf8c4ee.png)

I'm assuming that if I DON'T check that box, the Line Spacing **value is a %** of the value on the Layout page. 
I assumed if I DO check that box, then the Line Spacing value is actual pt sizes. Like a 3 would be a very small line spacing.

Here is what I put in: 

![image](https://user-images.githubusercontent.com/65363206/99717871-fb44d880-2a77-11eb-90cd-197a056de336.png)

But it should be noted that I got this same error when the box was checked and the value specified was set to 1.0 also, so it's not clear what kind of units this should be using if that box is checked. (Or maybe I'm assuming correctly but there is a bug, so it isn't acting like it should.) 

If I check that box, does it affect just the Line Spacing box or does it also affect the Space Before and Space After boxes? Or all the boxes? Just wondering the scope of the option.

It would be good if we couldn't put in bogus values, but also, I would like to scrunch certain paragraphs with tighter line-spacing, and the % value won't go below 1.0, when I need it at 75% or so. Suggestions?

NOTE: the Help Tip says usually the **Line Spacing is calculated as a factor of the Font Size**... Helpful, but WHICH Font Size would that be: 1) the one just above it, 2) the field's parent's Font Size, or 3) the one one the Layout Page? 

It would be helpful if that tool tip could pop up on the Line Space label and box area too. 
(In fact I'm not seeing tool tips on any of the Paragraph Settings options.)

Also, it would be nice if we could specify a STYLE value (e.g. line spacing) once, for the topmost Parent, and it overwrites all the unspecified values in the children. It'd save a LOT of time. Or maybe it is supposed to work this way, but I'm not seeing it?

**Comment by davidg-sil** [comment]
FYI, (and as far as I remember) as long as no one specifies the per-marker line spacing, then everything except headings and footnotes uses the line spacing calculated from / specified for  ```\p```

**Comment by davidc86** [comment]
The only tool tip that shows up on this page is when I hover over "Absolute Spacing":

![image](https://user-images.githubusercontent.com/65363206/100299181-0361b400-2f61-11eb-8fb4-d141ae117981.png)

First off that is pretty helpful tip, except I'm not sure which "Font Size" this is referring to. I assume this refers to **this paragraph's** Font Size, correct? Cuz you all told me about the "Font Size" on the Layout tab, which seems to be the Main Driver of these "factors". So maybe a clarification here might help?

Also it would be helpful to add similar tips to each of the other labels, like "Left Margin", "Line Spacing", "Space Before" "Space After" "First Line Indent" and "Right Margin". They could all say the same thing, like a short version of what you have in the "Absolute Spacing" tip. 

Also, if I'm understanding how these values "factor" with other values (found elsewhere), then maybe "Left Margin" and "Right Margin" should be "Left Indent" and "Right Indent" (as these refer to how much the whole left side or right side **of the current paragraph** is "_**indented**_" from the Left Margin and Right Margin of the layout, correct?

Anyway just some thoughts on this.

**Comment by markpenny** [comment]
All good feedback - I'll do some editing/adding of tooltips and labels.

**Comment by mhosken** [comment]
Fixed not outputting absolute line spacing correctly in the stylesheet.

**Comment by davidc86** [comment]
We have some progress...
Checking Absolute style does not crash. And it converts the line spacing value into pt size! Nice.
But it also doesn't appear to do anything, no matter what pt size I put in.

![image](https://user-images.githubusercontent.com/65363206/100523238-f7ead480-317c-11eb-830a-eda4400490ae.png)

The intro lines are set to 10pt while the normal paragraphs (on the right) are set to 15pt on the layout page and set to 1.0 on the Style page (so I'm figuring the \p = 15pt line spacing). But as you can see the left page lines line up exactly with the right page lines.

Is there another setting I'm missing?

**Comment by mhosken** [comment]
A couple of bugs in the TeX code:
- There is no call to set the baseline for non heading styles
- The definition of LineSpacing is #1\FontSizeUnit but to turn that into an actual size of use we need to multiply by 12.

**Comment by davidg-sil** [comment]
@mhosken,  There's no bug, at least relative to the documentation. Please see Documentation/ptx2pdf.md

LineSpacing is a scalable measure, measured in FontSizeUnits
BaseLine is a fixed measure  and can include glue.

pxtprint can of course perform other calcs if desired(!)

**Comment by mhosken** [comment]
OK so the documentation (that is following the code) says that the units are fontsize units. I actually think it would be better if we multiplied it by the LineSpacingFactor as well so that it becomes linespace units. This means that 12 is always the base line spacing rather than just the base font size. If a \LineSpacing is 12 then it will be the same as the default base line spacing for the project (which defaults to 14/12 of the default fontsize).

To add to the confusion, if neither a \LineSpacing or \BaseLine is set for a marker and there is a \FontSize, then this is used but scaled in the same way as the base line spacing is a proportion (usually > 1) of the base font size. In effect, we are following that pattern by defining \LineSpacing in the way I propose.

My only difficulty is in how to describe this to users!

**Comment by mhosken** [comment]
It's more subtle than that, but we still hold that 12 line spacing units gives the base line spacing. But underneath this is scaled such that in ptxprint.sty, 14 units gives the base line spacing. Why is this I hear you cry? Well...

In calculating the LineSpaceFactor, ptxprint takes into account that the fallback linespacing for a paragraph, if none is specified, is  14/12 times the fontsize of the paragraph. This means that LineSpaceFactor is actually the base line spacing / 14. So to get the base line spacing, one needs 14 line space units. This is not ideal! But we may never get to change it now.

**Comment by mhosken** [comment]
Fixed? Na. The problem is that we haven't done the same trick for the SpaceBelow and SpaceAbove. So what options are there for us? Why lots, of course:
1. Set Baseline in \p rather than messing with LineSpaceFactor. But that messes up things like \q and pretty much all other paragraph styles.
2. Do the same trick of scaling the values into the .sty file for SpaceBelow and SpaceAbove. Given that the closest thing we have to a [https://github.com/ubsicap/usfm/tree/master/sty](style reference) says that such values are in points, we are free to reinterpret how we like.
3. The unspecified BaseLine is `14/12 * 12 * LSF * FSU`. Let's make FSU=1 for this discussion. As per the previous message, we would really like to have LSF = x/12 rather than x/14, thus we define a LFF (LineFudgeFactor) to multiply in here so now `x = 14/12*12 * LFF * LSF = 14 * LFF * x/12 =>`14/12 * LFF * x = x => LFF = 12/14` by default. Of course if one wants to work with a different approach one can (e.g. setting LSF to 1 and using BaseLines everywhere.
4. Use LFF everywhere else, so `\BaseLine = \LineSpacing * LFF * LSF * FSU`. With `LSF=x/14` then `LFF=12/14`.
5. Use VerticalSpaceFactor as LFF in either 3 or 4.

Of all these, I like 3 the best. My reasons are:
- The maths is simpler since LFF only gets used in one place in the code rather than everywhere a \LineSpacing, SpaceAbove or SpaceBelow may get resolved.
- It concentrates the value in one place and one concept.
- The value can be changed if someone wants to do a different kind of scaling.
- It allows a project to change its default fontsize to linespacing ratio apart from the LineSpacing ratio.
- LineSpacing and SpaceAbove, etc. use the same notional units (unless the VSF is set for the SpaceAbove and SpaceBelow, but that is about such space compression/expansion
I'm not a fan of 5 because VSF is about allowing people to change the spacing ratio apart from the linespacing. If they want to play with both then mess with LSF and LFF instead.

**Comment by mhosken** [comment]
What about:
6. Drop the 14/12 multiplication in the BaseLine calculation and set the default LSF to 14/12. No LFF. There are a few places in the code where implicit half lines are referenced and we simply switch them from 7 & 14 to 6 & 12 respectively.

**Comment by mhosken** [comment]
We have a solution. Introducing `\LineSpaceBase` which is either 12 or 14. This is used to scaled fontsize * LineSpaceFactor / 12. Traditionally it is 14 but it is much easier to think of SpaceBelow and SpaceAbove in terms of 1/12 of a base line spacing rather than 1/14. The style field `\LineSpacing` is defined as a multiple of the base line spacing (so 1.0 is the base line spacing (\p fontsize * FontSizeUnits * LineSpaceFactor * LineSpaceBase / 12)). PTXprint has a legacy switch to allow people to keep the SpaceAbove and SpaceBelow interpretation of 1/14 of a line instead of the easier to understand 1/12.
