### ISSUE TITLE
v1.3.8 Widows and Orphans

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#307]
I'm wondering if there is any way to get the process to NOT worry about paragraph widows and orphans? 
Here is a two page spread showing a clear example of where there is room for at least one more line on the bottom of the left page, but instead it was left blank. There does not seem to be anything in the next few lines (like a footnote) that would cause them to all bump to the next page, except maybe the "rule" that says don't leave a paragraph with only 1 or 2 lines on the top or bottom of the page. But personally, I'd prefer that, especially if the lines are complete lines.

![image](https://user-images.githubusercontent.com/65363206/99751830-09fbb180-2ab1-11eb-9e33-37c434f47ade.png)

I see an option to prevent Orphan Words-- a nice feature--but that isn't what I'm referring to. 
In Word there is an option to prevent Widow and Orphan paragraphs, i.e. either the first line (or 2) from a paragraph at the bottom of a page; or the last line (or 2) of a paragraph from ending up at the top of the page. I find it nice to turn this feature off. Doing so helps keep all pages looking more uniform. 
(I also normally try to use fixed space as well to aligned the printed text front/back through the paper.)

**Comment by markpenny** [comment]
@davidc86 This is an interesting one - as typesetting best practices would strongly discourage that. But I get your point that it could be a good idea to make it an option. But then are we guilty of allowing/encouraging people to produce sloppy PDFs? And what would that look like in the context of a 2-col (auto-balanced) publication? Perhaps it would only be allowed in single-col publications, and have a strong warning to go along with the option. @mhosken What are your thoughts on this? Is this the kind of thing that we can attach a penalty to, so that it works hard to make it fill the last line, but if it really can't do it well then it breaks and allows an orphan/widow?

**Comment by mhosken** [comment]
I think you may find that the space above the footnote line is enough to not allow two lines to transition across.

We already have 'optimize layout for poetry books' (not sure why it's disabled and on) which does this for poetry. So we could extend it to everywhere. But I agree that I would much prefer not to provide this as a lazy way to 'fix' page breaks. For example reducing the space separating notes and text a smidgen would probably fix this one. I also acknowledge that it shouldn't be up to me to enforce my typesetting prejudices on others. Perhaps it's the global nature of such a switch that scares me.
One could add a snippet like:
```
\setcvhook{MRK7.16}{\clubpenalty=50\widowpenalty=50}
\setcvhook{MRK7.17}{\clubpenalty=10000\widowpenalty=10000}
```
to your `ptxprint-mods.tex`. If that doesn't do anything, try dropping the 50 down to 0.

**Comment by markpenny** [comment]
I had forgotten about the Optimize Layout for Poetry Books option. But, yes - it allows widows/orphans and would work for any books listed above (where it has PSA at the moment). I've added a sentence to the tooltip now.

![image](https://user-images.githubusercontent.com/12962708/99929506-5e08dd80-2db2-11eb-982d-3970422caee5.png)

@mhosken The reason that it is "disabled but on" by default is so that when the user selects the option above, it already is on (but can be turned off if they prefer NOT to allow widows/orphans).
