### ISSUE TITLE
v1.4 NestedStyles should go

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#315]
Sorry I may have mentioned a related issue to this in (#299), but this is an update, to say that saving a PTXprint configuration to a New Config Name appears to correctly copy everything except the **NestedStyles.sty** file. (Actually, I haven't tested the issue in #229 whereby there may have been Style tweaks in memory, that had yet to be written to the file. But here I opened PTXprint and immediately changed the config name and clicked Save, and all the needed files were copied, except NestedStyles.sty.)

I don't actually know what the NestedStyles.sty file is for, and maybe it is generated each time PRINT is run, but just an FYI that it doesn't copy over.

Everything else copies now and even keeps the Notes and updates the Folder and Piclist file name perfectly too. So all is cool other than the NestedStyles.sty file!

**Comment by markpenny** [comment]
@davidc86 The reason this file isn't copied is that it is generated at run time (depending on what options have been set when you hit print) - so it is a dynamic file, changing constantly. There's no need to copy it over to the new config, and perhaps we should just treat it like other temporary files and delete it at the end of a job rather than leaving it around and including it with the settings that included in the Send/Recv operation.

**Comment by davidc86** [comment]
Good info. I agree, if it is a transient file and regenerated every time, then it probably should be deleted at the end of the job (or save it with the output files -- which are local to the user's machine and don't get sent with Send/Receive).

**Comment by mhosken** [comment]
NestedStyles is a temporary file so shoudl get deleted after a job runs (if you have removing temp files turned on). We are planning to remove NestedStyles in due course. So this will be a temporary issue.

**Comment by mhosken** [comment]
Hijacking this issue to list what needs to happen to do away with NestedStyles:
1. c_doublecolumns either doubles or halves the indent units (need to update tooltip to explain that indent factor is actually indent size in inches)
2. Throw out all our poetry indents since once you bring in indent size the ones in usfm.sty make sense. But if we don't like those values we can change them in ptx2pdf.sty
3. s_fnfontsize footnote size sets and is updated from the f (and one way to x) fontsize, taking into account the overall font size (since stylesheet is a font factor and the control is in pts). Although we have been treating it as a font factor. So which way do we want to go on that?
4. s_fnlinespacing footnote spacing updates f,x and is updated by f to an absolute line spacing. Changing it either updates f,x by absolute or relative amount depending on the setting. Tedious.
5. Toggling c_blendfnxr sets or clears NoteBlendInto f for x in the style editor (note there is no direct control of that in the style editor)
6. Toggling direction fcb_textDirection should swap justification for all justification values not center (so left and right aligned)
7. Do we need to keep fancy borders verse font size? Or can they set the styles up themselves? Likewise for \s
8. Move colophon styleinfo to ptx2pdf.sty
9. Do away with NestedStyle.sty
