### ISSUE TITLE
v1.4 The Picture CheckList tool appears to work for the 1st selected picture only

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#317]
The Picture CheckList tool appears to work for one picture only. Moving the selection to the next picture entry does not increment what is shown in the lower half of the tab.  

![image](https://user-images.githubusercontent.com/65363206/100305317-df0cd400-2f6e-11eb-9051-26ed06a356e6.png)

In this example, I selected the top entry (John the Baptist) and then I answered the questions. 
Then I clicked on the next picture entry, but the bottom half didn't change. It still shows the answers I gave for the 1st illustration, and the preview picture is still the first picture, not the one that is selected.

BTW, it will be VERY tedious to go through all of these questions one illustration at a time. 
Also, the last Yes/No is not like the others...is this going to trip people up?

It might be helpful if there was a way to mark "All Pictures in this book are like this:...." And then we go back and tweak the few that might be odd, like "This one  MUST be mirrored" (currently not an option, but maybe should be) or "This one is _alien but acceptable_" etc. 

Also, I don't see any consultant taking the time to go through this. So I'll be initializing their initials here, which is somewhat questionable on principle, but I suppose if they approve the publication. It's just that most international consultants don't pay much attention to the illustrations. SO the approval falls to me and the team testing it with the community. Anyway, these are niggly things that can be worked out if need be later.

**Comment by davidc86** [comment]
SO, like is there a future version where unapproved illustrations won't get exported to the PDF file?

**Comment by markpenny** [comment]
The background to this tool is that the EthnoArts people are fed up of seeing publications put out there where there has been insufficient testing of important components (like illustrations). I'd be the 1st to agree that this functionality (to keep track of what is/isn't tested/approved etc.) doesn't really belong to PTXprint, BUT then where *does* it belong? Ideally in Paratext, and perhaps one day it will get adopted. So until then we have a tool that is entirely OPTIONAL for a team to use, but is hopefully helpful - if for nothing else, then just to make people aware of the kinds of things they should be thinking about. The "Is this approved?" and "Notes" extension was added on later based on the request of a user. So people will love the (drudgery!?) of going through each one carefully answering each of the questions, and others will absolutely abhor that extra work. But, as I said, it *is* optional. And hopefully helpful to those who invest the time to use it.

I like the suggestion to have some preset defaults for the book, but I'm tempted to think that people will just use that as a shortcut to pretend that everything has been checked, when in reality it hasn't. By leaving them all as Unknown it is easy to use the Filter feature to find the ones that haven't really been checked yet.

Yes, MH just fixed the "not selecting properly, and not updating" bug that was there in 1.4

I'm aware of the strange wording of the final yes/no question, and we tweaked it a little to be more clear on what we are asking.
![image](https://user-images.githubusercontent.com/12962708/100306520-7b36e980-3008-11eb-9021-8b6d81803e56.png)
If you can think of a nice way to switch the question around (so that the preferred/expected answer is a "yes" instead of a "no") I'm all ears. If not, then we're left with a few interesting ways to solve it:
a) Swap the position of the radio buttons "no" on the left and then "yes" on the right.*
b) Make the label of the correct answers **bold**, so it would show:   O Yes    O **No**    O Unchecked 

Perhaps all of them would be better off shown as:  O Yes    O Unchecked/Unknown    O No    

The Reversing an image really needs to be updated so that the "Mirror" or "Reverse" terminology is the same across all the tabs. As far as options go, (instead of yes/No/Unknown) how about:   O Must NOT be    O Can be    O MUST be   (and you would hope that we would eventually connect this response to the Details page so that it limits the available options on the Mirror drop-down as follows:
  Must NOT be  - set Mirror option to "Never" and disables control (so user can't change it accidentally to something else)
  Can be - leaves all options available for the user to choose
  MUST be - set Mirror option to "Both" and disable...

> SO, like is there a future version where unapproved illustrations won't get exported to the PDF file?

That would be a nice option on the Picture Settings tab. But I certainly wouldn't make it automatic. After all, there are too many busy/lazy consultants around :-) to wait for them to check the right boxes. We don't want bottle necks. That is why PTXprint exists - to clear them.

**Comment by markpenny** [comment]
@davidc86 Comments on this layout:
![image](https://user-images.githubusercontent.com/12962708/100309414-af61d880-300f-11eb-869f-d670cd655c46.png)

**Comment by mhosken** [comment]
Yes the whole checklist treeview selection was a mess. Fixed now.

**Comment by davidc86** [comment]
The original issue here has been addressed in v1.4.1 (it now tracks the selected illustration).
As to the changes to the question/layout/options on this page, that all might should move to another issue for enhancements?
