### ISSUE TITLE
PrintDraft-mods.sty appears to make no difference in output

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#32]
I'm using **PTXprint-0.3.0.exe**. I'm trying to apply some changes to indentation of q1 and q2 via PrintDraft-mods.sty. As you can see below, I have selected the proper tick mark in the Advanced tab:

![image](https://user-images.githubusercontent.com/915182/75646665-eff91500-5c7c-11ea-92b8-8163a11f9ed8.png)

I use the following code in PrintDraft-mods.sty to adjust the ouput of q1 (and similarly for q2):

```
\Marker q1
\LeftMargin 0
\FirstLineIndent -0.15
\Justification Left
```
Our primary stylesheet usfm.sty (which is loaded first in the .tex file) has the following definition for q1:

```
\Marker q1
\Name q1 - Poetry - Indent Level 1
\Description Poetry text, level 1 indent (if multiple levels) (basic)
\OccursUnder c
\Rank 4
\TextType VerseText
\TextProperties paragraph publishable vernacular poetic level_1
\StyleType Paragraph
\FontSize 12
\LeftMargin 1.25
\FirstLineIndent -1  # 1/4 inch indent, 1 inch wrap
```

No matter what values I use in PrintDraft-mods.sty, there is no difference in the output PDF. In fact, I don't seem to be able to adjust any styles at all using custom.sty or PrintDraft-mods.sty. Nothing changes in the output. Only changes in usfm.sty result in a changed output, but we can't change the stylesheet for the sake of PDF outputs.

Any suggestions?

**Comment by markpenny** [comment]
Thanks for this feedback. We've done a lot of work since 0.3.0 and I trust that this bug has now been fixed. Please try to download and install the latest Beta test version 0.4.0 from here: [tiny.cc/ptxprint](http://tiny.cc/ptxprint)

**Comment by viverechristus** [comment]
Thanks for the latest beta. I'm afraid this problem remains unresolved. Adjustments to markers that I make in PrintDraft-mods.sty are still not showing up in the output. (Note, however, that in Paratext, the Output to PDF tool does register the things I put into this file.) I'm happy to provide you with any files or details you need to troubleshoot.

**Comment by markpenny** [comment]
OK, I'll take a look at this next week and get back to you. Can you confirm that you are using the Paratext project's PrintDraft folder (and that is indeed where the PrintDraft-mods.sty file is located).

**Comment by mhosken** [comment]
Do bear in mind that we changed the default file to ptxprint-mods.tex since
the normal PrintDraft-mods.tex used by PT has lots of stuff in it that
ptxprint generates and so the two are best handles with two files. You can
always \include ptxprint-mods.tex in your PrintDraft-mods.tex if you like.

GB,
Martin

**Comment by viverechristus** [comment]
Thanks. However, the file that doesn't seem to make a difference is
PrintDraft-mods.sty rather than PrintDraft-mods.tex. the advanced tab shows
that this file is being called.

**Comment by markpenny** [comment]
I have tried to replicate the problem that you are facing, but am unable to do so at present (0.4.2). Any changes I make in my .sty file *are* being reflected in the PDF output. 

So... could you please confirm that you have checked the option to Apply the PrintDraft-mods.sty file; and then when you click on Edit, it should show the .sty file itself.
![image](https://user-images.githubusercontent.com/12962708/76959988-9e20e200-6940-11ea-9051-90a25e6ac0c9.png)
You should be able to edit the Style file in the resulting viewer. Make sure that you SAVE any changes and then re-run.
![image](https://user-images.githubusercontent.com/12962708/76960046-b55fcf80-6940-11ea-908a-597a350d3366.png)

You can also check what is being called by examining the resulting .tex file [but you must ensure that the "Preserve Intermediate Files and Logs" option is checked first - otherwise there will be no .tex file to be seen].
![image](https://user-images.githubusercontent.com/12962708/76960295-2acba000-6941-11ea-8b66-da3720d0f11a.png)

**Comment by viverechristus** [comment]
I am using 0.4.2, as well. Still not working. See settings:

![image](https://user-images.githubusercontent.com/915182/77221081-e1659580-6b78-11ea-8ca5-3160e0f96b0c.png)

Here's the (saved!) PrintDraft-mods.sty, with the relevant portion highlighted.

![image](https://user-images.githubusercontent.com/915182/77221093-0d811680-6b79-11ea-9b07-c806831b2d4c.png)

Here's the tex file to show that the stylesheet is being called:

![image](https://user-images.githubusercontent.com/915182/77221108-33a6b680-6b79-11ea-8476-91062d64b19f.png)

Here's the output, showing that poetic lines (q1 and q2) are still being indented, even though indenting is turned off in PrintDraft-mods.sty:

![image](https://user-images.githubusercontent.com/915182/77221128-6e105380-6b79-11ea-8245-eb996ebeaf44.png)

Here's an output of the same chapters from Paratext 9.0 "export draft PDF", which uses the same "PrintDraft-mods.sty." Notice that here there is NO indenting, consistent with the modified stylesheet.

![image](https://user-images.githubusercontent.com/915182/77221134-897b5e80-6b79-11ea-906a-6ac6d8b1b2d1.png)

I would be happy to share any files with you that you like.

**Comment by viverechristus** [comment]
I really appreciate  your work to track down the problem. I've just posted
a reply at GitHub.

Josh
Joshua & RuthAmy Jensen
Ratanakiri, Cambodia
088-957-1791 (in Cambodia)
817-522-4383 (US number, also rings in Cambodia)

**Comment by viverechristus** [comment]
I just downloaded 0.4.3 and tested, and PrintDraft-mods.sty continues to be ignored, though all the settings are apparently correct. Once again, "Export Draft PDF..." in PT 9 honors all style modifications in PrintDraft-mods.sty, but PTXprint doesn't.

I love PTXprint and would love to have this working right. If there's anything I can do to help troubleshoot, please let me know. I can send files, or I can test files you send to me. Please advise.

**Comment by viverechristus** [comment]
Problem (partially) solved. I just discovered that be deselecting "Apply Customized Styles (in custom.sty)", the PrintDraft-mods.sty modifications are honored:

![image](https://user-images.githubusercontent.com/915182/78093485-83e50a80-73fc-11ea-8757-b9101dca0b48.png)

This is a bit of a mystery, because when both stylesheets are included, PrintDraft-mods.sty is called after custom.sty:

![image](https://user-images.githubusercontent.com/915182/78093602-c1499800-73fc-11ea-97c8-816eefd454a3.png)

So from my perspective, this issue is now resolved, because as far as I know, I don't need anything in custom.sty. However, it seems that you might want to investigate why this interaction is going on.

**Comment by markpenny** [comment]
@viverechristus That is really helpful feedback! Thank you. We'll see what we can do to (i) be more predictable, and (ii) ensure users can understand the order in which the various stylesheets are applied. I can also see issue #36 about needing to reload for changes to take effect.

**Comment by markpenny** [comment]
@viverechristus Good news - we have found what is likely triggering this strange behaviour. I was able to replicate the issue on one of my projects, and it was exactly as you reported: if custom.sty was enabled, it was totally ignoring EVERYTHING in the PrintDraft-mods.sty file. With a little bit of digging, we finally traced it to an unwanted hyphen '-' at the end of a \Bold line. As soon as the offending hyphen was removed, it all functioned as expected.

So the short term fix for you is to carefully examine what is in the custom.sty file to make sure there are no "syntax" errors or typos - and hopefully you can make it work again.

The long term solution is for @davidg-sil to figure out how to make the TeX macros more robust, and to "step over" or ignore, or better still, flag such syntax issues so that the rest of the stylesheet(s) can get processed properly.

**Comment by viverechristus** [comment]
Thanks, Mark!
