### ISSUE TITLE
Nothing Happens

### ISSUE THREAD

**Issue by mattymatta** [sillsdev/ptx2pdf#34]
I tried using this on Windows 10 (64-bit). I used the stock settings and tried to print Ruth then Genesis in one language, then Acts in another language. Nothing worked. The 'Print Preview' button does nothing. 

Hopefully this is a screenshot of the program along with the other programs I was running at the time:
![image](https://user-images.githubusercontent.com/62287025/76848811-5465c800-686a-11ea-97b7-2d2e88a16a47.png)

**Comment by klassenjm** [comment]
I have a similar experience (currently working with 0.4.0).

For me, it takes a very long time for the PTXprint application to display the UI, initially (fc-list.exe is running and using a lot of CPU). 40-60 seconds probably.

I wondered if it might make a difference if I ran PTXprint as Administrator (maybe there are issues with gathering font info?). It does not seem to make a difference.

But also, it takes some time (much less than startup) for a PDF to get generated.

If delays are somewhat unavoidable, for some reason, it might be good to show some kind of progress bar ("please wait" message)?

Jeff

**Comment by markpenny** [comment]
Thanks Matt, and Jeff for this helpful feedback. Yes, I'm aware that we need some sort of "indicator of progress" - at least when it is producing a PDF, and preferably when it is loading as well.

You are right that running fc-list takes a lot of time - especially when there are a number of fonts loaded on the system. MH had an idea of backgrounding that task so that it doesn't slow everything down on startup.

Usually the PDF production is quick, but there are certain conditions (automatic ToC generation, \nb chapter numbers) when that process is repeated a number of times (upto 5 times) to refine the output. Still, it would be good to show the user that *something* is actually happening!

**Comment by markpenny** [comment]
We've done a couple of things that might help (even though there is no proper progress bar yet):

a) There's a kind of splash-screen that sits there very briefly for most people, but longer for those with hundreds of fonts installed :-)   - hope you get the hint...
![image](https://user-images.githubusercontent.com/12962708/80202376-23379f00-8643-11ea-9b09-4fa3318d9989.png)

b) When you click on Print, the button turns RED while it is working away in the background, and goes back to it's uncoloured state when the job is finished:
![image](https://user-images.githubusercontent.com/12962708/80202315-0dc27500-8643-11ea-86ad-98b1a3b32a0b.png)

These changes will be available in 0.5.0 Beta which will be available within a few days.
