### ISSUE TITLE
Generate PicList dialog doesn't cancel properly

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#340]
From JN: I closed the Generate Piclist dialog by clicking the X in the corner of the dialog. It would not close by clicking Cancel. I had to close and restart the program to get the generate piclist dialog box to open again. Also, if I click Cancel on that dialog, and it doesn’t disappear, and then I click OK, it just crashes and I have to restart the program again.

**Comment by mhosken** [comment]
The problem here is that an exception has occurred but the exception is not being captured to display in the main dialog. I'm not sure what to do to capture those. Perhaps we can monitor for such exceptions on the command line and looking at the top of the traceback to see why the exception is not captured.
