### ISSUE TITLE
Poor defaults - some go against GPS requirements like fontsize 12

### ISSUE THREAD

**Issue by jstnlth** [sillsdev/ptx2pdf#341]
-GPS maximum fontsize is 11. That should be the default instead of 12.
-default of 2 columns on an A5 page with fontsize 12?  That is super tiny. The default should be 1 column given the other settings. I get dreadful justifying with two columns. Sometimes only two words fit, with a huge space gap.
-terrible indents on poetry.
-huge paragraph indents in single column mode. The indent size should probably to equal to two-column size.

I'm sure there are a lot more. Those are just the ones that hit me on the head in the 10 seconds that I looked at my initial run.

[ptxprint-SILdefaults-GENDidinga.pdf](https://github.com/sillsdev/ptx2pdf/files/5815359/ptxprint-SILdefaults-GENDidinga.pdf)
[ptxprint-poordefaults-GENDidinga.pdf](https://github.com/sillsdev/ptx2pdf/files/5815391/ptxprint-poordefaults-GENDidinga.pdf)

**Comment by markpenny** [comment]
Hi @jstnlth  - thanks for your feedback. I'm pleased that you were able to get as far as you did in 10 seconds ;-)

I understand where you're coming from, and agree that we should try to conform to GPS requirements - but in my mind, only when appropriate! However there are a couple of other significant issues to consider:

a) the GPS requirements are rather biased toward roman-scripts and from my typesetting experience in Asia for 15+ years, I have found that 11pt is rarely large enough for many of the scripts we work with. So for a change, I've chosen a default setting that might favour those scripts (see default sample below).

b) because of the way that Paratext stylesheets work, EVERYTHING relating to font sizes is relative to a BASE font size of 12. So if you set the base to 12 and then go and change the font size of specific markers in the Styles area, you will get what you ask for (ie. 11 will give you 11pt). But if you change the base to 11pt, then setting the size in the Styles area won't give you exactly what you asked for, but rather 11/12ths of what you asked for (i.e. 11 = 10.08pt) - and that gets really confusing for people really quickly. We try to explain this in the tooltip:

![image](https://user-images.githubusercontent.com/12962708/104700628-55f96880-5779-11eb-8dfe-15544205efd0.png)

I'm curious as to why you are seeing **huge ugly indentation** of poetry lines. Is it possible that you've got custom.sty checked (on the Advanced tab) and that there are some strange values set in there? Try turning that off. Yes, I've changed the default so that it no longer is ON by default. The other thing to check is the Base Paragraph Indent (on the Layout tab) - which should be 1.0 or perhaps even smaller.

There are other default settings (for example, double column layout, the vertical and horizontal rules, and Coloured text, etc.) which are turned on to highlight that these things are possible [and easy enough to turn off] rather than being prescriptive as "best practices".

![2021-01-15 21_17_46-Window](https://user-images.githubusercontent.com/12962708/104702229-90173a00-577a-11eb-9fda-aac4406db8d5.png)

**Comment by mhosken** [comment]
Regarding your 'bad line breaks' issue, I see that you have pretty long words and would benefit from some hyphenation. I am researching how to enable support for large hyphenation lists and should have something available soon, but if you could send me your hyphenation list, I would be happy to test it out and even make sure the project works for you if you also send a project archive (see Advanced tab in ptxprint).

**Comment by jstnlth** [comment]
We don't do hyphenation. That's why we
      never do 2 columns.  But even so, the columns seem too thin even
      if short words are used - at least with this fontsize/page-size
      defaults.
    
    Justin
    
    
    On 1/15/21 1:27 PM, mhosken wrote:
    
    
      
      Regarding your 'bad line breaks' issue, I see that you have
        pretty long words and would benefit from some hyphenation. I am
        researching how to enable support for large hyphenation lists
        and should have something available soon, but if you could send
        me your hyphenation list, I would be happy to test it out and
        even make sure the project works for you if you also send a
        project archive (see Advanced tab in ptxprint).
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sillsdev/ptx2pdf/issues/341#issuecomment-760809293",
"url": "https://github.com/sillsdev/ptx2pdf/issues/341#issuecomment-760809293",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jstnlth** [comment]
> There are other default settings (for example, double
        column layout, the vertical and horizontal rules, and Coloured
        text, etc.) which are turned on to highlight that these things
        are possible [and easy enough to turn off] rather than being
        prescriptive as "best practices".
      Well, the program is advertised to "just work when you press
        print", so it ought to chose the most sane defaults for its
        target majority audience instead of "highlighting possibilities"
        IMHO.
      > you've got custom.sty checked
      Yes - that was the default.  I didn't have much time to
        customize in 10 seconds... :-)
      However, the results are still horrendous for poetry when I
        disable the custom.sty.  (I'm testing with Didinga - which is a
        completed NT that has already finished typesetting etc - so the
        SFM markers should be legitimate.)
      
      
      
      
      On 1/15/21 11:45 AM, Mark Penny wrote:
    
    
      
      Hi @jstnlth
        - thanks for your feedback. I'm pleased that you were able to
        get as far as you did in 10 seconds ;-)
      I understand where you're coming from, and agree that we should
        try to conform to GPS requirements - but in my mind, only when
        appropriate! However there are a couple of other significant
        issues to consider:
      a) the GPS requirements are rather biased toward roman-scripts
        and from my typesetting experience in Asia for 15+ years, I have
        found that 11pt is rarely large enough for many of the scripts
        we work with. So for a change, I've chosen a default setting
        that might favour those scripts (see default sample below).
      b) because of the way that Paratext stylesheets work,
        EVERYTHING relating to font sizes is relative to a BASE font
        size of 12. So if you set the base to 12 and then go and change
        the font size of specific markers in the Styles area, you will
        get what you ask for (ie. 11 will give you 11pt). But if you
        change the base to 11pt, then setting the size in the Styles
        area won't give you exactly what you asked for, but rather
        11/12ths of what you asked for (i.e. 11 = 10.08pt) - and that
        gets really confusing for people really quickly. We try to
        explain this in the tooltip:
      
      I'm curious as to why you are seeing huge ugly
          indentation of poetry lines. Is it possible that
        you've got custom.sty checked (on the Advanced tab) and that
        there are some strange values set in there? Try turning that
        off. Yes, I've changed the default so that it no longer is ON by
        default. The other thing to check is the Base Paragraph Indent
        (on the Layout tab) - which should be 1.0 or perhaps even
        smaller.
      There are other default settings (for example, double column
        layout, the vertical and horizontal rules, and Coloured text,
        etc.) which are turned on to highlight that these things are
        possible [and easy enough to turn off] rather than being
        prescriptive as "best practices".
      
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sillsdev/ptx2pdf/issues/341#issuecomment-760757543",
"url": "https://github.com/sillsdev/ptx2pdf/issues/341#issuecomment-760757543",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by davidc86** [comment]
I suspect the Indention problem mentioned in #328 might contribute to the "horrendous" indention of poetry. It is a bug which ruins an otherwise nice setup.

I can't read NRS text like what Mark displayed, but I have to disagree, Justin. It looks fine to me. Whereas wide columns are hard to read for many people, Research shows this is because the wider the column, the more difficult it is for their eyes to find the beginning of the next line (they lose their place coming back to the beginning if the columns are too wide). So, to me, the example given by Mark looks to have reasonable columns for their text orthography. 

But for us in Indonesia, we use roman scripts in a single column layout, because our words are long and we use larger text (for people with poor eyesight). But we also use larger margins, so the overall look of the column is not too wide and squatty.  (Yes we probably kill more trees than is advised, but for these small runs, 100-page books are not a huge problem.  

I hesitate to force PTXprint to "default" to a GPS standard that is designed for saving money when printing the final product on expensive rice paper. Rather PTXprint main target is specialty runs. And these should be designed for accessibility, not economy. (Besides the whole 12pt font design in Paratext is so hardwired and acts so bizarre if tweaked, that changing that should almost be disallowed. Keeping it at 12pt then allows everything else in PTXprint to act "normal".)
