### ISSUE TITLE
Only 99 Chapters shown for XXA book

### ISSUE THREAD

**Issue by RossWebb** [sillsdev/ptx2pdf#344]
We have used XXA for Bible Stories. In the project there are 142 "chapters" but PTXprint only offer 99 of them to print.
All chapter, however, are included in the PDF!

![image](https://user-images.githubusercontent.com/21695272/105109061-d28c9e00-5b0f-11eb-85c6-e552d67b759d.png)

Fixing this is not a biggie for me. But if they are real bugs, somebody else might trip over it.
Ross

**Comment by markpenny** [comment]
This has now been fixed and we use Spinners rather than drop-downs, so it is easier to use, AND you can go up as high as 999 for non-scripture books. Thanks for pointing this out and helping us improve it for everyone else.

![image](https://user-images.githubusercontent.com/12962708/105455321-2c47c080-5ce8-11eb-8923-11fdfb4555e8.png)
