### ISSUE TITLE
REQUEST: Start each chapter on a new page

### ISSUE THREAD

**Issue by RossWebb** [sillsdev/ptx2pdf#345]
Not a big deal, but we are using XXA "book" for a 140 Bible Story set.
It would be good to be able to specify to start each story (chapter) on a new page.

Ross

**Comment by markpenny** [comment]
Hi Ross - I'll have a think about adding an option to "Start each chapter on a new page", but am also reluctant to keep adding controls which may confuse novice users, and only be used in special circumstances.

There is an easy work-around though...

On the Advanced tab, ensure "Apply Changes Specified (PrintDraftChanges.txt)" is checked, then click the Edit button:
![2021-01-20 21_41_41-Window](https://user-images.githubusercontent.com/12962708/105258931-a7797b80-5bef-11eb-8563-543dbc64a936.png)

In the file that shows up, add this line somewhere (which throws in a \pagebreak BEFORE every \c ch-num):
"(\\c \d+ ?\r?\n)" > "\\pagebreak\r\n\1"
![image](https://user-images.githubusercontent.com/12962708/105259238-4c945400-5bf0-11eb-9ecc-bb1d341e732b.png)

There might be some complaints from the USFM checker (which can safely be ignored), but it should give you what you're expecting - with each chapter starting on a new page. But I noticed that the column-balancing algorithm gets thrown by this, and ends up with some weird formatting of orphan paragraphs in 2-col layout!

So, you might want to look at the settings on the Layout tab and make some adjustments like this to achieve what you need:
![image](https://user-images.githubusercontent.com/12962708/105259793-54a0c380-5bf1-11eb-9bef-3b4ab294d282.png)

And this setting allows unbalanced columns so that you don't end up with weird page breaks:
![image](https://user-images.githubusercontent.com/12962708/105259854-7bf79080-5bf1-11eb-8f31-dc0267865fb1.png)

BTW - I'm curious to know whether your XXA book is actually a Paratext **module**, or just contains text that has been copy-pasted manually from other parts of scripture.

**Comment by RossWebb** [comment]
Hi Mark,

Thanks for the workaround suggestion.
As for the XXA book, I'm not sure of the PTX module definition, but the text was imported from on old PTX project that never made it to the current registration status. So I just made a new project and imported it from the old project using the option presentted when I inistigated the new book.

Does that make sense?
Ross

[Ross Webb - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=v8tgr)	[v8tgr]

On January 21, 2021 at 1:05 GMT, Mark Penny <notifications@github.com> wrote:

Hi Ross - I'll have a think about adding an option to "Start each chapter on a new page", but am also reluctant to keep adding controls which may confuse novice users, and only be used in special circumstances.

There is an easy work-around though...

On the Advanced tab, ensure "Apply Changes Specified (PrintDraftChanges.txt)" is checked, then click the Edit button:
[2021-01-20 21_41_41-Window](https://user-images.githubusercontent.com/12962708/105258931-a7797b80-5bef-11eb-8563-543dbc64a936.png)

In the file that shows up, add this line somewhere (which throws in a \pagebreak BEFORE every \c ch-num):
"(\c \d+ ?\r?\n)" > "\pagebreak\r\n\1"
[image](https://user-images.githubusercontent.com/12962708/105259238-4c945400-5bf0-11eb-9ecc-bb1d341e732b.png)

There might be some complaints from the USFM checker (which can safely be ignored), but it should give you what you're expecting - with each chapter starting on a new page. But I noticed that the column-balancing algorithm gets thrown by this, and ends up with some weird formatting of orphan paragraphs in 2-col layout!

So, you might want to look at the settings on the Layout tab and make some adjustments like this to achieve what you need:
[image](https://user-images.githubusercontent.com/12962708/105259793-54a0c380-5bf1-11eb-9bef-3b4ab294d282.png)

And this setting allows unbalanced columns so that you don't end up with weird page breaks:
[image](https://user-images.githubusercontent.com/12962708/105259854-7bf79080-5bf1-11eb-8f31-dc0267865fb1.png)

BTW - I'm curious to know whether your XXA book is actually a Paratext module, or just contains text that has been copy-pasted manually from other parts of scripture.

**Comment by markpenny** [comment]
I just found out that you can use \pb instead of \pagebreak (for that regular expression)... so it would read:
"(\\\c \d+ ?\r?\n)" > "\\\pb\r\n\1"

**Comment by KimB2017** [comment]
markpenny, thanks for a useful expression! It looks like your "update the text above", as your later comment states, didn't get saved to your original instructions. The earlier comment still shows "\pagebreak".

**Comment by RossWebb** [comment]
Hi Mark,

I used this successfully - chapters started on new pages. Great.
However I recieved an error (which didn't stop the show) that says "Failed to canonicalise texts..."
It went on to suggest that the error might be bing caused by the Changes.txt contents.

Ross

[Ross Webb - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=vc40c)	[vc40c]

On January 21, 2021 at 3:26 GMT, Mark Penny <notifications@github.com> wrote:

I just found out that you can use \pb instead of \pagebreak (for that regular expression)... so it would read:
"(\\c \d+ ?\r?\n)" > "\\pb\r\n\1"

**Comment by markpenny** [comment]
@mhosken - do we need to add something to ptxprint.sty to ensure that \pb within the text don't throw an error?
DONE

**Comment by RossWebb** [comment]
Using the change suggest in PrintDraftChanges.txt I now have a new page per chapter and with no errors (1.5.9)
But a couple of other issues which I will adress in a couple of new requests :)
