### ISSUE TITLE
What is a factor, the effect of changing font factor on line spacing.

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#360]
Here is a zoomed shot of the PDF output, and it shows that the poetry text is getting a narrower line spacing than the main text, even though the styles for both are the same (except indentions).

![image](https://user-images.githubusercontent.com/65363206/106162137-c333d300-6155-11eb-8a73-e8ebbd0d479f.png)

I've included a RULER overlay to see the slightly narrower spacing.

Any idea why it would do this?

**Comment by mhosken** [comment]
Please submit an archive with temporary files.

**Comment by davidc86** [comment]
My archive file is 73MB. This space only handles <10MB files.

See this link to get into a shared folder that contains the zipped archive file: 

https://1drv.ms/u/s!AsIa18BQPThpr5IyG1d9rWgivJ_5tw?e=gagIbx

**Comment by mhosken** [comment]
Thanks for the archive. I was able to reproduce the problem. What is happening is that the \q1 baseline is not set and so it is calculated as the relative point size of the text 11/12 of the linespacing and so is 13.75pt instead of 15pt.

This raises the question @davidg-sil of whether the baseline should fallback to the paragraph baseline instead of being based on the font size (except for \p which should so fallback). I know it used to do that, but I can't remember why we changed it.

A work around is to force a baseline either by setting linespacing to 1.01 (so it actually gets stored) or an absolute baseline of 15pt.

**Comment by mhosken** [comment]
OK here's the plan:
- Change font size factor from base 12 to base 1. so what was 11 becomes 0.92 for example. This makes all factors have 1 being full scale rather than 12 (also for space before and space after)
- The linespacing for paragraph is the same as for all other styles and if not specified is font size factor * base linespacing

**Comment by davidc86** [comment]
I'm not following you... do you mean that this is what I should do with my config file in PTXprint? Or is this the plan moving forward for PTXprint to use when establishing a "base" value?
