### ISSUE TITLE
Way to edit Font Features?

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#362]
Martin's issue #333 was closed with a comment: 

> I've also created a font feature editor and integrated so that people don't have to type feature strings and work out what syntax to use, although you can if you want.

But I don't see a font feature editor in ptxprint. I am happy that the features I specified in my PT Project Language settings are being displayed in ptxprint. However, I don't see a way to change the PT-specified features or specify features for a different font. Am I missing something?

**Comment by mnjames** [comment]
I can't check this on Linux, but the location of font features was recently changed in ptxprint in Windows, and I wonder if that's why you can't find it. 

You now have to click the name of the font where it says "Body Text (Regular" and then Font Features is at the bottom of the dialogue box where you also would pick a new font.

**Comment by markpenny** [comment]
Yes, that's right. It all got moved so that *any* Font selection (for example in the Styles area) allows these settings to be set for whichever font is being selected. This gives the user far more flexibility to do clever things with multiple fonts (which may or may not use the same features). If you have any useful ideas on how to make this more discoverable, that would be great. Maybe something in the Tooltip for the Font Configuration...
![image](https://user-images.githubusercontent.com/12962708/106324910-d32aee80-62de-11eb-87a8-0754d4e39e8f.png)

**Comment by cmahte** [comment]
This is a question: The general format for opentype font features that
should appear in that box is

kern=1&liga=1&dlig=1

? How can we list properly 1 opentype feature or many?

**Comment by markpenny** [comment]
Ratz! I forgot to mention that there is even more magic hiding behind the enhanced Font Chooser...

The Font Features BUTTON displays a whole new dialog where you just get to choose whichever features you want!

![image](https://user-images.githubusercontent.com/12962708/106327205-94973300-62e2-11eb-98c4-c32386d717dc.png)
