### ISSUE TITLE
Image copyrights don't appear with first Print (Linux)

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#364]
When I switch to a new Configuration and click Print, the book copyright statement appears at the end, correctly. But the image copyrights do not appear until I hit Print a second time.

**Comment by markpenny** [comment]
Yes, unfortunately there's nothing we can do about this other than what already shows in the Tooltip:

![image](https://user-images.githubusercontent.com/12962708/106325140-33ba2b80-62df-11eb-83fb-9c5b71e301e0.png)

Any suggestions on improving the wording (without making it too long)?

**Comment by davidc86** [comment]
Maybe the NOTE should be moved to the top, as it is critical.

The rest is a clarification of what it is and how it looks. But if the user needs the illustrations included, and we do, then that is critical info. 

(For our more traditional books, we'd like this Colophon to occur on the back side of the Title page. But I guess this could be used to generated the contents to then paste into a "real" frontmatter PDF file?)

Now I'm wondering (because of another issue #373) if this 2nd Print relies on "temp files" hanging around, which they might not if the user has unchecked the box for temp files.

**Comment by KimB2017** [comment]
It DOES work to include these copyright statements on an intro page in an extra book, even in a Bible Module. Great!

In case it was missed, please see my latest comment on  #350, about how to get one-time custom copyright info for figs in.
