### ISSUE TITLE
Linux: Font Features are not applied

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#37]
A previous closed issue states that Font Features applied in a PT project carry over to PTXprint, but I am not finding this true in v 0.4.4 for Linux. I have found this true with Andika, Andika New Basic and Charis SIL (matching the font specified for the project's language to that specified in PTXprint).

**Comment by markpenny** [comment]
I believe that this issue has been fixed in 0.4.6 or later. Please let us know how it is going now, and feel free to close the issue if Font Features are now working as you expect. Note that there is a new control on the Advanced tab which shows you which Font features have been set (in Paratext).
![image](https://user-images.githubusercontent.com/12962708/79648590-32939400-81ce-11ea-8fca-74c772cb8d63.png)

**Comment by markpenny** [comment]
@mhosken I'm wondering whether we should:
(a) have a [reload] button for the Font Features (similar to what we already have on the Footnote + Xref Callers)
(b) have a checkbox to turn OFF Graphite Rendering [so that a user can force the /GR not to appear on the font name, and can test OT rendering. What are the pros and cons of doing this?
What are your thoughts on these?
