### ISSUE TITLE
HowTo for installing ptx2pdf and XeTeX is not linked in the Quick Start README.md

### ISSUE THREAD

**Issue by richmahn** [sillsdev/ptx2pdf#375]
First paragraph of the Quick Start README.md file doesn't link to a place to describe how to get requirements installed. The `(Instructions can be found here.)` text has no link

https://github.com/sillsdev/ptx2pdf/blob/master/docs/quick-start/README.md

**Comment by markpenny** [comment]
Hi @richmahn - thanks for pointing this out. When we find the instructions :-) we'll make the link.

We're actually working in an old github repository and adding a whole new way of using the ptx2pdf macros through a UI-based tool called PTXprint (see [home page here](https://software.sil.org/ptxprint/)). Are you interested in installing the macros manually so that you can work on them and develop them further (if so, let us know what you're interested in helping with), or are you primarily interested as an end user needing to create neat PDF scripture output (in which case I'd suggest starting with PTXprint)?

**Comment by devosb** [comment]
I fixed the issue @richmahn pointed out in https://github.com/sillsdev/ptx2pdf/commit/8f3878ec6a007b5093f5270f4cdf8c3ab1195710 @markpenny asks a very good question, the same one I was going to ask.
