### ISSUE TITLE
Font feature Literacy Alternates in Andika

### ISSUE THREAD

**Issue by KimB2017** [sillsdev/ptx2pdf#381]
Andika and its variations have "litr=1" (on) set by default. In the features dialog most features have a simple toggle Unticked/Ticked. If I untick litr for Andika it has no effect, because the default state is ON. I don't see a way to turn litr OFF for Andika, to make it look like a normal sans font.
![Selection_102](https://user-images.githubusercontent.com/25071218/107082616-7047c480-67c2-11eb-9d42-4009da3eeca2.png)

**Comment by KimB2017** [comment]
Update: When I switched from AndNB to vanilla Andika it seemed to pull in my PT-defined features! Maybe that's because I have Andika set as fallback font (because AndNB is missing some of the characters designated for marking Glossary entries, but it has true bold and italic).

Then if I switch back to AndikaNB my PT-specified features are present again. But if I play around with the features, the only way to turn Lit Alternates back on is to type "litr=0" in the features text box. Maybe this one needs a dropdown in the Features list instead of a tickbox?

**Comment by mhosken** [comment]
Language settings and features should now (**after** 1.5.10.2) work together. Of course the ability to turn off a feature is uniquely Graphite. In OpenType, all features are by default disabled and have to be explicitly enabled in a font. Thus you can't default a feature to on and allow the user to turn it off. OpenType just doesn't work that way :(

**Comment by KimB2017** [comment]
I see that Literacy Alternates now adds a 0 or 1 statement to the selected Features list when I untick or retick the checkbox. Thanks!

Question, f**my**i please: I searched through [scripts.sil.org](https://scripts.sil.org) pretty carefully for some documentation about how OpenType works. I see many references to it but nothing I could see about how to use it. I am pretty ignorant about fonts in general except for the aspects I need to use, which I like to at least begin to understand. Are you saying that when you use Andika in an OpenType app it displays by default with the literacy alternates turned OFF? Also, what are some OpenType apps?

**Comment by KimB2017** [comment]
Fixed!

**Comment by mhosken** [comment]
OpenType is a text shaping technology like Graphite that takes a string and a font and returns glyphs and positions for presenting on the page or screen. It's not something a user 'sees' per se. A single font may support both Graphite and OT (OpenType) with different data structures in the font giving the information the shaping (converting string to glyphs and position) technology (OT or Graphite) needs.

Graphite is great but has not been accepted by the industry (thank you MS & Google). OpenType is less powerful, but can generally do the jobs necessary. One limitation is that you can't default a feature to on and so can't turn off a feature. All features are by default off.

TypeTuner is a way of producing fonts with features defaulted to on and off. The effect of tuning a font is that it makes it impossible to turn off a feature that was turned on by TypeTuner. The best solution is to use the untuned font with all the features as you want them. So for example, Andika Literacy is basically Andika with some features turned on (and perhaps a narrower default line spacing). In PTXprint you are better off using Andika and then setting the appropriate features you want. And since PTXprint sets the line spacing itself, the narrower linespacing of Andika Literacy has little value either.
