### ISSUE TITLE
v1.5.10 "factor" is not user-friendly

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#383]
Sorry to be a downer, but I just wanted to say that the whole idea of using a "factor" system in the style specs is not going to be user-friendly. I don't know where the idea came from, and maybe it is common in some circles, but it is a mathematical construct that computers are great at, but has little tangible real world "hooks" for most field users, who are not professionals (and PTXprint wasn't designed for professionals). So field teams know about labels like "font-size" or "point-size" and they might know about pixels. But scaling will be completely foreign. 

Just a concern. Because people have "rules of thumb" like, "11 pt looks good for main text, 10 point for intro, and 9 pt for footnotes, and 12 pt for section headings" or whatever. 

But with scaling, it will just be a guess as to what 0.92 will get them. 

Granted we could teach them to take the base font size of 12 (or whatever it happens to be) and multiply it by 0.92 to get  11.04pt (which I suppose is rounded to 11pt). But why? Doing calculations are what computers are for, not something humans need to do. Why can't the interface just let people type in the FONT SIZE they want, and the computer calculate whatever is needed to get the math to come out correctly for that size? 

I.e. Who cares what the "base font size" is? If I put in 11 in the style sheet, and the base font size is 12, then the math underneath convert my 11 to a 0.92. BUT if the base font size is 11, than my 11 in the style sheet converts underneath to 1.0. 

In my mind, the new design is backwards. Might it not be easier for field teams if the "base" value defaulted to 1.0, while styles were entered as 12 pt or 11 pt etc. because that is what people are expecting and wanting specify. Then if for some oddball reason, I want to shrink everything in my configuration a little bit to get it to fit on a weird page size, but still look proportionally balanced, **then** I adjust the BASE size down to say 0.9 to shrink everything down to 90% of the original sizes, and I do a test print to see if that does the trick. If it isn't quite right, I tweak the base number again. This way I am only tweaking ONE thing--the % of the BASE in order to change all the point sizes in the style sheets etc. When I'm done messing with oddball sizes, I just revert the base value back to 1.0 and boom everything is back to normal.

Just wondering about the current direction on this.
Again, sorry if this comes across as whining and complaining. It is only meant as a real question and concern. Please correct my understanding if I'm off the mark here. Thanks.

**Comment by markpenny** [comment]
Hi David, Thanks for expressing these thoughts. We *were* expecting some push-back, and want you to know that we've talked this through in depth over multiple occasions. And I also agree with you that ordinary users can't deal in "factors" but need to see font sizes in Points. So just earlier this week I added the *calculated* point size on the Character Settings tab which will, for example, display what a Font Size Factor of 0.83 will produce when the Base Font Size is 12pt:

![image](https://user-images.githubusercontent.com/12962708/107607229-857a9280-6c9d-11eb-8171-4bc5bf1a8e2f.png)

And as the user tweaks the Factor, that value updates - so they don't have to do the maths themselves.

But I can still hear you say, "Why not just stick with points for sizes?" And I think I now know enough now to explain why what we have done *is* better. Here are 2 scenarios (A) is using pts everywhere, and (B) is using the Factor system.

(A) I set up my publication for A5 page layout, I set the Base Font Size to 10.5pt. I change various settings for the footnotes and section headings to be 9pt and 9.5pt respectively. I'm happy with these settings and then I print. All good so far. But later someone wants to do an A4 layout. So I go and change the Base Font Size to 12pt, and most things look OK, except (you guessed!) the footnotes and section headings are rather small. Oh yes, I need to go back and adjust them, and all the other styles that you might have tweaked over the days/weeks when you were refining it. [In other words, specifying absolute values is easy to do, BUT the price you pay is that *you* have to remember what you changed and *you* have to tweak those values again and again each time you change page size.

(B) As above, except that instead of applying absolute font size values in Points, you tweak the *factor* until the correct pt size displays. It works fine in A5, and then later when you switch to A4 and increase the Base Font size, EVERYTHING automatically scales accordingly. You have no more tweaking to do.

So, yes, it is a bit different. But once you understand the why and how, it is a very elegant system.

Extra tidbit:
You're probably wondering why we ALSO have the "Scale Relative to Parent" and how that is different from the Size Factor. For that, imagine the word LORD which is wrapped in \nd Lord\nd*. Assuming your font *doesn't* have SmallCaps, we need to make this word slightly smaller; but HOW small? That all depends on context, so in the Body text of 12pt, we might want LORD to be displayed as 10pt; but in the footnotes of 9pt, we need it to display (not as 10pt, but) as 7.5pt - so that it displays proportionally (or relative to the parent style). So for that we need this setting, and setting \nd to be .833 would handle both cases.

BTW - we've just revamped the Margins and brought them all together onto the Layout tab (sorry about the grayed-out look - that's just a temporary glitch):

![image](https://user-images.githubusercontent.com/12962708/107608438-dfc92280-6ca0-11eb-9521-a7507670c090.png)

Any thoughts/feedback on that?

**Comment by mhosken** [comment]
Further on A). While typesetting, you are working on choosing a font and appropriate size. There is no expectation you are going to get it right first time. Or you are working in a non-Roman script where point sizes may be much higher generally. You may decide that you can solve some spacing issues by a .1pt change in the font or the linespacing. You know. All the tricks typesetters use to make documents work. These changes are achieved much more simply by a single setting rather than having to change the point size of every marker.

I am somewhat sympathetic to your having a global font factor and concrete point sizes in each style. But then you have exactly the same problem if your font factor ever deviates from 1.0, which I've just shown is highly likely. Hopefully the label will offset some of the confusion and people can just fiddle with a specific marker's fontsize (a relatively rare activity, since it changes the balance between elements in a document) and see the resulting point size there immediately.

**Comment by davidg-sil** [comment]
I think the underlying issue that is being addressed is that (in the ptx2pdf macros that PTXprint is built on) a marker's font size has always(?) been treated as a multiple of the _'fontsize unit'_, which probably had only a passing resemblance to 1pt in most projects. But since it a paragraph's font size was normally 12 fontsize units, (and since paratext is also involved, and says the number is measured in points) people expect 12 _fontsize units_ it to be 12_pt_, and think they need to go through the whole stylesheet and edit everything to make it 11, if they want 11pt text, when all they **actually** need to  do is change the fontsize unit to 11/12 of a point (which happens in PTXprint by setting the font size on the main page).

By 'hiding' the stylesheet's '12' behind the factor, PTXprint is trying to help people realise that they're **really** changing the relationship of text produced by a given marker to that from other markers, not setting a font size, and normally that's not something they ought to be doing without thinking long and hard about what it does to the balance of the document.

**Comment by davidc86** [comment]
Thanks for these explanations you all wrote. They are very helpful and would be nice to see in a Help file.  During the night I thought of the idea of keeping the factor values, but having the computer display the resulting pt size next to the scale/factor box, just like Mark showed in his screenshot. It would be very helpful if this feature displayed next to every place the user enters a factor value.

Some observations while testing v1.5.10:
1) It looks like the layout and styles etc. now have a mixture of factoring and pt size specifications (and maybe inches too?). Seems more confusing this way. Maybe everything should be a factor? (with a calculated point size/inches/mm displayed next to it?)
2) I've noticed when testing the factor settings on my style sheet, that 2-decimal places seems too large of a jump. I.e. to increase the size of the line spacing from say 1.01 to 1.02 makes a very large difference in how it is displayed. So maybe something isn't working quite right yet, as such a jump should only increase the "point" size from 12.12 to 12.24 -- a very insignificant jump.
3) I also noticed that if I start reducing the line spacing down to say 0.83, after a bit of tightening, it stops doing anything at all. Is there a lower limit? If so, this should be noted. 
4) Also, at this point I have no idea what this 83% line spacing is measured against: Is it in relation to the base font size? Or the current paragraph's font size? Because if the base font is 12, but the current paragraph is an intro paragraph, with a factor that yields a 10pt font, then I'd probably want to adjust the % of line spacing based on the CURRENT font size, not some arbitrary base font size. But maybe a user keeping track of that would be asking too much. 
5) Each FONT style on my computer seems to have a different base size (what is 12pt for one is larger or smaller than 12pt for another--weird but apparently true). So it seems that using a % of some generic font might be problematic, especially if the document mixes different font types.

**Comment by mhosken** [comment]
1. There are no factors on the layout page. All settings have their units listed (well they do now). There are no dimensionless values on that page.
2. Pass. Would need to reproduce.
3. There is a macro set limit that says: you can't have a line spacing that would result in the top of the next line (ascender) being more that 7/12 of the base linespacing above the baseline of this line. We've never encountered anyone wanting to change that limit. If you are finding you are hitting this limit without lines overlapping, I would be interested. Anyway, I think that's a bit of a longwinded thing to explain in a tooltip for something that is unlikely to be hit in real life.
4. See 3. above. As per the tooltip for linespacing, the linespacing factor is against the base line spacing on the layout page (under the base font size). Not sure how to make this much clearer.
5. Yup. That's why we want a way to make it easy to change all the font sizes in one go.
