### ISSUE TITLE
v1.5.10 footnote styles do not seem to have much of an effect

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#384]
I might be missing something here, but changing the footnote style to LEFT instead of justified is not working:

![image](https://user-images.githubusercontent.com/65363206/107684106-60235f80-6c70-11eb-8e5a-ef5fe2d700a0.png)

Also oddly, I set LEFT in the top level of footnote, but all the sub-nodes still keep the JUSTIFIED label, and when I went through and changed all of these to LEFT, PTXprint marks these with a **bold** label (meaning the setting is _different_ from its parent, but the parent is also LEFT), so why are these marked with bold? 

It seems to me the more logical thing to do whenever a user changes a Parent value, is for PTXprint to change all sub-nodes to follow the change in the parent, or if that is dangerous, then all the sub-nodes that don't match the parent's new setting, should be marked with Bold (and the **_collapsed view should open to show this_**, btw), and then we can quickly "return these to match the parent" by clicking on the bold label.

(Also, I'm not sure why when these all went "Justified", they suddenly couldn't properly do a proper line break.) 

It was working as JUSTIFIED just fine earlier today. So I don't know why it suddenly won't format these correctly anymore. 
Also, it is not clear how we actually control the CALLER formatting, so that we can specify its size and vertical location. REASON NEEDED: the caller in the main text is scaled to be nice looking for 11pt font (or thereabouts), whereas our footnotes are 9pt with very narrow line spacing, thus the footnote caller is flying too high and is too large for the surrounding footnote reference and text. And I'd like to get rid of the space between the caller and the reference number. How is this done?

**Comment by davidc86** [comment]
(I can't send an archive. v1.5.10 won't build one.)

**Comment by mhosken** [comment]
Much of this is addressed in #385. There is nothing that says that a parameter's label is bolded due to a difference to some 'parent'. The tooltip is quite clear: a parameter's label is bolded if the value is different from what is in the stylesheet. More specifically as specified in the chain of usfm_sb.sty, custom.sty ptxprint-mods.sty. I.e. that what you see is uniquely edited here in ptxprint gui.

Also, because there is no notion of parent styles, there is no subnodes either. They are just a way of providing a visual hierarchy for finding markers. So, no setting something in one marker/node does not set anything in any other nodes/markers. Having said that, we are toying with the idea of doing that for q/q1 and s/s1, but only because they are near synonyms and we would have to think about what happens if someone wants them different.

**Comment by mhosken** [comment]
Other than this, this is a repeat of #388 and will be addressed there.
