### ISSUE TITLE
v1.5.10 footnote spacing

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#385]
I would like to control the spacing between footnotes when they are NOT paragraphed. Not sure which control has an effect on that. Here is what I'm seeing:

![image](https://user-images.githubusercontent.com/65363206/107690766-8ea53880-6c78-11eb-8de3-92c00d3d8fe0.png)

The line spacing inside the footnote is set to 10.5 absolute pt size (because that was what I found to work). I'd rather use a scale factor if I could get that to work. But I don't know how to control what spacing occurs between footnotes. 

1. As you can see it is a bit squished between them.)

2. You can also see that the line breaks are still not correct. I have a printed version of this same set of footnotes where the first line ends with "..._anggur yang_" but PTXprint won't break it correctly like that anymore.  

3. I'd like to LOWER the caller and pitch the space. I'm still looking for that option, 

4. The style sheet says "factor of the parent" but in actual fact, it is treating \p as the parent, when the UI suggests that \f is the parent here.

**Comment by mhosken** [comment]
1. Oh go on then. Since you asked so nicely :). I've enabled the spacebefore and spaceafter values for non paragraphed notes, so now you can control the space between notes in a class, where you have one note per paragraph. If notes are merged into a single paragraph, the parameters are ignored.
2. Yes. I would like to dig into that with an archive, once we can get one.
3. You can set up a new marker to style the caller (and the notecaller). See the caller style and note caller style edit boxes under note settings in the style. Create a new style based on v and set the font size and raise (and turn off superscript, which is a poor man's hack for a quick reduce of point size and raise).
4. I don't think parent means what you think it does. The hierararchy of styles in the stylesheet is purely a way to organise the tree and there is no parent child relationship between any markers anywhere in the system. By parent we mean the context in which the marker is being used. Thus if you use font scale the font size will be a factor of the font size of the text in which the character style is being used. In ptxprint we present the size based on the \p style, but within a footnote, the text would almost certainly be smaller. I've added the word text to Scale Relative to Parent Text to perhaps help reduce such confusion.

**Comment by mhosken** [comment]
The layout issues will be addressed in #388. Hence saying this bug is fixed.

**Comment by markpenny** [comment]
I'm wondering whether the word "context" would be better than "parent", so something like: Scale Relative to Context, or perhaps Scale Relative to Surrounding Text. Any thoughts?

**Comment by davidc86** [comment]
I like the idea of "Scaled Relative to Surrounding Text". Also the idea of when we tweak the factor values, it would be nice if the current pt calculation could be displayed next to it in the Style sheet, would be really helpful. Just today I used the Calculator to figure out what the apparent pt size would be with the given factor. But on other tabs where you have provided this feature already, it is VERY handy! Excellent work. The header margin tab is just wonderful now!!!
