### ISSUE TITLE
v1.5.12 a string of \xt references are treated as though they don't have breaking spaces

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#394]
The text has this in it: 
\ip Markus kyesy Kitab ne ma yaklol ohe, Yesus neke Raja Maoryetake, ode Hulasokwe Anan a I (matos \xt 1:1,11,24; 3:11; 5:7; 8:29; 9:7; 14:61-62; 15:39\xt*).

This comes out looking like this: 
![image](https://user-images.githubusercontent.com/65363206/107984704-8578dc00-6f96-11eb-9593-d80956b3aade.png)

But the standard we use specified in the PT settings is that the semi-colon ";" marks the break between one chapter's references, and another chapter's references. I suspect if PTXprint just treated the space after ";" to be a possible line break location, we'd solve this problem. I don't recall this being a problem before. 

I did check the box:  
![image](https://user-images.githubusercontent.com/65363206/107984870-ebfdfa00-6f96-11eb-9595-96c135f14cfe.png)

But this should not affect the behavior of "; " only the space between the book name and the chapter number, e.g. Mrk. 1:11

I could probably solve this manually by putting in \xt around **_each reference_**, but since PT does not require this, I would rather not do that, as this is something a computer can do more reliably than a human.

**Comment by markpenny** [comment]
@mhosken  - we need to figure out *what* we actually need to do in this situation. My current thinking is that we shouldn't allow the non-breaking space to be inserted after a semi-colon ;   - is that enough to resolve this one and not have any other unintended consequences?

@davidc86 - There's a problem with this reference - 'matos' should be WITHIN the \xt, as that's what we're trying to keep together book name followed by ch:vs reference. But here everything else is being tied together with a NBS, but 'matos' is free to be separate from the ch:vs refs. 

![image](https://user-images.githubusercontent.com/12962708/108639223-47c90580-74f8-11eb-8673-6f3de1b7b35e.png)

[AFAIK: The reason that you NEED 'matos' within the \xt is so that Paratext can actually check the chapter and verse refs to ensure they are valid. If you had 29:34 as a ref within the existing \xt, it wouldn't flag that as an error - but if matos was within the \xt it should pick it up as an invalid chapter+verse reference for matos.] Here's what it would look like if matos was inside:

![image](https://user-images.githubusercontent.com/12962708/108639434-5b28a080-74f9-11eb-8c6c-e0e52f0c93cf.png)

I think we only want the 1st match to have the NBS added, not the subsequent ones.

**Comment by davidc86** [comment]
Actually, that isn't quite right. The word "**matos**" means "**see**", it is not a book reference at all. Paratext specs do NOT require the book abbreviation to be included **_if_** the reference is to the CURRENT book, which these are. This is intro material referring to various bits in the current book.

**Comment by markpenny** [comment]
Okay - thanks for fixing my faulty understanding! We'll fix the code :-)

**Comment by davidc86** [comment]
Woohoo! Nicely fixed. Thank you very much. Output looks great.
