### ISSUE TITLE
v1.5.12 Headers enhancements are great, but are the measurements correct?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#396]
Here is what I'm seeing: 
![image](https://user-images.githubusercontent.com/65363206/107988660-8150bc80-6f9e-11eb-9296-25cde4f415de.png)

This says the SIDE margin is measured in mm and it set to 12.
The top margin (to text) is measured in mm and set to 17.5
The header to text space is 12 POINT (and the header text itself is set to 10.5 pt on the Style page)

So it says the Edge of Pager to Top of Header is 6.318mm. 
This may be true... I don't know. I looked all this up and got: "The contemporary desktop publishing point (also called the PostScript point) was defined as 72 points to the inch (1 point = 1⁄72 inches = 25.4⁄72 mm = 0.3527 mm)." 

So 12pt (header gap) + 10.5pt (header size) = 22.5pt * 0.3527 mm/pt = **7.93575mm** (from top of text to top of header)

And so if you take that value from the **17.5mm top margin**, you should get something like **9.56mm**, right? (Not the displayed 6.318mm. Or am I missing something?)

**Comment by davidc86** [comment]
Also, Footnotes have a lot of fiddly things to think about, like Footnote spacing, Footnote horizontal rule, etc. But this only gives the Bottom margin to Text (mm) and Bottom Margin to **_bottom of_** Footer (mm). 

So, is the RED measurement the **absolute minimum**? 
What about where we don't put the page number on the bottom of the page. If there is NO Footer on a page, does the text go all the way down to the BLUE measurement, or does it still stop at the RED measurement?

**Comment by markpenny** [comment]
I think the best way to describe what is going on is with this diagram:
![image](https://user-images.githubusercontent.com/12962708/107992829-66ce2000-703e-11eb-81b5-42b78cfd49e9.png)
Ignore the arrows on the right. Look at the blue, red and orange arrows on the left. There's a mismatch between what the user thinks they are specifying and what they are actually specifying. And the reason for this is that the "Effective Font Height" is actually only 0.7 of the line height/spacing. 
So in the image above, the (thicker) arrows on the left are what PTXprint is actually using in its calculations. But the user is expecting the distances shown by the thinner arrows.
So that explains the problem, and I need to talk through with MH about what the possible solution is/should be.

**Comment by davidc86** [comment]
Excellent diagram! Nice to have this in a document somewhere once the feature dust settles a bit on all of this.

**Comment by mhosken** [comment]
It is pretty much impossible for us to work out what is the top of text for a font given that different scripts and texts extend different amounts above the baseline. For example, in devanagari, the height of the text is to the washing line, even though there are diacritics that go above. For Latin, is the height the x-height, cap-height or ascender height? Since it is so ambiguous and a mess, we have had to choose heights that may not seem obvious at first glance, but that we have tried pretty carefully to express in the tooltips.

It may help if we were to put the header and footer into boxes that extend from their baseline to some notional ascender height and then show arrows to that. Likewise showing the 'notional baseline above the top line'.

**Comment by markpenny** [comment]
> It may help if we were to put the header and footer into boxes that extend from their baseline to some notional ascender height and then show arrows to that. Likewise showing the 'notional baseline above the top line'.

Like what we have above in the devanagari example...

**Comment by mhosken** [comment]
yes but with less arrows :)

**Comment by markpenny** [comment]
I've re-worked the graphics so that it is clearer to the user WHAT is actually being measured, and the tooltips explain why the measurements they would expect to see don't match.

![image](https://user-images.githubusercontent.com/12962708/108460086-c5182e80-72dc-11eb-835a-d31a805f0c60.png)

Also note that the three controls highlighted also change the graphics so that you see a "preview/result" in the graphics of the changes being toggled.

**Comment by davidc86** [comment]
Wow! Very nice! Well done Mark.
