### ISSUE TITLE
Does "factor" mean "factor"?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#401]
My understanding of "factor" is a mathematical calculation.
Base line spacing of 15pt 
A style's line spacing factor of 1.0 = 15*1 = 15pt

But it doesn't always work this way. **A factor of 0.0 should yield 0pt, right?**. 
**A factor of 0.25 should yield 1/4 of the base value, right?**

I've noticed that, as I adjust the Space before and Space after factors for say intro section headings, just ever so slightly, boom! suddenly it results in either another whole line added in, or the extra spacing altogether drops it out to zero altogether, even if I'm not saying 1.0 or 0.0. I'm not seeing how to get something like a 1/2 line spacing (6pt line spacing) before or after some things. 

Also, my intro styles are set to a factor 0.91 against the base font  size of 11pt, so this gives me 10pt   (yeah! this works nicely).
But the line spacing factor of 1.0 against the base line spacing factor of 15, should give me 15pt (way too big, but regardless, it doesn't give me that). It looks a whole lot more like around 12pt to 13pt line spacing. Any idea why that would be the case?

Changing the intro line spacing factor to 0.91 (like the font factor), against the base line spacing of 15pt should have yielded around 13pt., which for a 10pt font is adequate. The results were no different from when the line spacing was set to 1.0.

Elsewhere MH wrote: "There is a macro set limit that says: you can't have a line spacing that would result in the top of the next line (ascender) being more that 7/12 of the base linespacing above the baseline of this line. We've never encountered anyone wanting to change that limit. If you are finding you are hitting this limit without lines overlapping, I would be interested. Anyway, I think that's a bit of a longwinded thing to explain in a tooltip for something that is unlikely to be hit in real life."

Actually, as an end-user, I find it much easier to learn software, if the computer doesn't 2nd guess me. If I want to have two lines write nearly on top of each other, so I set the line spacing factor to 0.25 or some such, and it comes out overlapped, then I KNOW how that featuer works. But if I specify 0.25 and it DOESN'T come out overlapped, then I have no idea why, and begin to think there is a bug in the software. 

The problem with getting correct space before/after seems affected by the software trying to keep me from doing something it thinks is dumb. The line spacing for my intro paragraphs is also another example: what I'm seeing in the output doesn't seem to related clearly to the values I'm entering in the style sheet. 

 Any ideas?

**Comment by davidc86** [comment]
Here is an example:
Base Font: 11pt
Base line spacing: 15pt

Main Title \mt1 
Font factor: 1.55  (17.1pt)
Line Spacing factor: 0.99 (Is this against the 15pt base? If so, this should give a spacing of 14.85 -- kind of tight)
I get this: 
![image](https://user-images.githubusercontent.com/65363206/108021089-cc44f100-6feb-11eb-9070-9afde2117cd1.png)


But if I change this 1/100 to a factor of 1.00 line spacing, I get this: 

![image](https://user-images.githubusercontent.com/65363206/108021166-f72f4500-6feb-11eb-823c-1b213d6256d8.png)

That isn't correct. A 1/100 change in a factor should not radically change the spacing.
Note that if I change it to 0.98 or 0.95 etc. there is almost NO CHANGE (not that I can see) from the look of 0.99, as one would expect. So, what is different with how the 1.0 value is used?

Thanks. Any clues would help.

**Comment by mhosken** [comment]
I think you are raising two questions here:

## 1. Space above headings not adjusting linearly
Text is laid out on a grid and in order to keep text on the grid, we go through some pretty wild basic maths  to make sure that the whole group of headings fits into an integral number of lines. Thus if you slightly increase or decrease the space before the first line of a heading, it is liable to make no difference, it's only once that change triggers an integral number of lines for the whole heading box, that you will see a change.
This raises the question of whether we want to allow an off grid setting for those printing single column and who don't care about backing up their text, so necessary when there is visual blead through on the page. I don't think we want to break grid on two column text otherwise it just looks ugly.

##2. Why are you limited from how close lines can get to each other?
(I'm working this out as I type this). Let's do the math on this and see what it turns up. First we need to know the ascent of Charis SIL (Let's assume that's the font you are using), which is 1.196 em. So the height of the font for the mt1 is 17.1 * 1.196 = 20.46pt. The linespacing is set at 15pt (give or take). Thus TeX considers the top of the text to be 5.46pt above the baseline of the line above. The TeXBook says the following:

> Whenever a box is added to a vertical list, TEX inserts “interline glue” intended to make the distance between the baseline of the new box and the baseline of the previous box exactly equal to the value of \baselineskip. But if the interline glue calculated by this rule would cause the top edge of the new box to be closer than \lineskiplimit to the bottom edge of the previous box, then \lineskip is used as the interline glue.

In the ptx macros \lineskiplimit = -7/12*15 = 8.75pt with \lineskip=0pt. So what confuses me is why you have hit the lineskiplimit with your values. I would have expected the linespacing to have to have been 0.78. Much tighter. Aha, but I am not taking into account the depths of boxes. The descender for Charis is at 0.439 em which at (let's guess the point size of the text on the line before the mt1) 15pt gives 6.59pt so now our overlap is 5.46 + 6.59 = 12.05 which is way above our 8.75pt and so triggers the "don't insert the baseline space" action. Now if we really wanted we could work out the precise figures for the point size and spacing for the line above from the knowledge that the lineskiplimit is not triggered at 15pt but is at 14.98pt. But we don't need to (and there would be some guess work since we need 2 numbers from one piece of information). We know enough.

So, what's the culprit here? To be honest, it's a lot to do with Charis having a descender to ascender height of 1.61em. The lineskiplimit is 0.58xlinespacing which is often 1.2 font size which makes it around 0.7 the point size. Factor in an increased size of the text in the lower line and you can hit that pretty simply. So perhaps we should increase (well decrease) the lineskiplimit. We don't want to make infinity, but perhaps we can drop it to say -9/12 which at least allow some overlap. I'll do that and you can then decide if you still want more.

You did ask!

**Comment by davidc86** [comment]
Haha! Yes, I did! My bad. 
Well, rather than do a pile of special math for this, why not allow Main Titles, Secondary Titles, and all Intro materials to be freed from the integer grid? As these will often be different in font size, and are generally limited to the first page of each book (unless people get verbose!), so keeping this nailed to an integer spacing seems overly restrictive. 

One thing we have done in the past (using Word or Libre Office) on other bits of text, like section headings and parallel reference lines, etc. is to try to adjust these to wiggle inside an integer box. Say the primary text is 11pt and line spacing is 15pt, and the section headings are also 11pt, then we'd like to separate them a bit from surrounding text. So we often made them spaced out with 5.5pt extra below and 16.5pt above. I'm not sure how this works out in TeX and PTXprint, but in Word, it's like adding half a space below and a space and a half above, so in the end the next body of text starts in the exact same Integer Box that the rest of the text will be in. Keeping all lines of text lined up. 

I believe this is what you are doing mathematically behind the scenes, which is _very helpful for main scripture text, but not so much for Intro materials, or titles_, or maybe even picture captions, etc. 

So, "cool" feature! But also it is confusing to end users,  **because subtle tweaks are not reflected in the output, and the interface gives no reason why**.  I don't have a suggestion for tweaking the Style UI except maybe to somehow disallow certain values, and have a button "_Why can't I specify certain values?_" which then gives the whole "_PTXprint tries to keep the scripture text lined up across the entire document..._ etc."
