### ISSUE TITLE
Don't break footnotes across pages

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#403]
Shouldn't there be a way to prevent footnotes from splitting across two pages? I don't think our readers would be able to handle that...

**Comment by mhosken** [comment]
Why? Are you seeing it happen? It shouldn't

GB,
Martin

**Comment by jeffheath-sil** [comment]
It has happened! I've got a pretty extreme case of a book where I think they've overdone the footnotes a bit (too many and footnotes too long). But in the two cases where a footnote is broken across a page break, XeTeX could have pushed them onto the next page leaving a few blank lines on the previous page. (Neither was one of those extreme footnotes which was very long.) I've sent an archive to the support address.

**Comment by mhosken** [comment]
From yet another reading of the TeXbook, I see no way to stop footnotes splitting. The only way is to manipulate the page lengths appropriately, just as you manipulate for appropriate page breaking using the .adj file. In this case the aim would be to get the line with the two v25 footnotes onto the next page (e.g. EPH 2.11 +1)

Another option, which may be easier, but will mask the problem and look just as bad as not page breaking well, is to set:
```
\interfootnotelinepenalty=10000
```
This will make it impossible for TeX to break a footnote since there will be a \penalty10000 at the end of every line. This works well for you separate footnotes. I'm not sure how it works for paragraphed footnotes (run together).
