### ISSUE TITLE
v1.5.14.3 End of Book decoration causes PTXprint to not export colophon

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#408]
Here is the colophon: 

\pc BRIT ERAS MARKUS IKESKYE
\pc ti tel Maslyarkwe, Maluku, Indonesia
\b
\pc KABAR BAIK YANG MARKUS MENULIS
\pc dalam bahasa Selaru, Maluku, Indonesia
\b
\pc THE GOOD NEWS WHICH MARK WROTE
\pc in the Selaru language, Maluku, Indonesia
\b
\pc \zcopyright
\pc \zlicense
\b
\pc \zimagecopyrights
\b
\pc Buku ini ditulis dalam bahasa Selaru [slu].
\pc Untuk informasi atas bahasa ini, mari menuju ke situs:
\pc https:/ / www.ethnologue.com/ language/ slu
\pc dan
\pc https:/ / www.selaru.org
\b
\pc Buku ini disponsori oleh:
\pc Yayasan Pemberdayaan Masyarakat Desa
\pc Jln Ki Hajar Dewantoro
\pc Saumlaki, Kabupaten Kepulauan Tanimbar, Maluku 97664
\b
\pc Edisi Percobaan
\pc YPMD-KKT
\b
\b
\b
\b
------------------------
Nothing comes out in the PDF.

Here is how I have it set in PTXprint: 
![image](https://user-images.githubusercontent.com/65363206/108752884-080f1780-7512-11eb-8cea-4cd4502db8d4.png)

**Comment by markpenny** [comment]
Strange! I plugged your colophon text into my project and ran it and it worked just fine. I wonder what (else) is different.

![image](https://user-images.githubusercontent.com/12962708/108811232-c36aa580-7611-11eb-949c-eb1ca217db76.png)

Note that you no longer need to add a space after / as we do this automatically for you. So normal URLs now get preserved properly, and are even clickable in some PDF viewers :-)

If you still can't get it to work [have you tried it in a new config yet?] then please send a link to (small) ZIP Archive :-)

**Comment by davidc86** [comment]
Okay, weird. You can get it to work, but I can't.
I tried turning off the Page Break before option, but that just made it worse! The final page chopped off the last line of scripture and just ends! See this, the last page in the PDF:

![image](https://user-images.githubusercontent.com/65363206/108868948-b70c2b80-75c4-11eb-9da7-9233218428b8.png)

Turning on the "Page Break" at least gets me the whole verse text and the end of book decoration.

AHA! Turning off the end of book decoration caused the colophon to be exported! 
So there's the bug. If an end of book decoration is active, then the colophon messes up.

**Comment by davidc86** [comment]
Note: if no end of book decoration is included, the footnote on the last page looks even weirder (to me).

![image](https://user-images.githubusercontent.com/65363206/108869674-6812c600-75c5-11eb-894b-f04c3556e42d.png)

Maybe some prefer that? I don't know. To me, it looks messed up.

**Comment by davidc86** [comment]
By the way, in messing with this, I opened the CFG file in Notepad++ and saw several blank lines in the colophon section, even though they don't show in PTXprint's edit window. I removed them from the CFG in Notepad++ and reopened PTXprint, but it didn't make a difference. Still, not sure why/how those extra lines got in there, but might it a good idea if the CFG save function removed any empty lines (i.e. <Enter><Enter>, etc.) when it saves?

**Comment by markpenny** [comment]
There must be more to it, as mine shows up:
![image](https://user-images.githubusercontent.com/12962708/108918040-9364e600-7695-11eb-99ce-32d735399f1c.png)

But perhaps it is because when the end of book decoration isn't there, there is more space for it to fit on the page. I think the issue might be more related to the box being too big for the page (which is being addressed elsewhere).

BTW - why don't you put the massive multi-lingual colophon material into the FRT book (or even a BAK book) instead? I think the main reasoning behind the colophon was to make it "easy" for those doing just a short 1-book publication to comply with the requirements without having to think too much, or even edit the preset colophon text. But if it is going to be much longer and complicated, I'm guessing it should really be its own book. Still, it should just work either way...

**Comment by mhosken** [comment]
Are we sure that the cause of your problems is the inclusion of end of book decoration. Let's not presume the cause wrongly. Currently, for this project, you can't produce any colophon, with or without end of book decoration. Am I correct? If so, and given Mark's inability to recreate the problem, we probably have to look at something about your configuration rather than jumping to conclusions.

**Comment by davidc86** [comment]
If I'm careful to remove several of the \b lines to make sure it fits on one page, then it will print on the next page IFF there is no end of book decoration. If I turn on the end of book decoration, the colophon won't print.

Yes, I actually have a fancy FRT for the entire Bible, but whenever I want to print just ONE book, I need to create a special FRT for that book. And up till now those FRT books failed to print in PTXprint. (I haven't tested them recently. I should try again.) 

But for the sake of testing, I was pushing the limits of the colophon, because that is what some users will do. So, ideally, the program will fail gracefully for outlying cases like the colophon is too large, or won't fit on the page if there is end of book decorations or a page break before it, etc. I've pushed those cases and am reporting the errors I'm seeing. I'm not changing anything in the book except the turning on or off the decoration, turning on or off colophon, and its page break switch. (Oh, I did make the fonts factor smaller than 1 so it would fit better on the page. But then all the tests were just those switches.)

**Comment by davidc86** [comment]
v1.5.14.4
Woohoo, we have a winner!
![image](https://user-images.githubusercontent.com/65363206/109179816-47c74080-7758-11eb-9d9b-079d9bbe18b7.png)
![image](https://user-images.githubusercontent.com/65363206/109179994-71806780-7758-11eb-8d7f-2e4fcc58e770.png)

**Comment by davidc86** [comment]
I not prints the colophon with or without the decoration.
