### ISSUE TITLE
Final footnote in book displays too high

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#409]
If a footnote/xref occurs on the final page of a book, the footnote area displays too high up on the page. My typing teacher in high school said footnotes should always be measured up from the bottom of the page, not down from the text.

![image](https://user-images.githubusercontent.com/65363206/108868277-0a31ae80-75c4-11eb-8f4f-879e19486e36.png)

It looks rather funny/odd this way. I don't know if this is due to the end of book decoration or not. But it doesn't look right, right?

**Comment by davidc86** [comment]
Note: if no end of book decoration is included, the footnote on the last page looks even weirder (to me).

![image](https://user-images.githubusercontent.com/65363206/108869674-6812c600-75c5-11eb-894b-f04c3556e42d.png)

Maybe some prefer that? I don't know. To me, it looks messed up.

**Comment by markpenny** [comment]
AFAIK it is standard practice to bring the footnotes up for the LAST page in a book. One of the reasons for this is so that you can start the next book on the same page, but AFTER the previous book's footnotes. 

However, I agree that if/when there is an explicit end-of-book decorator, it makes it look strange. So maybe this needs to be an option, or perhaps we just push the Footnote to the bottom of the page IF there is an end of book decorator.

I'd be interested in what @jeffheath-sil thinks about this issue.

**Comment by jeffheath-sil** [comment]
On other pages, the footnotes are always at the bottom of the page, even if there is some big title or footnote that gets forced to the next page (i.e. leaving a large blank hole on the previous page with the footnote). So it seems to me that the "norm" should be to put the footnote at the bottom of the page.

If you have checked the option "Begin Next Book on Last Page of Previous Book", that is where I think the issue comes up. Do you squeeze in the footnote before the beginning of the next book? Or is it possible to put it at the bottom of the page anyway (in other words, it would appear after the start of the next book). In my mind, this second option is more natural anyway - even if a new book starts, the footnote always goes at the bottom of the page. Isn't that where you are supposed to look for "foot"-notes?!

**Comment by mhosken** [comment]
Under the colophon as well?

**Comment by jeffheath-sil** [comment]
We don’t usually use the colophon, so I probably am not the right person to respond to that question... But my gut feel is that the footnotes should even go below the colophon. Our footnotes tend to use a fairly small font, and under that line for the notes, so they are kind of tucked away there at the bottom of the page. It seems like the colophon could appear above that and still look decent. But again, you should probably ask some people that actually use colophons to see what they think.

**Comment by davidc86** [comment]
Books that use a colophon of this sort are often children's books where the copyright "page" is actually just a boxed bit of text on the back cover. Such books don't use footnotes. 

Another place where I've seen a "colophon" is in Wired magazine, and it is a narrow column off to the far right side where the editors and staff of that issue put various bits of "what helped us get this issue out", along with the "copyright" blurb, their mailing address, legal verbiage, and other pertinent information. Footnotes don't happen in Wired magazine either.  

So maybe "colophons" and "footnotes" don't really go together? Or maybe a colophon should always be relegated to a blank page or back cover?

**Comment by markpenny** [comment]
The decision for now (until someone can authoritatively tell us to do something different) is:
a) If there is a footnote and colophon on the final page, then the footnote will appear just under the text, and the colophon will be at the bottom of the page.
b) If there is no colophon, then the footnotes on the final page will drop/sink to the bottom (or foot!) of the page.
c) If the colophon is forced onto the next page, then the footnotes will also stay at the bottom of the page.

This should be working in ver 1.5.18

**Comment by davidc86** [comment]
These design decisions look great to me!

**Comment by davidc86** [comment]
Perfect! Looks very nice with or without the end of book decoration.
