### ISSUE TITLE
v1.6 Picture captions are not refreshed from Paratext USFM files

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#435]
I was caught out that the picture captions are not automatically refreshed from the originating USFM files in Paratext.

I realize this happens because after careful tweaking of all the pictures' sizes, and positions, and anchor references etc. we don't want PTXprint to revert those specifications back to what is in Paratext. 

BUT, the caption is TEXT, and if we make a correction in Paratext for a misspelled caption, or change the orthography in some way, I had assumed it would be updated in the picture list. That was apparently a bad assumption.

Might it be possible to have ONLY captions be updated automatically, or maybe make it optionally ON? (But other specs refresh optionally OFF)

I can see where if Captions are not refreshed, it could leave the picture list from earlier publications "stale" in regards to orthography and spelling decisions, when they are next printed or combined with other books in larger publications. (As each book basically starts on a new page, all earlier picture specs (size/location) could remain unchanged in larger publications.) It will be very tedious to go through and verify each caption whenever a new, larger publication is going to be formatted.)

**Comment by markpenny** [comment]
> the caption is TEXT, and if we make a correction in Paratext for a misspelled caption, or change the orthography in some way, I had assumed it would be updated in the picture list

I agree - we need a simple way for the user to update the captions (whilst leaving everything else intact). My best guess would be to have a [Refresh Captions] kind of button, rather than confuse it with [Generate...] which does something far more dangerous! I don't yet know how hard this will be to pull off, but we can put it on the enhancement list to be done at some point in the future.

**Comment by davidg-sil** [comment]
Probably the best 'key' to use to somewhat-uniquely identify the picture will be the image file name + reference (not anchor point).
At least, that'll work until someone decides to replace the image with, say, a coloured version, but still expects the same functionality.
At *that* point, there'd need to be some kind of internal database of original PT-lines, lookups in hg, and a logic-process looking something like this:
* PTXprint doesn't recognise an image line from its internal database.
* hg tells us that the new image line retrieved today used to such and such,
* That removed line corresponds to '*this* image line retrieved from paratext on X date', when it was mapped to internal ID number 1a2bc3; 
* Therefore the paratext image line for image ID 1a2bc3 is now .... and the caption is now "They brought her his head on a plate"
* Therefore the caption in the piclist ought to be "They brought her his head on a plate" instead of "They served her his head on a plate"

**Comment by markpenny** [comment]
@davidc86 - This feature has now been added. It will be in 2.0.6 or later whenever that is released.
Note:
a) that it ONLY works one way (i.e. Paratext -> PTXprint and not the other way) - so if you have only changed a caption in PTXprint, it might get overwritten by the old/new version from Paratext
b) There is no way of telling it to only update certain books/pictures. It does all the pictures in the PicList.
c) There's no confirmation dialog - it just does it and overwrites captions and refs (but not the anchor, or size or position).
d) It is subtle, but in line with other similar "refresh" buttons scattered around in the UI

![image](https://user-images.githubusercontent.com/12962708/140695485-ba62556a-a431-4914-a6ab-a2006046f302.png)

**Comment by markpenny** [comment]
This has been fixed in 2.0.11 so that both captions L and R in diglots get updated.
