### ISSUE TITLE
Unknown error printing FRT that passes basic checks

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#436]
[AAAP-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/6213536/AAAP-DefaultPTXprintArchive.zip)

**Comment by sewhite** [comment]
FRT has images (figures) in it. Is that a problem?

**Comment by davidg-sil** [comment]
![image](https://user-images.githubusercontent.com/58848232/112848084-5df65280-90b0-11eb-9bf4-c4f736140eab.png)
While PTXprint itself couldn't spot the error,  the log file gives a couple of big hints, if you can read it. 
* Log line 334: It's finished reading `ptx2pdf.sty` that it started on line 332 and is now reading stylesheet `custom.sty`
* Log line 335: It understood the definitions for `\grk` `\tgrk` and `\efm`  - the message only triggers if the ```\TextProperties``` definition is met, so don't expect it to  show every entry.
* Log line 336: It met a "control sequence" - i.e. a USFM code or similar command that  wasn't defined
* Log line 337: That line is ```\Mrker```

Knowing that style sheets have ```\Marker``` in them, I had a look, and sure enough there was a ```\Mrker test``` where I'd expect ```\Marker test``` The following line says ```\TextProp character``` which might be clear enough to a human but the code expects ```\TextProperties```, so that throws an error unless I fix that too.

After that, the `XeTeX` code works happily, but python is struggling.

**Comment by davidg-sil** [comment]
```
Please send to: ptxprint_support@sil.org

Traceback (most recent call last):
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/gtkview.py", line 760, in onOK
    self.callback(self)
  File "/home/david/src/ptx2pdf/python/scripts/ptxprint", line 162, in doit
    runjob.doit(noview=noview)
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/runjob.py", line 231, in doit
    self.texfiles += sum((self.dojob(j, info) for j in joblist), [])
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/runjob.py", line 231, in <genexpr>
    self.texfiles += sum((self.dojob(j, info) for j in joblist), [])
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/runjob.py", line 369, in dojob
    res = self.sharedjob(jobs, info)
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/runjob.py", line 469, in sharedjob
    texfiledat = info.asTex(filedir=self.tmpdir, jobname=outfname.replace(".tex", ""), extra=extra)
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/texmodel.py", line 580, in asTex
    self.dict['document/imageCopyrights'] = self.generateImageCopyrightText() \
  File "/home/david/src/ptx2pdf/python/lib/ptxprint/texmodel.py", line 1205, in generateImageCopyrightText
    artistWithMost = max([a for a in artpgs if a != 'zz'], key=lambda x: len(set(artpgs[x])))
ValueError: max() arg is an empty sequence

<class 'ValueError'>: max() arg is an empty sequence
```
What I see is a 4 step process involving 3 sub-optimal things: 
1. The test file provides no copyright data, which is a user-issue but understandable for a test file.
2.  Python is not removing the images from the `.usfm` file, although it will generate a `.piclist` entry for the file. 
3. The first run produces a `.picpages` file, that has no copyright data.
4. The python code is trying to see which artist  of the list `(empty)` provided the highest number of pictures, and getting miserable. (Why doesn't it count `(empty)` as doing all 3?)

**Comment by sewhite** [comment]
After fixing the errors in custom.sty, I get a PDF of the FRT book. But the images are not included, even after I add copyright info for each one. Attaching the updated archive. 

[AAAP-DefaultPTXprintArchive2.zip](https://github.com/sillsdev/ptx2pdf/files/6224260/AAAP-DefaultPTXprintArchive2.zip)

**Comment by davidg-sil** [comment]
When I load your zip and click print, I get this:
![image](https://user-images.githubusercontent.com/58848232/112946080-c8090900-913d-11eb-892b-2db1f9506944.png)
When I go to the pictures tab and select 'include pictures', I get this:
![image](https://user-images.githubusercontent.com/58848232/112946761-93498180-913e-11eb-9a47-b9bb5b8532e7.png)
As you see, it's trying to include two images but can't find them, as when PTXprint makes the archive, if 'include pictures' is not ticked, it does not put any pictures in the zip file.
Note that at this point the piclist is still empty. 

The 'master' usfm file looks like this:
```
\id FRT - Advanced Aardvaare Project
\mt2 Preface
\periph Front Page
\pc \fig Testation Inc|fulani translation.JPG|col|||Timeling 1|1.0\fig*
\pc \fig |Happy.jpg|span||Testation Inc|Timeling 2|1.0\fig*
\pc \fig |Conovers Bainbridge Island edited.jpg|span|||Timeling3 |1.0\fig*pt
```

I generate the piclist and now the processed usfm file (in PrintDrafts) now looks like this:
```
\id FRT ‑ Advanced Aardvaare Project
\mt2 Preface
\periph Front Page
\pc  \zfiga|0\*
\pc \fig|Happy.jpg|span||Testation Inc|Timeling 2|1.0\fig*
\pc \fig|Conovers Bainbridge Island edited.jpg|span|||Timeling3 |1.0\fig*pt
```
Perhaps @mhosken or @markpenny  can comment on why only the first image is being stripped from the processed USFM.  I altered the size of the first image and now the piclist in the `PrintDrafts` folder looks like this:
```
FRT .0 Testation Inc|size="span" pgpos="t" scale="0.450"
FRT .1 |size="span" pgpos="b"
FRT .2 |size="span" pgpos="b"
```

Which sadly skips the filenames entirely. I'm not sure why. Maybe because the files are missing? But I don't have 'Omit missing pictures' ticked, so this seems likely to be a bug. Hopefully if the images are available the piclist will not be broken.

**Comment by sewhite** [comment]
I had neglected to tell PTXPrint to include figures. When I do, I still get the same result you did, the pictures are not in the PDF, just a frame for the second or third one. I tried choosing a different image for the first one, but it still seems to vanish, not showing even the frame for it. 
Attaching new archive. When I look at this archive, I don't see the image files in it, so I'll attach them in another zip file.


[AAAP-DefaultPTXprintArchive3.zip](https://github.com/sillsdev/ptx2pdf/files/6230225/AAAP-DefaultPTXprintArchive3.zip)
[figures.zip](https://github.com/sillsdev/ptx2pdf/files/6230233/figures.zip)

**Comment by mhosken** [comment]
Could you click generate, on the pictures page and then try again; archive
etc.

GB,
Martin

**Comment by sewhite** [comment]
Martin, when I click Generate, nothing seems to happen. If I then print, I get a PDF that cannot be opened. 

[ptxprint-Default-FRTAAAP.pdf](https://github.com/sillsdev/ptx2pdf/files/6231452/ptxprint-Default-FRTAAAP.pdf)
[AAAP-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/6231453/AAAP-DefaultPTXprintArchive.zip)

**Comment by markpenny** [comment]
@sewhite Just checking to see if this issue can be closed now, or whether it is still a problem.

**Comment by sewhite** [comment]
Yes, it can be closed. Version 1.8 prints my FRT with three illustrations
without problems.
Steve White
International Language Technology Consultant
