### ISSUE TITLE
Doesn´t Print and Progress bar does not advance

### ISSUE THREAD

**Issue by jpgotopo** [sillsdev/ptx2pdf#437]
As much as I change the settings, the book does not print, the progress bar is stopped and nothing prints. I check the destination folder, there are the files created, but they cannot be opened.

![image](https://user-images.githubusercontent.com/27728874/113966627-0dd86800-97f5-11eb-8a7c-c9e3f92440dc.png)

**Comment by mhosken** [comment]
Perhaps this is due to something causing an exception in the xetex running subthread? For now a restart should clear the logjam. And since it will have saved your config you can restart and hit print immediately.

If that fails, then you may have hit print too quickly and haven't given ptxprint time to load everything, So try again and wait 20s before hitting print. If that is the case, please let us know. All more data on what is a tricky problem to track down.

**Comment by markpenny** [comment]
> the book does not print,

Sorry to see this. Are you able to Close and Restart? Obviously something unexpected has happened, but it is rare that it should produce a PDF file that is un-openable. If you can't get it to work, please try "Create Archive..." on the Help page and post the .zip file here, or send it to the support email address mentioned in the Tooltip on that page. Thanks.

**Comment by markpenny** [comment]
@jpgotopo - Have you been able to progress any further, or are you still stuck at this issue?

**Comment by jpgotopo** [comment]
Hi, I still have the same problem, You do not want to print, the printing progress bar is stopped, and the printing never appears. I don't know if it's a configuration issue, or will you have to see the Paratext permissions for the project?

**Comment by jpgotopo** [comment]
> @jpgotopo - Have you been able to progress any further, or are you still stuck at this issue?

Hi, I still have the same problem, You do not want to print, the printing progress bar is stopped, and the printing never appears. I don't know if it's a configuration issue, or will you have to see the Paratext permissions for the project?

**Comment by markpenny** [comment]
No, this is unrelated to Paratext permissions. Could you try deleting the "Default" configuration which should erase any strange settings. Then make sure the Font has been set on the Font+Script page. Try a single book and let me know how it goes. Otherwise could you try: "Create Archive" using the button on the Help page (and send it to ptxprint_support@sil.org).  If that fails, then we would need to look at your screen through Zoom, or Skype.

**Comment by jpgotopo** [comment]
Hi Mark, I have sent the email with the created file attached as you
suggested to the respective email.

Thanks!

**Comment by markpenny** [comment]
Just an update on this issue. Both Phil L and @markpenny have worked online with @jpgotopo to try and resolve this issue. But we have been unsuccessful. The error that we're seeing is that it can't find paratext2.tex even though it is properly installed in the correct location. So far we have not come across this issue.
The Archive .ZIP file works quite happily on other machines - so we know that PTXprint is doing the right thing. But XeTeX just can't find the .tex macros it needs. It could be related to paths being hijacked by other software installations. Phil L was going to investigate further.
@jpgotopo decided to try using PTXprint on a different machine to see if it works there.
I don't think there is anything that the developers need to do - other than learn from the experience, and wait for news on how it is eventually solved.
