### ISSUE TITLE
Vertical Space Separating Footnotes and XRefs - not working

### ISSUE THREAD

**Issue by klassenjm** [sillsdev/ptx2pdf#457]
Hi,

I'm working with PTXPrint 1.8. I would like some space separating the footnote block / paragraph from the XRef block.

On the Notes+XRefs tab I see the option to configure a "Vertical Space Separating Footnotes and XRefs". I have tried different values in this field. There is no change in the output.

I have also tried to edit the Style for `\x ...\x*` to apply a SpaceBefore factor. This also has no effect.

There is an archive [here](https://www.dropbox.com/s/37t2v0zdc4icrgn/GNTPA-60-2Col-2FontPTXprintArchive.zip?dl=0).

Jeff

**Comment by markpenny** [comment]
Hi @klassenjm, Yes, I can confirm that there has been a regression here. We'll look into it and get it fixed for the next minor release.
@mhosken or @davidg-sil it looks like the macros are now ignoring the \InterNoteSpace=6.0pt setting in the .tex file.

And I'm not sure we've tried using the SpaceBefore option on ``\x ...\x*`` but there's no real reason that it shouldn't. So that gives us a couple of things to fix. Thanks for finding these bugs.

**Comment by klassenjm** [comment]
Tried 1.8.3. This issue is fixed for me.
