### ISSUE TITLE
Chapter numbers superimposed on body text of \nb paragraphs

### ISSUE THREAD

**Issue by livingfield** [sillsdev/ptx2pdf#460]
I'm seeing the same issue #19 which was "fixed" a year ago, though that was a Latin-script project and this project is Khmer script, so I don't know if it might stem from a different issue. Sometimes the chapter number for \nb paragraphs is printed superimposed on top of the body text. At other times it prints correctly. I've attached a PDF showing the output of all  \nb in this job.
[nb_problem.pdf](https://github.com/sillsdev/ptx2pdf/files/6611179/nb_problem.pdf)

**Comment by markpenny** [comment]
@livingfield Thanks for reporting this. Obviously there has either been a regression, OR the circumstances are different enough that (new) bugs are surfacing in a different ways. There are currently some limitations surrounding the use of \nb **in long paragraphs** that go for longer than 2 columns of text. **What would really help us is if you can use the "Create Archive" button on the Help tab to create a .zip archive. Please send that to the ptxprint_support (at) sil.org address so that we can have some good test data to work with.**

BTW - If you are desperate for a quick work-around, you can always change the \nb markers to \m (through a PrintDraftChanges.txt rule - see Advanced tab) so that you can at least get away from the chapter numbers overwriting the text.

`"\\nb " > "\\m "`

So instead of getting a perfectly formatted continuous (no-break) paragraph like this:

![image](https://user-images.githubusercontent.com/12962708/121149783-0ede5200-c897-11eb-9c77-24e5d2984997.png)

You may end up with a broken paragraph like this (or worse), but at least the chapter numbers won't be clobbering the text:

![image](https://user-images.githubusercontent.com/12962708/121149890-26b5d600-c897-11eb-8eee-cfdbc87e9323.png)

**Comment by markpenny** [comment]
@davidg-sil I am assuming that this is related to #335 and I'm hoping both are fixed now. Could you confirm, please.

**Comment by davidg-sil** [comment]
I believe that the issues causing this problem have been addressed in the current version in git, yes. @livingfield, when the next version comes out could you please check that all is working properly and either report that there's still a problem or close the issue? Thanks!

**Comment by livingfield** [comment]
V1.8.9.1 fixed all \nb except this one which was right after a page boundary. The chapter number should be one line lower, and then it would be perfect. PTXprint is incorrectly placing the chapter number one line higher than it should be.
![Screen Shot 2021-06-25 at 10 36 06 AM](https://user-images.githubusercontent.com/15900199/123444384-d764ea80-d5a4-11eb-8eff-6b5a8e5ed769.png)

**Comment by markpenny** [comment]
@livingfield Thanks for sending the archive. We'll look into it and hopefully rectify it before 1.9 is released.

**Comment by davidg-sil** [comment]
Oh yuck.  Yes, that's  a horrible place for it to raise the chapter number like that. Hopefully, it ought to be possible to prevent a page-break in the line before a raised chapter number, but, while you want me to not let it raise the chapter number, I can't (mustn't) do that for every case..

So...  some explanation of what's going on here. One of the inherent ways that the TeX  layout engine works is that you tell it how wide the lines of a paragraph  ought to be, and what text to put there and then it finds the 'optimal'  line-breaks. according to various globally applied rules. Normally this works beautifully, but when the paragraph shape  depends on the contents, as it does with placing cutouts for mid-paragraph chapter numbers,  you can get some nasty loops. 

Imagine if the long word at the top of p,444 wasn't part of the text (i.e. the start of the verse ended up earlier on the line). If the cutout currently starts in  line 32 of the paragraph (I'm typing this on my tablet, so can't count), then the start of verse 1 will be on line 33,   But,  if the cutout  were to start on line  33, then the  line-breaker might decide put verse 1 on line 32. 

Therefore, someone wiser than me introduced the freedom for the code to 'raise' the chapter number one line. 

@mhosken  can hopefully correct me if I'm wrong, but I don't think there is any way we can tell it that moving which line verse 1 is on between one run and another is a very bad idea, and so  we're stuck with TeX's idea of optimal line-breaks.

So, I think in your case it got 2 things wrong: 1) it accepted what ought to be a fall-back solution too easily,  but  it needs to be *allowed* to accept  less-than ideal chapter number positions *eventually* to escape that kind of loop. I think that probably means better 'accounting' or something to only allow adjustments to   2) it  split the page in the wrong place.

**Comment by mhosken** [comment]
Or to put it another way. The TeX macros work out where the nb cutout should be before page breaking and so the position of the cutout is set independently of page breaking. It's hard enough getting cutouts right what with multiple columns and pages and things shuffling around. So have it handle a page break in the middle of the cutout is just beyond us at the moment. Consider it a bad page break, much like an unsightly gap at the bottom of a page, and move on. Sorry. Maybe one day we'll be inspired and fix this. But neither of us see a way out at the moment.

**Comment by davidg-sil** [comment]
Slight correction to @mhosken, I think that at the moment there's a `\vadjust {penalty 1000} ` in the code, that the `\nb` triggers. We can probably check if the number is raised and make it a `\vadjust pre ` if  it is.  That ought to stop this from happening to chapter numbers, at least. 
I'm still not healthy enough to get out of bed to do it though.

Regarding imperfect results of the hysteresis/slop, I also think there *could* be some kind of 'runs this has been stable' counter added to the `.delayed` file, and then if the user is requesting 'as perfect automatic layout as as possible' there could be some clever logic to  permit slop on the first unstable value and not otherwise.  It's going to take thouhgt and make for more repeat-runs, of course, and neither of these are going to solve every break in a cutout.

**Comment by livingfield** [comment]
Thanks for the explanations. In this particular case I got acceptable output with AdjList. It sounds like this will remain the best fix for a while.
