### ISSUE TITLE
Top margin settings in dialog very confusing

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#461]
My immediate reaction when I went here after noticing the rule line overlapped with the header text on my printout, was that the two red variables (Top margin to text and  Header to Text Space) were showing me what the problem was, so clicking the gear button would fix the problem. It did not.

My second thought was I needed to increase the distance between the top of the page and the horizontal rule. But there is no single way to do that, I have to set the distance from the rule to the text body. This was not obvious. 

I'd suggest splitting off the rule dimension into a different part of the dialog, and I'd also suggest not using red and orange within the same part of the dialog as contrasting colors. They look the same to me, with these thin letters and arrows.)

My proposal for a clearer dialog:

![ptxprint-proposedmargindialog](https://user-images.githubusercontent.com/16904461/122252642-857fde80-ce99-11eb-8078-e8c0d9429089.png)

**Comment by markpenny** [comment]
Hi Steve, thanks for walking me through your thought process on this dialog. I agree that it is pretty "tight", and certainly all these values are confusing. However, we are intentionally trying to constrain how "tall" the UI gets, because most/many of your users don't have FullHD screens. For that reason, I can't really "explode it out" as you have proposed. I have packed a lot onto the layout tab, but it needs to stay together as all of these values interact with each other. 
Sorry about the red/orange. I'll have a think about a different primary color, but purple is already used for the Side Margin width.

**Comment by markpenny** [comment]
@sewhite Here are some ideas to (hopefully) make it a bit more obvious (even without changing any of the graphics):

![image](https://user-images.githubusercontent.com/12962708/122375152-14364d80-cfb7-11eb-9264-0a69f641bcea.png)

and if the Horizontal rule is enabled then the additional green setting shows up, along with the updated graphic showing the line.

![image](https://user-images.githubusercontent.com/12962708/122375283-2fa15880-cfb7-11eb-9822-bd396980d53a.png)

Is that an improvement for you?

**Comment by davidg-sil** [comment]
Maybe swap purple and orange, for higher contrast on the verticals?
Also, I'm just looking at the wording. Since the orange says 'Text space' and it's referring to the same thing at the bottom as the red, should that read 'Header to Text' or should the red's '... margin to text'  read '.. margin to Text Space'? Oh, and green uses a third term... So, 'Text Space', 'Body Text' or 'Text'?

**Comment by sewhite** [comment]
Mark, I think your proposal is a step in the right direction. Here is another suggestion I worked up that I think would be clearer still: 
Same dimensions as the existing dialog. I added a note to say you would set the top of page to text area then the spacing of the header above the text area, and this determines the distance from top of page to the header. I also moved the arrows closer to the variable they referred to. Like you, I also think the box for the rule under header should be below the top margin settings. I also reinstated the horizonal dividing line between all the top margin settings and the bottom margin settings, which could be a problem with your proposal. 

![image](https://user-images.githubusercontent.com/16904461/122470696-5b5b1900-cf8c-11eb-9227-d0d3e2eb0d0e.png)

**Comment by markpenny** [comment]
Okay, here's my (final?) take on this subject with the graphics re-done:
![image](https://user-images.githubusercontent.com/12962708/122716971-10f4d780-d2bf-11eb-9043-b208d51e8cdd.png)

and when the Horizontal Rule option is checked:
![image](https://user-images.githubusercontent.com/12962708/122717019-21a54d80-d2bf-11eb-9fb4-3eed5ffa4ce4.png)

Note: If we go ahead with this layout and **updated label wording**, then I will also need to update some of the tooltips to match.
@davidg-sil AND @sewhite  - is this OK and more consistent for you now? Steve, earlier you wrote:
_"I added a note to say you would set the top of page to text area then the spacing of the header above the text area, and this determines the distance from top of page to the header."_
All of that information can be found in the Tooltip. I get the feeling that no one is reading the tooltips :-( which is a shame because *that* is where the documentation is.

**Comment by sewhite** [comment]
I think this version looks good.

You mentioned the tooltips. I think I did look at those but felt bogged down by a few more details.
![image](https://user-images.githubusercontent.com/16904461/123111211-ba94af80-d40a-11eb-92d9-b65398b28c24.png)
Why does the first line start a little below where the main text area starts? Do you mean the distance between the top of the tall letters and the first turquoise or teal line in the graphic? I guess the second paragraph explains this but I had to read it over a couple of times."

Maybe something briefer would be clearer: 

"The distance (mm) from the top of the page to the top if the main text area. The base of the first line of text is one base line space below the top of the text area.
