### ISSUE TITLE
diglot: RTL problems

### ISSUE THREAD

**Issue by mhosken** [sillsdev/ptx2pdf#466]
In some paragraphs, the last line of the paragraph has the word order reversed (the text within the word is correct but the words come in the wrong order).

For example, "this is Arabic" would become "Arabic is this" and not "cibarA si siht"

**Comment by davidg-sil** [comment]
I've found a place where `\endR` was used in the footnote code. 
Testing indicates that `\endR` almost certainly should not be used, except where it is an RTL inclusion in otherwise LTR text.

Current locations where `\endR` is used are:
* `ptx-references.tex` the header/footer. This is probably appropriate.
* `ptx-para-style.tex` in macro arguments to `\leftline` / `\rightline` (which put `\hss` after and before the argument respectively and pass  it on to  `\line`.

These uses all seem reasonable to me.
