### ISSUE TITLE
Adj list in Bible Module

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#471]
Is it possible to create an Adj List file for Bible Modules? If so, what is the syntax for referencing different paragraphs?

**Comment by mhosken** [comment]
Yes, but it's complicated. I recommend getting used to using Adjlist files with normal scripture books first.

One has to think in terms of the flattened module. Firstly references. The adjlist uses book chapter verse and paragraph numbers. The book is always the 3 letter code after the \id line in the module (MOD). The chapter and verse is set by whatever has been pulled in. If no verse is set, then it is 0. The paragraph number starts from 1, containing the C.V reference and increments from there (so the paragraph after is 2, etc.)

As an example, all text before the first chapter number will be MOD 0.0 +0[2], etc. If you don't pull in \c lines then you can use the verse numbers MOD 0.3. But you need to bear in mind that a line in an adjlist is used the first time it matches the current location in the file. Thus if you have two passages and no \c lines then MOD 0.3 will match the first \v even if you want to refer to a later one. To do that, first put in a blank change for the first MOD 0.3 +0 to have it used and then put in another MOD 0.3 +1 for the next occurrence.

Adjlists are a bit brittle. If you get them wrong, and a reference doesn't match. The macros will not look any further ahead and so all later adjustments will not happen.

If you get stuck, you can using the macros' tracing mechanism to get some tracing help in the log file. Add

```
\tracing{j}
```

to your ptxprint-mods.tex (and enable it) and the log file will show every paragraph and what it was trying to match against from the adjlist file. You should be able to dig yourself out of most holes from that.

**Comment by mnjames** [comment]
Thank you for the detailed explanation. I thought I had a good idea how to work with the Adjlist in regular books, but have just done a little experimenting to verify that it works as I expected in general.

I've been using the XXA, XXB, etc books because when I try to print Bible Modules directly from inside ptxprint, I get an error like this: <img src="https://user-images.githubusercontent.com/30174022/127225514-e3f7838a-a344-4522-851e-9b5e06509579.png" width=50% height=50%>
Is this a bug, and if so should I write up a separate issue? I wonder if it has to do with the RTL markers that Paratext automatically adds in.

I think I have things working, but still have some questions.
- Does the Generate button not work on XXA, XXB, etc books?
- My XXB file had a \c 1 in it, but didn't have any verses in it. And the `\inc f s` line didn't include `v`. After a lot of experimentation, I discovered that adding a \v 1 line into the spec file made the Adjlist start working. Is that to be expected?
- Reading the trace log file lead me to this syntax, which works: `XXB .1 +1[3]`. Why is there no chapter number (and adding "0" breaks things)?
- Since I'm not importing chapter\verse references from the different references I'm bringing in, will I need to number every paragraph through the entire file (into the hundreds)? If so, any recommendations on how to find the paragraph I'm looking for. Anything I can type into the module spec to trace which paragraph it occurs in, just to get the paragraph number for my help?

**Comment by davidg-sil** [comment]
The following works and probably gets you what you want. It's not very *pretty* but I've tested it and it works...

At suitable points in your module file, put in some figure-anchor milestones like this:
```
\zfiga|A.ABRAHAM\*
```
The dot is required, as is the bit after the `|` being all caps. Normally (e.g. when used for figures) these rules don't apply, but they do for adjust lists. This requirement for all-caps is a pain, means you can't instantly use key-term entries as adjust-list 'anchor points' and I expect it will be fixed in the near future.


In the adjust list, the relevant entry is now:
```
XXA A.ABRAHAM +1[1]
```
or whatever.

As with verse numbers, this explicit milestone resets the paragraph counter, but (confusingly) there are some differences between counting paragraphs, and where things get used. So e.g. if the flattened module looks like this:
```
\p And they went into the land of Nod, east of Eden.
\zfiga|A.ABRAHAM\*
\mt  A man called Abram starts to obey God
\s The family leave Ur
\p This is  what happened to Terah and his family.\f + \ft Traditionally, the generations of Terah\f* 
Terah had sons  Abram, Nahor, and Haran; and Haran had a son Lot. And Haran died before his
father Terah in the land of his birth, in Ur of the Caldeans.
```
Then, looking at the log file, it seems that the `\s` is paragraph 2 for adjust lists, (but paragraph **3** for triggers), and unlike with verse numbers, there is at present no way to adjust the paragraph that the `\zfiga` milestone is found in, at least, not while using it as a reference.
