### ISSUE TITLE
Callers not showing in text or notes for cross-references

### ISSUE THREAD

**Issue by toddlprice** [sillsdev/ptx2pdf#474]
Regardless of what variations I try for callers for cross-references, they do not show up in the pdf. See screen snips attached.

![image](https://user-images.githubusercontent.com/16920146/128371606-c63dea45-6758-4b04-80b0-4239243fd5fe.png)

![image](https://user-images.githubusercontent.com/16920146/128371924-13e2e181-a7de-4e3f-bfee-3c356d309aa4.png)

![image](https://user-images.githubusercontent.com/16920146/128372045-f1af4719-4a60-4176-ade6-4517691509e7.png)

![image](https://user-images.githubusercontent.com/16920146/128372349-037c59a2-9b51-48e1-9403-d005aa82ba93.png)

**Comment by mhosken** [comment]
Please send an archive (help/create archive) and we'll dig into it.

**Comment by toddlprice** [comment]
[Bayash-SeptemberPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/6939882/Bayash-SeptemberPTXprintArchive.zip)

**Comment by markpenny** [comment]
Hi @toddlprice - this one is doing exactly what you told it to do in Paratext:
`\x - \xo 1,55 \xt Gal 3,16\x*
`
The hyphen/minus **-** sign after the \x marker instructs that the there should be **no** caller.
So you have 2 choices: Either (i) change the - to a + in Paratext so that the caller will always appear, regardless of which software you use to print or publish your text in future, or (ii) use the "override" setting in PTXprint which is shown below:
![image](https://user-images.githubusercontent.com/12962708/128428645-adad20e5-fb40-4200-a9ee-4ef1d68e138d.png)

This will then ensure that the settings specified in PTXprint will be applied (thus overriding the minus - in the USFM) resulting in a caller being shown:
![image](https://user-images.githubusercontent.com/12962708/128428808-56aaad56-5df4-4a2b-80c8-5f0503fbda8a.png)

I hope that makes sense now...

**Comment by toddlprice** [comment]
Thank you. I didn't realize that my settings in PT were not to show cross references. Thanks for your help!
