### ISSUE TITLE
v1.9.3 odd empty line at bottom of page

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#489]
This might be niggly, but I don't see any reason for this odd blank line on the right-hand page. The two pages are lined up nicely, but the right-hand page pushes the last line onto the next page for no apparent reason. (The last line has no footnotes and no cross-references, and is only a few words long.)

![image](https://user-images.githubusercontent.com/65363206/131507249-ae9dd60a-3157-4bbe-9f5a-e13c0c21522a.png)

**Comment by markpenny** [comment]
Could you show us a screen-shot of the TOP of the next page, please. Or send us an archive.

**Comment by mhosken** [comment]
My guesstimate with just the information we have is that there isn't actually room for another line above the footnote. I'm not sure why, but the very bottom of that second page looks higher than the first and the footnote line is higher too, which is odd in itself.

**Comment by davidc86** [comment]
Here is the next page: 

![image](https://user-images.githubusercontent.com/65363206/131906069-923285ff-f6b8-4b98-b929-a431800df624.png)

NOTE: there is no footnote or cross-reference associated with that last bit of text at the top. I've set my PTXprint configuration to allow single lines to sit by themselves, so that isn't a problem. But it just looks like that last line should fit on the previous page when compared to the previous page. (Unless the chapter number somehow bumps something?)

I can send an archive too.

**Comment by davidc86** [comment]
[Uploading SLU-SelaruNewPublicationPTXprintArchive1COR.zip…]()

**Comment by davidc86** [comment]
[SLU-SelaruNewPublicationPTXprintArchive1COR.zip](https://github.com/sillsdev/ptx2pdf/files/7101412/SLU-SelaruNewPublicationPTXprintArchive1COR.zip)

**Comment by davidc86** [comment]
Wow, good catch! I agree with you Mark, that the footnote "box" should assume descenders so the space allotted is consistent regardless of whether the text happens to have descenders in it or not.

**Comment by markpenny** [comment]
Here is what is happening: Due to the left notes having a descender, the entire "notebox" sits slightly higher, so the last line of the main body text ends up unusable (insufficient vertical space).
![image](https://user-images.githubusercontent.com/12962708/132778897-f3969177-2921-4df2-9337-f83fa8d0a65f.png)

I would prefer that all "noteboxes" sit that little bit off the bottom edge so that the footnotes don't change position vertically depending on whether they have a descender or not.
If this is too hard to code in TeX, then could we insert an (invisible) character [maybe a space character???] that descends below the baseline so that it always has that space regardless of whether it is needed?

**Comment by mhosken** [comment]
Do you have advanced/use glyph metrics turned off? Because that might fix
this (but in the opposite direction to what you might expect)

**Comment by mhosken** [comment]
As Mark has shown, one way to help to see what is going on is to turn on gridlines. This often helps to see exactly what lines up with what. And just to reiterate my previous comment: Try turning 'use glyph metrics' off in the advanced tab.
