### ISSUE TITLE
Support for basic Study Bible layout

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#496]
Basic Study Bible layout has been requested, primarily by UBS for teams that are drafting study bibles and need a way of reviewing materials before formal typesetting.

- Two column notes with verse synchronization
- Study notes overflowing onto the next page

Note that this would be a major undertaking, and it is unknown how long it would take to develop this functionality.

**Comment by davidg-sil** [comment]
To remark on how significant an undertaking it would be... 
At present, things like balancing and getting footnotes to not split while not ending up overflowing the the margins (and off the bottom of the page) rely on running a trial-galley multiple times, and then rejecting the page and shrinking the galley if things don't fit. TeX was not written to fully accommodate this 'try that again' approach.

If footnotes split, the left-overs are automatically placed on the next page. There is no easy way we know of to clear the 'this goes on the  next page' list when rejecting a page, so 'left-over' bits end up accumulating from different trials.

**Comment by mhosken** [comment]
We can clear the leftovers by using an output routine that empties box255, especially if we run with holdinginserts=1

**Comment by klassenjm** [comment]
I think it would be worthwhile to discover what kind of text layout would be most useful and necessary for evaluating and reviewing study material. I think knowing this would make it clearer what kinds of effort is needed in PTXprint.

For example:
- I recall that one thing that is helpful for a team working on study material is to have a better visualization of how balanced the spread of study content is across a book or books.
- What kind of layout would be most helpful for a team to use for sharing the study content and inviting comments and review. In this case, the Bible text itself may even be minimized, and the study content become the 'body text' essentially. Perhaps with room to add comments in a wide margin area? Maybe it would only be necessary to show the Bible text for verses which have note content (i.e. the Bible text becomes like a note to the study material). Options of this type. Likely simpler layouts.

I'm willing to explore the needs here with my colleagues and report.

This is not to diminish the need for a complete, printable layout. I'm only wondering what PTXprint could do to empower the study content development process -- especially because of it's accessibility and speed.

**Comment by davidg-sil** [comment]
I see that paratext9.2 has introduced 'bible study additions'. which seem
to be distinct from te main usfm. but nothing about how they are stored,
etc. I presume eventually we will need to interface with the file/database
format.

From the TeX perspective, sidebar  materials can be included via
trigger-files. which provides the ability to pick the right anchor (in a
similar way that picking the right anchor-point  is important for figures),
but perhaps an intermediary file would be appropriate.

  Certainly from the GUI-perspective, I'm assuming that there will need to
be 'anchor' , 'unique description' (equivalent of filename for images), and
'category'.  A separate position might be needed.
 At the moment a `\cat history\cat* for the sidebar uniquely defines the
sidebar position and styling, but probably a way to indicate the page
position without duplicating everything else will be appropriate. e.g.
`\cat history\cat*\zposition |tl\* `  or perhaps `\cat
history|position="tl"\cat*`   ?

Some parameters e.g background image would presumably change though between
something that is page-width vs column width, so despite the convenience of
cascading features, perhaps there is no need for anything beyond `\cat
history-tl\cat*`

**Comment by klassenjm** [comment]
Yes - the 'Study Bible Additions' project type is project in which you can connect / associate various types of additional study content with a base translation. You can connect the study content to specific locations or words/phrases. Paratext manages the associations and content with stand-off markup method (in XML).

This means that the study content projects are not resulting in copies of the base text project (which is what was being done previously) in order to get the study content in the right location in the text. You only maintain one base text.

Paratext presents the Additions project window in a way which looks very much like a normal project. You see the base text and its markup in a lighter shade. You navigate as normal. The base text is un-editable in this Additions project. If you do edit the base text in the base project you see the change appear in the Additions project.

There can be multiple Additions type projects which are associated with a base text.

When you want to publish -- the Additions project has an export utility which lets you generate a "Publication" project. This is a merge of the base text and the currently active Additions. The Publication project is just like the previous Study Bible project type you've been working with -- all USFM. In Paratext it is un-editable. I believe this Publication project would flow through PTXprint as now.
