### ISSUE TITLE
All types of colors show in the PDF, but I can't figure out how to control them

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#50]
All types of text/paragraph colors show in the PDF, but I can't figure out how to control them. 
I have selected both "custom.sty" and "PrintDraft-mods.sty" as per the "recommendations".
 Using these I am able to get some control of some things. But it is not clear what the processing order is (custom.sty --> PrintDraft-mods.sty or visa versa) . No instructions are given for modifying the colors, so I'm not sure what codes to use. And oddly \wj ... \wj* come out BLUE! No idea where that came from. 
For now I've turned off colors, but that's a hack, and if I'd like to read it on a device, color in some places would be an enhancement.
Any clue where to go to get instructions on these two files? (And it might be nice if the "custom.sty" wasn't the exact same name as the "custom.sty" file in the project's main folder--because it is not the same file. How about "PrintDraft-custom.sty", so we know it's related but unique from that file.)

**Comment by markpenny** [comment]
Thanks for all the good feedback David. We've only just added color and it hasn't been tested much at all. I'm guessing that we've got something wrong with the mapping of integers (in the .sty files) to hex codes (in the .tex code) which is translating the colors incorrectly. We'll take a look and fix that.
About the order of stylesheets, there is an order:
![image](https://user-images.githubusercontent.com/12962708/82009301-981f5700-968c-11ea-8b74-6fac1c00269d.png)
So, it starts with the highest level: **usfm**.sty
then it moves to the project-level: **custom**.sty
and on to tweaks that the user may have set in PrintDraft: **PrintDraft-mods**.sty
(And finally there may be additional style tweaks that PTXprint makes in **NestedStyles**.sty
So, yes, there is only ONE custom.sty (not two).
We have recently seen some strange behaviour where the .sty files are being skipped over if something within them wasn't kosher; but we thought that issue was solved.

**Comment by markpenny** [comment]
It appears the the .sty files (which Paratext uses) use a mixture of systems to interpret the colours. As you can see here, Red and Maroon are using RGB(255,0,0) and RGB(128,0,0) respectively, whereas all the other shades are Decimal values of their HEX equivalents. 
![image](https://user-images.githubusercontent.com/12962708/82012277-108a1600-9695-11ea-8624-c963db9a1d60.png)
@mhosken  We'll need to map the RGB-styled numbers to their equivalent HEX codes.

**Comment by davidc86** [comment]
Hi Mark,
Long time no talk, though I hear about you from Bruce Cain from time to time.

This is a great tool btw so don’t think my “issues” anyway detract from the program.

Thanks for that heads-up on the .tex file.
Hmm. So no temp “custom.sty” file eh? Well, that means mine is being skipped. I think maybe PTXprint thinks it isn’t halaal because it may have user-defined markers in it. (Not sure, but maybe.)

So, I’ll need to look at that more.
Thanks,
David

**Comment by mhosken** [comment]
It turns out that Paratext interprets \Color us BGR not RGB, if in decimal. It also supports xRRGGBB hexadecimal (as in x400000 for dark red). So we'll do the same. TeX macros modified accordingly. 

BTW PT has a bug in that it reads \Color as BGR but writes it as RGB integer (if I'm reading the old code correctly). But then I don't know when PT ever writes a .sty file.

**Comment by markpenny** [comment]
@davidc86 Are your colours behaving more predictably now?

**Comment by davidc86** [comment]
Well... words of Jesus are now RED. So that is a plus. But none of my other colors match what I'm seeing in Paratext. So, it would be good if somebody made a pronouncement and made a standard set of controls for color in Paratext and in PTXprint. A friend came up with this list for his custom.sty, and I'm wondering if this is correct for PTXprint?

# Black  \color 0
# Red  \color 255
# Green  \color 65280
# Blue   \color 16711680
# Magenta   \color 16711935
# Cyan   \color 16776960
# White  \color 16777215
# Light Gray   \color 12632256
# Dark Gray  \color 4210752
# Gray  \color 8421504
# Pale Yellow (Pale Yellow) \color 13697023
# Light Yellow  (Light Yellow) \color 8454143
# Yellow  \color 65535
# Lime Green  \color 12639424
# Teal  \color 8421440
# Dark Green  \color 16384
# Maroon  \color 128
# Purple  \color 8388736
# Orange  \color 33023
# Khaki  \color 7051175
# Olive  \color 32896
# Brown  \color 4210816
# Navy  \color 8404992
# Blue gray \color 6576216

But I just tested this list, and "Blue" is NOT \color 16711680 (apparently that is YELLOW!)
So, we need a definitive "cheatsheet", which we can paste at the top of our custom.sty and our PrintDraft-mods.sty file.

**Comment by markpenny** [comment]
Yes, I've been looking at these too. Here's my analysis. Paratext uses the above colours and displays them properly within Paratext itself:
![image](https://user-images.githubusercontent.com/12962708/82485355-f3bc6b00-9af8-11ea-87d5-678fa4285787.png)

But when we try with PTXprint they'rs all over the place except for the short codes 0,128,255 etc.
![image](https://user-images.githubusercontent.com/12962708/82485486-236b7300-9af9-11ea-9ce6-6791eef6fa70.png)

**Comment by davidc86** [comment]
So... some codes work, but many don't. Who has the authority to say, "Enough! We are going to mark color this way." ?

**Comment by markpenny** [comment]
Success! Well done @mhosken 
![image](https://user-images.githubusercontent.com/12962708/82525458-0eb9ca00-9b4f-11ea-8e21-b20a2c51786e.png)
