### ISSUE TITLE
Styled borders / book dividers (e.g based on arranging “vectorian” picture elements)

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#501]
Rather than using PDFs, consider an option to used styled borders and/or book dividers (e.g based on arranging “vectorian” picture elements)

**Comment by mhosken** [comment]
Need to collect info on how people would want to describe this stuff. Are we talking border fonts as well? How do those work in TeX anyway? Some examples would help.

**Comment by davidg-sil** [comment]
Examples of some 'vectorian' picture elements, as pulled in by test code. This isn't ready to merge into the PTXprint  macros, but this is what the issue is discussing.

![image](https://user-images.githubusercontent.com/58848232/133131544-b54f31a7-8801-48cc-8cca-f288da071add.png)
Zoomed in:
![image](https://user-images.githubusercontent.com/58848232/133134162-d6b77910-fa42-4a71-940a-1f3908058725.png)


The test code uses the vector images supplied with pgfornament, but I've reimplemented the macros to avoid all the latex dependencies in that and the multiple layers of abstraction from pgf itself. Hence 'noPGF' in various of the names in the snippet below, which generates the dividers, as (PDF) vector graphics. 
```
\vskip 3em
\def\ornamentstretch{1.5}
\noindent\hbox to \hsize{\leavevmode\nopgfOrnaments{73|h|-,73||-,72||*,70,73||*,72||-,72|h|-}}
\def\ornamentstretch{1}

\hrule

\SetuppfgOrnament{0.1}{}{}
\def\ornamentstretch{1.0}
\leavevmode\nopgfOrnaments{71,70,71}\endgraf 

\vskip 3em
\leavevmode\nopgfOrnaments{72,76,75,74,73}\endgraf
```
Key to the above `X|Y|Z` cryptic format in line 3 is: `X` = element number; `Y`=flip (h=horizontal flip); `Z` stretch/repeat: `-` stretch `*` auto-repeat. My intention is to (eventually) have it adjust stretch so that with a minimal amount of stretch in the requested elements, there is no whitespace added.  Another challenge is to be able to make frames around things.

**Comment by davidg-sil** [comment]
For side-bar borders, this is now semi-integrated as a plugin. It's not accessible via the GUI, and needs extra paths added to TEXPATH (and the files from the package). 
Partial screen-shot below is from `examples/testcases/ornaments`:

![image](https://user-images.githubusercontent.com/58848232/153208628-aa2b045b-2235-4530-ae08-1f83176c86f3.png)

**Comment by mhosken** [comment]
This is coming along nicely. I see there are some next steps needed:
- Allow borders around the main text block (excluding page bottom notes, etc.) which adapts height according to the text block size. This also means that the text block calculations will need to factor in the border heights.
- Allow font glyphs to be used as vectorian elements rather than the fixed set of svg descriptions. Yes, this loses fill colour, but that's a small price to pay for the convenience of using fonts for the border elements
- Add glyph ductility to allow a top/bottom border to consist of two corners filled by an unknown number of single elements. Then TeX calculates how many are needed and then stretches or shrinks them all to resolve the granularity error. This also applies vertically.

The primary use case I see for all this is bordered texts where footnotes need to be identified as not being part of the authoritative text. Also then study bibles may be produced for such communities.

**Comment by mhosken** [comment]
In answer to the anticipated question of which takes priority between glue and glyph stretch, I would say glue. If there is any space glue in a border description, no elements stretch or shrink.

It may also be assumed that all border elements come from the same font, although different fonts may be used for different projects.

**Comment by davidg-sil** [comment]
Unanswered questions:
- Are repeated strings of elements going to be necessary  (e.g. fill with repeated "<>" )?
  - If so, is this desirable for ornaments as well as font-based elements?

Assumption:
- There is never going to be a need to mix different fonts / ornament sources that have the same element / character number

Steps to cope with a font-based approach:
- Implement multiply+stretch [WIP]
- Decide on method to specify font
- Decide on method to specify border chars 
- Method to generate glyph size lookup table needed for calculations (or measure on-the-fly at a standard size??) Is there something more efficient than 'stick it in a box and measure'? Possibly not for strings.
- How to apply horizontal / vertical stretch?
- Output the glyph/string simply or do something clever in PDF?

**Comment by davidg-sil** [comment]
Update (status on 10th March):
* pgfhan ornaments can now actually be selected!
* multiply+stretch now implemented and working.
* Font-based ornaments can be selected, rotated, stretched, coloured etc. in the same way as pgf ornaments are. (except by definition they have no outline stroke, just fill.)
* If font-based ornament strings are assigned a number in the .tex file, then each font-based ornament string can be have its own font
* If font-based ornament strings are just used in the stylesheet, the global `\StringOrnamentFont` defines the font.
* `\OrnamentsFamily` is currently a global (`vectorian` or `pgfhan`). If there's a demand, it should be possible to make it so that Ornaments 1-200 are from `vectorian`, 201-400 from `pfghan`, etc.
* Ornamental `\zrule`  and sidebar boxes are fairly well tested, but not yet in GUI (hand-crafted `.sty` file is needed).
* Ornamental **text borders** are currently in alpha testing. These (should) put a  border around the text body, and make no allowance for the user not leaving enough space for header lines, etc. 
![image](https://user-images.githubusercontent.com/58848232/157696997-5bcd8a4a-d2d6-4bdf-9291-53d2d27e025f.png)

**Comment by davidg-sil** [comment]
Update: Allowance for text borders should now be in place.

**Comment by markpenny** [comment]
This now works well, but the UI needs to be enhanced to make this easy enough for the average user to make use of.
