### ISSUE TITLE
Can thumb tabs have bleed (extend beyond the edge of the page if/when 

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#503]
[Suggestion from PTXprint community](https://community.scripture.software.sil.org/t/thumb-tabs-with-bleed/2567)

Can thumb tabs have bleed (extend beyond the edge of the page if/when crop marks is enabled)

**Comment by mhosken** [comment]
We already to 1pt of bleed. Perhaps there should be more?

**Comment by davidc86** [comment]
I know that where we work, books are made on photocopy machines, and the operator is not always carefully about positioning the original pages on the glass, nor do the machines always pick up the paper sheets to print the back side quite as consistently as the high-end publication industry expects. So having lots of "bleed" on those thumb tabs does allow the pages to shift a bit side-to-side and still have the thumb tabs show when the book is cut for final trimming (there is a need for extra wiggle room on the outer margin of the thumb tabs, so wherever they are cut the book abbrev. still shows, rather than getting cut off).
Just my observations on the hand-made book industry where we work.

**Comment by markpenny** [comment]
In this original thread, 8pt was suggested. Why not round it up to **10pt**?  After all, there's very little lost by making the bleed larger - it will only get trimmed off anyway.

**Comment by mhosken** [comment]
you can set \def\TabBleed{5pt} which is currently the default being the distance from the edge of the page to the end of the widest horizontal crop mark (think top left corner).
