### ISSUE TITLE
Multiple PicInfo.txt files found in a project

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#512]
My understanding is that there should only be ONE PicInfo.txt per project, but clearly these are being copied/duplicated when they shouldn't be:
![image](https://user-images.githubusercontent.com/12962708/132778086-c083d775-5c3c-49e4-a01d-da53993db318.png)

**Comment by mhosken** [comment]
No there are two picInfos associated with a publication. The first picInfo is all the shared information between publications: clear, acceptable, reverse, creditbox and credit text. The other information is publication specific: usage, clear, noise, acceptable.

At least that's what's supposed to happen in theory. But it looks like things aren't working quite right and shared info is ending up in the publication info. Or is it that the shared info is being copied into the publication instead of copying over the publication specific? (Conjecture).

Question. What are the symptoms of this bug? What needs fixing (apart from just getting it all right again)?

**Comment by markpenny** [comment]
There aren't any symptoms for the users - apart from there being lots of versions of this file being scattered around, and if they happen to edit one, they're not sure why what they have done doesn't have any impact on what happens in the output for that config.

So, yes, let's just make sure there is only ONE of these files hanging around, and not lots of them. (And make sure that they don't get copied when creating a new config, or when copying a config from one project to another).

**Comment by mhosken** [comment]
No. The point is there needs to be 2 files. Because some information is specific to the publication and some to the language project. So, the number of files is exactly right. The only issue is whether they contain the right stuff. Remember picinfo files contain information on checking files and piclists contain lists of pictures in a publication. Are we talking about the right files?

**Comment by mhosken** [comment]
Rename publication specific picInfo.txt to picChecks.txt and is generally pretty small since people don't add such info.
