### ISSUE TITLE
Enable Layout Templates to be packaged and shared between users

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#515]
!dea - Create a way for users/typesetters to submit their finely tuned set of settings to a publicly accessible template gallery (that other users can grab and use if they like the look of the layout). This would include one or more screen-shots of the PDF showing the final look, highlighting the features, and would be filterable on options when searching for an appropriate layout: eg. “Show me all the templates for (i) DEV script (ii) 2-col layout (iii) with thumb-tabs.”

Currently we can copy Configurations to other projects (which is great), but this would enable people to share (give or take) config templates or bundles with other users via a shared online repo.

A pre-requisite to this would be to enable "templates" (a collection of settings, and associated files) to be distributed along with PTXprint when it is deployed.

**Comment by mhosken** [comment]
Here is a proposal on how we might do this. We only plan on supporting one source rather than merging configs from multiple sources.
# Basic structure
Within the publication config (shared/ptxprint/config) there will be potentially two new directories:
- *base*. This contains the config files (ptxprint.cfg, ptxprint.sty) as they were after the last merge
- *mergeout*. This is generated by someone creating a template and contains the config files that other projects will merge into their projects.

Notice that when creating the mergeout, only those fields and styles that are to be merged are stored in the config files. Thus these files are subsets of a full config. In addition, other resources may ship in the mergeout directory. A template can simply consist of a mergeout directory in a zip.

# Merging
The process of merging involves doing a 3 way merge between the current config, base and mergeout. Any differences between mergeout and base are applied to current config, unless current config has a difference from base in the same place. Conflicts are automatically resolved in favour of the current config.

Once a merge has concluded, the resulting updated config is also saved to base as the basis for future merges.

**Comment by davidg-sil** [comment]
It may be desirable to have a '(interactively) trash my changes' option as well: all _merge_ items different to _base_  become part of the new configuration. (with option of 'merge file says.... you had....'). 
Or maybe a 'this value is non-standard' emboldened display, like with style-sheets?

**Comment by markpenny** [comment]
@mhosken Where are we up to on this one? I know that we have the base and 3-way merge etc. but I don't know how we're presenting it to the users (other than just allowing them to IMPORT a config from a PDF). It probably needs some help if it is ever to become mainstream.

Should we discuss this with others in NOV as well?

**Comment by markpenny** [comment]
Most of this request will be addressed by the upcoming feature "Import [selective] settings..."
