### ISSUE TITLE
Can't Format the Picture Captions

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#53]
There is probably a way to format the picture captions, but I'm not seeing it. I looked in the Pic List, and that has the information, but no field marker to apply an attribute to. And when I look in the draft SFM file, the picture data has all been removed.
The logical place is to add a control to the Pictures tab.

**Comment by davidg-sil** [comment]
Looking at the source code, the font of the caption text is set as \fig (see your stylesheet). It being centred and where the verse reference (if supplied) go, etc. are hard-coded.

**Comment by markpenny** [comment]
We would eventually like to add a Stylesheet editor control so that people don't have to go digging in the multiple .sty files to work out what needs to change. That would make it possible to easily control the style of captions. But as DG mentioned, and as stated in the [FAQ ](https://software.sil.org/ptxprint/faq/) _which is still being developed_ - you can make changes to the \fig style.
```
##### Make illustration captions slightly smaller than body text and Italicize
\Marker fig
\Fontsize 11
\Italic

```
