### ISSUE TITLE
Erroneous error message

### ISSUE THREAD

**Issue by sewhite** [sillsdev/ptx2pdf#552]
Running PTXPrint on Mark in this project produces this error message about \x on line 581.
There is no \x on line 581 or 580. In fact, there are no \x markers in that entire chapter. (chapter 8). 

![image](https://user-images.githubusercontent.com/16904461/137963347-5f9d59eb-3bb1-47c6-bcce-b712c996ed99.png)

[GSP2-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/7375626/GSP2-DefaultPTXprintArchive.zip)

**Comment by markpenny** [comment]
Thank you @sewhite for uncovering this one for us. It took us some digging to figure out what was wrong, and it was a combination of factors. One of which was due to \qt not being listed in the "Occurs under" settings for \x (or \f). Now that the underlying stylesheet has been fixed, this should just work WITHOUT our additional rules (which I had asked you to add in PrintDraftChanges.txt) to move \qt* before the \x etc. We have also updated the code to handle closing \usfm* markers which don't have a space after them. So, all in all, some significant fixes which will benefit everyone else. We hope to get 2.0.2 out before the end of today - for you to test further.

But please ensure you remove those rules from the end of your PrintDraftChanges.txt file before you re-test.
