### ISSUE TITLE
Chapter Number Drop-Caps impinges on footnotes (v2.0.4)

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#558]
This may not be new, but I'm seeing this now: 

![image](https://user-images.githubusercontent.com/65363206/138704677-30024014-a71c-4165-9392-ad6612456ace.png)

I do have my Advanced ptxprint-mods.tex file set to this:
% This is the .tex file specific for the SLU project used by PTXprint.
% Saved Configuration name: SelaruNewPublication
\TOCthreetabfalse
\clubpenalty=0
\widowpenalty=0 
\NoteCallerSpace=0.0em

So I don't know if the "0" settings for the clubpenalty and widowpenalty is a factor, but I haven't changed these settings in a very long time, and I don't recall seeing this Chapter number issue before.

**Comment by cmahte** [comment]
Mark,

I've done preparatory work to eliminate the user on this....  That is, Make
the page layout mostly do the typesetting, so that a human doesn't have to
go in and tweak it.

The primary target for typsetting is always the same: to have the last page
of a block of text (where "block of text here means from a hard page break
to the next hard page break) fill between 30-90%, or with shorter blocks,
consume at least 4 or 2 lines up to 100% of the last page.  There are other
lesser problems like spanning footnotes and hyphenated words and
orphan/widow paragraphs, but the first problem is not having entirely blank
pages with 1 line of text on them where that much break isn't wanted.

And when I'm typesetting here's the formula I follow manually:

Total linelength / (lines in a page * length of each line) = number of
pages.  But the  residual is the concern for the typesetter.  If it's 50%,
there's no concern, but if there's 90-110% then you want to stretch or
squeeze away from the 0% toward 50%.  If the remainder is between 25%-75%,
then both stretching and squeezing should maintain that midpage ending, but
not in close proximity.

There's math to do for whitespace around titles and implied breaks, but it
generally works this way. and in manual typesetting I just page forward and
look where the last page of the block is, then teypset that block to those
parameters... always squeeze, always stretch or maintain neutral space.
