### ISSUE TITLE
Request for configuration-specific PrintDraftChanges

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#587]
Would it be possible to add an analogue to the PrintDraftChanges.txt file which doesn't live in the project PT folder, but rather lives in the \shared\ptxprint\CONFIGURATION folder. Similar to ptxprint.sty. In fact, maybe a name like ptxprintchange.txt would make sense.

I think it's probably obvious why this would be advantageous once you have 4 or 5 configurations printing different parts of a translation in very different ways, but I can explain more if necessary. Basically, I want to have changes that only apply to a given print configuration, not to a given language project.

**Comment by markpenny** [comment]
Yes @mnjames. You are right, and we have noticed this issue - that certain changes need to be config-specific. So that's already being worked on. Each config will soon have its own **change.txt** file, but will [by default, for backward compatibility reasons] pull in (or import) the project's underlying printdraftchange.txt file. You can easily unhook the import so that there is no link back to ptxprintchanges.txt. My best guess is that this will be part of 2.1 whenever that comes out, as it also requires some UI work.
