### ISSUE TITLE
build process for debian, to adapt to gentoo.

### ISSUE THREAD

**Issue by hanetzer** [sillsdev/ptx2pdf#591]
Ello. Came across your project looking into interlinear bible tools for use with latex.
I use gentoo linux, which is not packaged for this system. I was hoping you could
point me at how you build the debian package, and where the files should end up,
so I could write a gentoo ebuild for this.

Running `python setup.py install --user`  works but it says paratex is not installed
and asks where the USFM projects are/will be stored.

**Comment by mhosken** [comment]
It sounds like you have the program running as written.

PTXprint is typically used by people who are using ParaTExt to create the scripture they are typesetting. PTXprint doesn't actually need ParaTExt installed to run. All that you need to do is to point PTXprint at the directory above the directory containing the sfm files. This is because the assumed directory structure is of a directory containing project directories, one per project, each containing the SFM files and other files.

If you set a suitable directory, PTXprint will remember that going forward. You can override it from the command line (PTXprint -h is quite fun).

**Comment by hanetzer** [comment]
Hrm. where are the sfm files at, then? I'm only seeing them under the
tests directory. What does a 'suitable directory' look like?

**Comment by mhosken** [comment]
A suitable is test/projects as in it contains project directories: projects/WEBorig/01GENWEBorig.SFM. The sfm files are the files that you as a translator are creating through diligence and hard work. An appropriate free tool might be [bibledit](https://bibledit.org/).

**Comment by hanetzer** [comment]
Huh. I was under the impression this project at least came with some
'barebones' skeleton projects to start working from. My mistake, then.
Eyeballing the file you pointed out, it doesn't resemble latex as I'm
familiar with it. Is this format documented somewhere?

**Comment by markpenny** [comment]
I have a feeling that you have mistakenly understood **Paratext** to be some kind of Para**TeX** which would obviously lead to a LOT of confusion and frustration. You need to understand that [PTXprint](https://software.sil.org/ptxprint/) is primarily for existing users of [Paratext](https://paratext.org/) (which uses USFM markup for scripture text).

**Comment by hanetzer** [comment]
A very distinct possibility. Thanks for some leads, however. Think that should do the trick for now.

**Comment by mhosken** [comment]
Ptxprint does not use latex, the macro package is built on top of plain tex.
