### ISSUE TITLE
FileNotFoundError on Generate Final SFM

### ISSUE THREAD

**Issue by SaraMeiSL** [sillsdev/ptx2pdf#607]
Trying to generate the Final SFM in View+Edit generated the following error. 
I know I have my PT projects in a non-standard place, but it should be able to cope?

![image](https://user-images.githubusercontent.com/74278075/150613404-d5f46dc5-fcda-4643-95e1-c602d45a03ed.png)

![image](https://user-images.githubusercontent.com/74278075/150613527-a4be42a6-067c-4f49-9bd5-509bce7e3e72.png)

**Comment by markpenny** [comment]
Thank you. That is good to know. We'll track it down and fix it for the next release.

**Comment by markpenny** [comment]
@mhosken Just confirming that this bug is reproduceable, but has nothing to do with a non-standard path. It is due to the following conditions:
a) Create a new config (ie. assign a name and then hit save)
b) Go to the View+Edit tab and click Generate (**without first printing anything**)
![image](https://user-images.githubusercontent.com/12962708/150711961-1a61041c-4b7c-4b15-a376-3ca666a6c7a3.png)
Given that PTXprint hasn't been run before, the file that it is looking for (in the \local\ptxprint\configname folder) doesn't exist yet.
I'm not sure how best to mitigate the strange combination of conditions. Perhaps just best to pop up a warning if it happens.
