### ISSUE TITLE
Two Column Layout reversed

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#624]
I have a project that started out as a Diglot, but that was incorrect, so I switched off Diglot, but the typesetting still typeset two columns, even though the Two Column Layout box is unchecked. Now if I check the Two Column Layout box, it goes to single column! Some remnant left over from the Diglot stuff? I created an archive of the project, and have sent it to Martin and Mark.

**Comment by markpenny** [comment]
Sorry @jeffheath-sil - we pulled a fast one on you! (but in all fairness it was many months ago now) This option used to say "Use Single column for these books" but now it has a toggling function so that it is the opposite to whatever you have set on the layout tab!

There was a rather cryptic note in 2.0.6 (10 Nov 2021) which mentioned it:
* Allow switching 1->2 cols for specific books (previously only 2->1 was possible)

![image](https://user-images.githubusercontent.com/12962708/156325169-cedba384-73f6-45e0-8a0d-01686d74228e.png)

**Comment by markpenny** [comment]
@jeffheath-sil Thanks for the tooltip suggestion. (See also Different Column Layout on the Body tab) something like that has been implemented now and will be in 2.1.15

![image](https://user-images.githubusercontent.com/12962708/156445883-e902c177-0fd2-497b-a407-b6bdbf748a7f.png)
