### ISSUE TITLE
Pictures placement (particularly in single column layout) still too hard for ordinary users

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#634]
An (advanced) user reported:

"I couldn't make the pictures not take up half a page or run into footnotes or text."
   and 
"...the pictures didn't go where I wanted them to go and I gave up in the end and did it with export to rtf and Word again as in the past. That is sad and equally tedious, but at least I can make it work."
   and
"But am I right in getting the impression that it still isn't up to doing some of our most ordinary daily jobs for an ordinary user/team like me?"
   and
"What we regularly need in an ordinary project is  print a simple draft including pictures for a UNS check on A4, and printing an A5 booklet with pictures for advertising the translation with a finished book, both without columns, because we have very long words. Those are the most common draft print jobs I need very regularly. But to me, as an ordinary user, it seems too hard to make it work, if it does in fact work. That in turn seems to kind of miss the purpose of it all for someone like me."
   and
"I had hoped this was going to be a tool I could recommend to teams to replace printdraft for them. A quick and simple way of churning out the copy they need for their next community check. But it isn't. That is disappointing, at least to me. 
   and
"Maybe there is in fact no solution for this and that is simply the nature of the matter with pictures. I'm no expert to judge that." 
   and
"...for the quick job in a project for ordinary people, there still seems to be nothing that really does the job."

Indeed - we've missed the mark if we can't make it work "out of the box" for ordinary users. It is clear that 2-col layouts have less issues than 1-col layouts, but for many parts of the world, they only used 1-col layouts.

From one of the screenshots, it was clear that the user was trying to use a cutout, but the anchor ref was right at the page boundary - causing mayhem in the footnote area and a big empty cutout area on the following page.

I think part of the problem (for single-column layouts) is that top-left, top-right, bottom-left, bottom-right get transformed into just "top" or "bottom" taking more room than they want to give the pictures. **So, I wonder if we can/should change that behaviour to produce a 1/2 col width fixed position cutout which is actually top-left, top-right, bottom-left, or bottom-right.**

Another possibility, that might help in some cases is that we have a new option on the Pictures tab (which is enabled by default) which says; "Limit vertical height to a maximum of X% of the page height" - and set the value of X to 50% by default.

**Comment by davidg-sil** [comment]
Because of how TeX processes its input (reading ahead, forming the columns and then 'pasting them' onto the page later), it would be somewhere between hard and 'probably not impossible' to anchor a **cut-out** to the physical page.
To clarify this a little:
* Positioning an image at a precise position on page 9 is actually quite easy: the 'full page' logic can be subverted so rather than generating a full page image and shipping out the page, it writes a smaller image and doesn't ship it out.
* Knowing which lines of which paragraph needs to be broken is considerably harder. Almost certainly, they will have already been processed into columns, so for the first run, the text will fully overwrite all absolutely-placed images.  As ever, adjusting the paragraph could well move the image's anchor  onto the next page. 
* Positioning an image at a precise position on the page on which Rev 20:1 appears requires that the page be processed first, data from that run interpreted, and the process restarted, 'knowing' that rev20:1 was on page 543 last time round.
* Positioning an image at a precise position on the first page of anything that starts a new page is quite simple.
* Positioning an image at a precise position on the page that starts *after*  Rev 20:1 appears is probably 'a not-impossible' task. It's going to take some re-processing.

**Comment by markpenny** [comment]
@davidg-sil I think I might have asked this question before. But is there any way to make the anchor ref more like a suggestion rather than a rule (like laws of the Medes and Persians) which cannot be changed? For example, if the user provided a range of verses like Rev 20:1-8 for the anchor ref, the macros would have more wiggle room about positioning illustrations (so as long as any verse between that range was still on the page of the illustration it would be acceptable). Would that help at all, or is TeX far more difficult than that?

**Comment by mhosken** [comment]
Unfortunately, programming up the 'let's try lots of different anchor positions and measure the amount of empty space at the end of the pages' would be both slow and a lot of work to program (read MAJOR refactor). Nothing in the macros is limited by the anchor. The anchor basically says where the picture should go, and if it's page positioned, then it helpfully just sets the page. For other positions (cutouts, etc.) the position is relative to the paragraph and so the anchor is merely locating that paragraph. The macros need to decide where to put something. Having less choice makes that easier.
