### ISSUE TITLE
PTXprint (2.1.13) still strips some \fig lines from our BAK book

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#648]
Just downloaded 2.1.13 to text Front and Back matter behavior, and it is still stripping out several \fig lines from our BAK book. No idea why.

Here is the SFM from Paratext:

\id BAK - Selaru\h Gambar o Peta \toc3 Peta \toc2 Gambar o Peta \toc1 Gambar o Peta-nare \rem zthumbtab PETA \mt1 Gambar o Peta \mt2 ti Kitab Lanke \rem Di sini kita kumpul semua peta dalam Alkitab \c 1 \p Ti ne tatos gambar o peta-nare ma klyosu o nam rakesy ti Kitab Lanke ne. \m \fig Nuske Ktem ne heitlulswo kyoat Yunus imorifke|alt="The world long ago when Jonah was living" src="PetaYunus_Selaru.tif" size="col" ref="Yun. 1–4"\fig* \pc Matos ti Kitab Yunuske \b \m \fig Hulasokwe Seike ti kyoat Yesuske imin ti lasmyer khaha ne|alt="The Temple of God" src="LB00250B.tif" size="col" ref="Luk. 4:9"\fig* \pc \xt Luk. 4:9\xt* \b \m \fig Nus o hnu ti lasmyer Palestinake|alt="The cities and towns in the land of Palestina" src="Holy_Land_BW-Selaru.tif" size="col"\fig* \pc Tnyetak Harharkwe \b \m \fig Saulus yor Barnabas wait laklakut mamunake ne|alt="Paul and Barnabas' journey 1" src="Paul1-BW_Selaru.tif" size="col"\fig* \pc \xt Kis. 13–14\xt* \b \m \fig Paulus wasi laklakut a kla-ruake ne|alt="Paul's journey 2" src="Paul2-BW_Selaru.tif" size="col"\fig* \pc \xt Kis. 15–18\xt* \b \m \fig Paulus wasi laklakut a kla-teluke ne|alt="Paul's journey 3" src="Paul3-BW_Selaru.tif" size="col"\fig* \pc \xt Kis. 19–21\xt* \b \m \fig Paulus wasi laklakutke bai nus lan Romake|alt="Paul's journey to Rome" src="Paul4-BW_Selaru.tif" size="col"\fig* \pc \xt Kis. 27–28\xt* \b \m \fig Nus o hnu a Paulus yor lianare rabrita Brit Eraske tiare|alt="Map of Italy to Middle East" src="PetaLokasi5T_Selaru.tif" size="col"\fig* \pc \xt 1Tes. 1:8\xt* \b 

(I have no idea why there are no <Enter> in there! Is that possibly the problem? It looks just fine in Paratext.)

Here is the Final SFM if I click the [Generate] button:

\id BAK ‑ Selaru
\h Gambar o Peta
\toc3 Peta

\toc1 Gambar o Peta-nare
\mt1 Gambar o Peta
\mt2 ti Kitab Lanke
\p Ti ne tatos gambar o peta-nare ma klyosu o nam rakesy ti Kitab Lanke ne.
\m 
\pc Matos ti Kitab Yunuske
\b
\m 
\pc \xt Luk. 4:9\xt*
\b
\m 
\pc Tnyetak Harharkwe
\b
\m \zfiga|.3\*
\pc \xt Kis. 13–14\xt*
\b
\m \zfiga|.4\*
\pc \xt Kis. 15–18\xt*
\b
\m \zfiga|.5\*
\pc \xt Kis. 19–21\xt*
\b
\m \zfiga|.6\*
\pc \xt Kis. 27–28\xt*
\b
\m \zfiga|.7\*
\pc \xt 1Tes. 1:8\xt*
\b

In there I can see the first THREE illustrations are not generated/listed.

**Comment by mhosken** [comment]
If this is you reraising an existing bug. Then either put a comment in that bug or at least link this bug to the previous one so that we can find the archive to start fixing it.

**Comment by davidg-sil** [comment]
@davidc86 , when you said 'there are no in there' did you mean 'no line-breaks'?
Yes, a lack of line-breaks would cause problems. USFM-3, at least, specifies that there should be a line break before any new paragraph marker.  Hopefully the lack of them is just cut-and-paste not copying correctly. Or are you saying that the code looks like that in the paratext file? Unformatted view ought to show you what's actually in the file.

I'm not at all sure why you're using `\xt...` as a supplemental caption. It might confuse things, with it not being inside a footnote. Do you have scripture-references in captions turned off?

@mhosken, this bug certainly has similarities with #641:  The `\zfiga`'s don't terminate properly (`*` instead of `\*`).

**Comment by mhosken** [comment]
The important thing is to terminate the \id line with a newline. The rest is probably OK.
