### ISSUE TITLE
Insufficient range for footer position?

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#65]
I have a draft border that I'm using that has a "hole" to hold the page number:

![image](https://user-images.githubusercontent.com/14953913/82303506-f1e88f80-99b2-11ea-869b-e537242fa5d0.png)

As you can see, the page number is a little lower than it should be to be nicely centered in the "hole". But the only place I find to adjust that position is the Footer Position field. And the max value of that field is 1.00, which isn't quite high enough. That field is 1.00 what? (Doesn't give dimensions...) Can it be made to have a larger max value?

**Comment by markpenny** [comment]
I've bumped up both the hdr and ftr to a max of 2. I have a feeling we need to revisit ALL the dimensions so that they are absolute values rather than "factors" based on other values. Would people be happy enough if everything was in metric (mm)? Or are there people out there still insisting on inches, points, ems and picas? (which would confuse most people).
Will be available in 0.6.5 shortly.
