### ISSUE TITLE
Indent problem in Bible Modules

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#653]
When I print a Bible Module using that option in ptxprint, certain paragraphs are not indented. They seem to be primarily paragraphs following `\rem` lines, but there are a few other cases which I can't predict.

If the exact same module is printed via the Single Book -- XXB option, it works correctly.

**Comment by mhosken** [comment]
Here's what's going on at least when processing the module. When a \ref is inserted, the module flattening code has to decide what marker to give the start of the text: \p or \p1. Why \p1? Because according to the USFM spec as it stands, \p may only occur after a \c somewhere in the file, while \p1 may occur before. Since there is no \c in your module (understandably), the flattener uses \p1. So your output ends up with some paragraphs indented by 0.65inch and some by 0.08inch.

Now, the question is whether this is the right thing to do and that comes back to the fundamental structure of USFM. Should we say that the delimiter between the intro paragraphs and the body paragraphs is \c or should we say that any body marker is the boundary. I would like to say the latter, and that would allow \c to take its rightful place structurally as a milestone and not the head of pretty much everything. But that's a story for a whole lot of other work I am doing.

**Comment by mhosken** [comment]
Why does this not happen in XXB? There seems to be something odd happening that means that the \ref is considered part of the \rem by the usfm parser (even though \ref is a paragraph marker. The reason for this is that the \occursunder for \ref has not been set. Setting it to \id results in the same experience with XXB as for the module.

**Comment by mnjames** [comment]
Thank you for this explanation. Yes, styling \p1 did work, though it is certainly far, far from intuitive.

Man, USFM confuses me. I think that's a least partially because I've pretty much learned everything I know about it from PT, and I think USFM confuses PT a lot.

> Because according to the USFM spec as it stands, \p may only occur after a \c somewhere in the file

How do you know learn this? When I have a question about USFM I usually go to [https://ubsicap.github.io/usfm/](https://ubsicap.github.io/usfm/), but it doesn't say thing about \p necessarily occurirng under \c.

> Since there is no \c in your module (understandably)

Why could I alternately not solve the problem by adding \c 1 to the beginning of my module (I've tried and it didn't work)?

Another question that this brought up, why does \p (and \p1 for that matter) default to a First Line Indent Factor of 0.12. Shouldn't the default almost tautologically be 1.00?

**Comment by davidg-sil** [comment]
Answering a few of your questions... 
* `\OccursUnder` is in the paratext stylesheet, and it's what makes/helps Paratext complain about some markers not being in the right place. There might be some benefit from PTXprint using it (I'm not very sure what), but there are almost certainly benefits (like not needing p1 / p) from ignoring it entirely.
* Why 0.12? (It should be 0.125). Paratext's style sheet assumes that indents are measured in inches. The ptx2pdf macros allow that '1inch' base measurement to be changed (scaling all indents by the same factor)

**Comment by mnjames** [comment]
There's a lot of work needed for Bible Modules, but I'll close this until such as time as someone (me) gets around to doing a system test of everything. Hopefully a future Bible Module conversion script will clear some of this up.
