### ISSUE TITLE
Missing section heading

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#659]
I have a project - first part of Genesis - where the section heading before Gen 1:1 is not being published. In the text:
![image](https://user-images.githubusercontent.com/14953913/163861145-6e6873c8-57fc-433b-b277-2a3775f5507d.png)

In the resultant PDF:
![image](https://user-images.githubusercontent.com/14953913/163861215-f658afd3-f5b9-4a97-a8ea-e51cc6f555bc.png)

I'm sending an archive to ptxprint_support.

**Comment by jeffheath-sil** [comment]
I should have said this is with the configuration to always start chapter 1 on a new page. But if I uncheck that I get a similar result:
![image](https://user-images.githubusercontent.com/14953913/163861642-23bc4e74-ac5c-4907-a7a5-07af6d04b18e.png)

This is quite disconcerting, that a section head would disappear... What if I didn't happen to notice it?

**Comment by markpenny** [comment]
Thanks for picking up this bug @jeffheath-sil . It is related to the chapter range settings. I trust we can get a fix into the next version which should be out later in the week (if all goes well).
![image](https://user-images.githubusercontent.com/12962708/163892302-f4d825ab-55ac-4539-a43f-e0ba65e128ca.png)
![image](https://user-images.githubusercontent.com/12962708/163892315-995b0c92-14e7-48c6-b62c-4a0790c66ac4.png)

The only **temporary work-around** that I can think of is to ask for all 50 chapters of GEN (as shown above), and then throw in a changes.txt rule to discard all the remaining text from \c 25 onwards: (note that the (?s) tells it that '.' dot matches newlines; otherwise it wouldn't find enough.
`"(?s)\\c 25.+" > ""`

**Comment by jeffheath-sil** [comment]
That work-around works fine for my current needs. Thanks.
