### ISSUE TITLE
Table of Contents variable needs entered twice

### ISSUE THREAD

**Issue by Ben-Pehrson** [sillsdev/ptx2pdf#668]
On the Peripherals tab, there's a field to enter the Table of Contents Title near the top of the window, but it can also be included in the Variables and Values. Why does this have to be entered twice? What happens if you only enter it in one of those two places, or if the values clash?

**Comment by markpenny** [comment]
There is a bit of history here...

Before PTXprint could handle any kind of front matter, there was an option to generate a Table of Contents. This still exists, and is easy for the average user to make use of (i.e. check the box for the Table of Contents, type in an appropriate title, and hit Print. Done!) That functionality needs to stay for our everyday (non-typesetter) users.

But now that we have added some extremely powerful front-matter processing options, there is understandably some confusion, for example:
 
![image](https://user-images.githubusercontent.com/12962708/166168582-0c2fb991-c293-4f03-9203-cc4b188c4cbf.png)

To answer that we need to look into the FRT matter to see what we asked for:
![image](https://user-images.githubusercontent.com/12962708/166168606-1c7345c6-e540-4d51-865b-980e35c9bd50.png)
...and it is now clear that the title is coming from \zvar|**toctitle**\* (which is pointing to the field that we filled in above).

If you want to overwrite that default behaviour, you can change the variable name to make it use the one defined in the list of variables (as shown below) rather than the Title at the top of the page:
![image](https://user-images.githubusercontent.com/12962708/166168677-2a40bb54-0721-411e-9e98-8247371282f8.png)

So, yes, it is a bit more complex than needs to be, but there is a valid reason which is to keep both ordinary users and power users happy; but this comes with the associated cost of sacrificing simplicity!

**Comment by Ben-Pehrson** [comment]
Okay, no worries. That's very understandable.
