### ISSUE TITLE
Running out of NBSP \u00A0 characters!

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#67]
There is an issue (reproduce-able on Windows at least) where after a certain point in the document - usually after a few hundred pages, the NBSP characters refuse to show up. They are clearly in the -draft .SFM file that gets fed to PTXprint (higlighted in yellow):
 
![image](https://user-images.githubusercontent.com/12962708/82325134-5a0d9480-99f8-11ea-8dbc-9345a20b1634.png)

But somehow they all drop out of the resulting PDF:

![image](https://user-images.githubusercontent.com/12962708/82325259-8f19e700-99f8-11ea-93b0-0c497b2e9939.png)

It is almost as if that special character has hit some physical limit, and there none left to go around :-)

**Comment by davidg-sil** [comment]
Can you try sabotaging your .usfm, so that, say, if it normally dies half way through chapter 3, chapter 1 and 2 are cut out? I'm wondering if something else might be happening. 
By the way, have you noticed that the callers are being forced to be either stars or double-daggers? I'm curious why anyone would do that.

**Comment by mhosken** [comment]
This one has me stumped. It's not a xetex binary problem and it's not a memory problem. I've seen NBSP disappearing in JOS in an OT consisting of GEN JOS etc. so there is something causing NBSP to misbehave and I can't find it.

**Comment by davidg-sil** [comment]
There are certain bits of code that turn  NBSP and other things into \relax. It's supposed to be a temporary measure during I'm not sure what.  My guess is that something is not restoring them.

**Comment by mhosken** [comment]
It's not in the only call to \pr@tectspecials that I can find in \maket@cline. I tried commenting that out and it made no difference (especially since I'm also pretty certain that macro is never called in my text). Are there any other macros or call sites to \pr@tectspecials, that I should check out?

**Comment by markpenny** [comment]
@davidg-sil Do you have any more ideas on this one? I'm keen to solve it before we ship ver 1.0, but don't know how realistic that is. Have you been able to reproduce it on your machine? Do you already have access to my series of WSG projects? There are 3 or 4 projects in different scripts that have significant chunks of scripture that are useful for testing/diagnosing bugs like this. Let me know if you want me to share them.

**Comment by markpenny** [comment]
This seems to be fixed! Well done @davidg-sil for finding it. I'm closing the issue.
