### ISSUE TITLE
Diglot not picking up discretionary line breaks from secondary text

### ISSUE THREAD

**Issue by Ben-Pehrson** [sillsdev/ptx2pdf#671]
I'm trying to make section heads in both the primary and secondary texts of a diglot have the same number of lines in each text, so I'm putting in discretionary line breaks in one or the other text. PTXPrint is picking up the discretionary line breaks from the primary text, but not the secondary text. Here's an example of what I've done in Paratext...
![image](https://user-images.githubusercontent.com/104610062/166224205-dc898a98-a3c4-4aaf-9e48-5463bf66835e.png)

And here's the PDF output...
![image](https://user-images.githubusercontent.com/104610062/166224277-f0a385e0-0f3a-43d2-8381-0380eb399d68.png)

I've also added some discretionary line breaks in the primary text, and PTXPrint is picking those up just fine.

**Comment by Ben-Pehrson** [comment]
But this behavior is not consistent. Sometimes it is picking them up. Here are the breaks added to Paratext...
![image](https://user-images.githubusercontent.com/104610062/166227145-0f93e228-f044-48fa-9185-b10d95832c4c.png)

And here's the PDF...
![image](https://user-images.githubusercontent.com/104610062/166227235-52f8db15-8dea-4919-b622-c3a28156a08a.png)

**Comment by Ben-Pehrson** [comment]
I have now seen this behavior with the primary text as well.

**Comment by davidg-sil** [comment]
What I'm seeing is expected  behaviour. If there's no pragmatic need to break the line, then the discretionay line break(s) will not force a break. In fact, adjustments it makes so that the it doesn't encourage a break unnecessarily might make a break slightly less likely..

You seem to have fallen into the common trap of thinking that a  discretionary line break is a forced line-break, (or maybe that the left and right collumns communicate with one another so what happens in one happens in the other?  Sorry, that doesn't happen, there is no code to assess an asesthetic need to break based on what's happening in the other column). 

You may want to adjust the margins of \s so that the text cannot fit across the page, perhaps rather than globally, by making a new style in the style editor that is a copy of \s, and then use the changes file to impose just on a few lines (slight alteration fo the  technique shown in a video @markpenny has made about adjusting pages).

**Comment by Ben-Pehrson** [comment]
Yes, I had always thought that discretionary line breaks were forced line breaks. 
I'm curious about another possible workaround. I notice that the "paragraphs" that the Adj List uses are actually standard format markers. So is there a standard format marker that could be inserted into the middle of a section head that could then be formatted as a (forced) line break?

**Comment by davidg-sil** [comment]
Probably the simplest way to frce the title onto two lines is insert a 2nd \s marker.
Alternatively there is a unicode charachter U+2028 LINE SEPARATOR  which will force a libe break.

**Comment by markpenny** [comment]
@Ben-Pehrson I wished I had known this last week; but another way of making PTXprint do what you're expecting is to set "OptionalBreakPenalty" to 10000 which will force a line break whenever it sees the // in the text. So in the ptxprint-mods.tex file (accessed through the Advanced tab) add this line:

`\def\OptionalBreakPenalty{10000}
`

That should give you what you're expecting (but you will need to set this in BOTH the **Pri**mary and **Sec**ondary projects' configurations):

![image](https://user-images.githubusercontent.com/12962708/167757651-808f03b9-9087-4fc8-ad82-c6aee5dec345.png)
