### ISSUE TITLE
Inconsistent reference to Left and Right for diglots

### ISSUE THREAD

**Issue by Ben-Pehrson** [sillsdev/ptx2pdf#672]
On the Diglot tab there is a tick box for "Secondary on Left (or Inner)." But even if that is ticked, the Adj List refers to the primary text as  L and the secondary text as R.  Easy workaround, but it's just a bit inconsistent and confusing.

**Comment by davidg-sil** [comment]
PTXprint is a very clever front-end to very usefull  but pre-existing TeX macros, which does considerable  modifications to the USFM on the way past (sometimes too much!). 
  what you're looking at here is a case of historic developments. The diglot TeX macros 
were first written and used more than a decade and a half ago, and when they did, there were 2 columns, left and right, which were always on the left and right. If you wanted to change the order, you changed which way round they were fed into the merge program and had to alter your style sheets.
Then the ability to make the Left text appear on the right hand side of even numbered pages, but that's just where the result of all the work gets stuck on the final bit of paper, it's still the left text internally.  Then some people wanted the columns to swap the other way, so that was added.

PTXprint UI designers decided to call what the macro still call the left text the primary text, so that people didn't  faced with it saying 'right text on the left (or inner)'  but as far as the macros are concerned, that's exactly what it's being asked to do. 
The polyglot options add more columns, which get labled A, B etc by the only merging tool for them, and you can define the display order to be R,A,B,L if you want to. 
Rewriting all the L and R stuff to be P and S or something would be quite a lot of work and incompatible with old publications.
