### ISSUE TITLE
Request for Adj List to work with footnotes

### ISSUE THREAD

**Issue by Ben-Pehrson** [sillsdev/ptx2pdf#677]
It would be really nice if PTXPrint could adjust paragraphs for footnotes in the same way that it does for paragraphs in the text.

**Comment by davidg-sil** [comment]
Just to check: you want to be able to make a note paragraph a line longer or shorter than it normally is, for balancing purposes?

**Comment by davidg-sil** [comment]
If we used the normal trigger mechanism for this, then:
 1. All footnotes notes would become potential trigger points.
 2. We would need new 'footnote number in this verse, on this side' counter(s).
 3. (a) *Either* the footnote would become the 'current reference point', meaning that a footenote/cross-ref's presence / omission would require current adjust lists, etc. to say "2nd paragraph after 3rd  xref in v2" rather than "2nd paragraph in v2"
*or* (b) the trigger mechanism would need a partial re-write to have a `\global` variant as at present and a local version which didn't do those changes at a global level (and cope with the mess that makes).

3(b) is probably preferable, but might make the docs even more confusing.

I'm guessing that not many people will need this. I'd thus suggest that the following alternative method to achieve this end, which doesn't impact everyone (if nothing else but extra cpu cycles):
a. some additions to `ptxprint-mods.tex` e.g :
```
\def\onelinelonger{\looseness=1}
\def\onelineshorter{\looseness=-1}
```
And b. inserting these through some advanced use of `ptxprint-changes.txt`.

**Comment by mhosken** [comment]
The difficulty with paragraphed footnotes is that the footnotes are re-flowed into new paragraphs at page layout time so any per footnote controls like setting looseness will be lost when the footnote is first put into an infinitely wide box and then the boxes are re-flowed into the final paragraph.
If the footnotes are separate, then yes, looseness can be set. But most footnotes are short enough that this isn't a concern.
My guess is that you want to control paragraphed footnotes and I don't see how we could do that since by the time the footnotes are turned into paragraphs, they are just a vbox of hboxes, with no knowledge of reference or anything.
