### ISSUE TITLE
Space in the pages

### ISSUE THREAD

**Issue by prabhujes123** [sillsdev/ptx2pdf#68]
After taking Psalms I found space in the pages. 
![image](https://user-images.githubusercontent.com/56344868/82367339-43cffa80-9a31-11ea-861b-c0a4a498a23c.png)

How to get Hebrew text
![image](https://user-images.githubusercontent.com/56344868/82367221-184d1000-9a31-11ea-9a51-3c2c7d20fc90.png)

**Comment by markpenny** [comment]
Yes, we are ware of both issues and working on them

**Comment by davidg-sil** [comment]
Regarding the Hebrew... one option is to set up a certain style with a particular font.
\qac …\qac* is a character style supposed to mark [the acrostic letter](http://ubs-icap.org/chm/usfm/3.0/poetry/index.html?highlight=acrostic#qac-qac), It seems like a reasonable use to make that a font-change.
E.g. in the style file:

\Marker \qac
\FontFace Ezra SIL

**Comment by mhosken** [comment]
Mark's recommendation a) above won't help if you just tick the box, since that leaves things as the default. You also need to lower the first number as low as is comfortable to read (how small dare you let a space become) and increase the second number as high as is comfortable (how wide are you willing to let a space go)
Widening the range of those two numbers will help a lot.

**Comment by markpenny** [comment]
@mhosken So the values 66 and 150 are already the default? In that case we should set the UI-defaulted values to something smaller and larger (so that ticking the box does something to begin with and the user can tweak it even further). How about 50 and 200 as UI-defaults?

**Comment by mhosken** [comment]
sure
