### ISSUE TITLE
Can't run a custom script (again)

### ISSUE THREAD

**Issue by da4396** [sillsdev/ptx2pdf#681]
I'm trying to run a custom script but can't get the script to run at all. I did read through issue #629 which discussed running custom Python scripts.

We are experimenting with PTXprint to see if it will help us layout a diglot. I wanted to modify some of the `\lefttext` and `\righttext` before we sent the merged text to XeTeX.

Regardless of whether I select **start** or **end**, the custom script doesn't seem to run. I'm testing with a batch file that simply copies the input file to the output file. The output file is never created. And the batch file tries to write a message to a log file but the log file is never created.

Looking through the PTXprint code, I noticed a few things. I'm currently running PTXprint 2.1.22.

On line 24008 in `ptxprint.glade`, the **before** radio button is associated with id `r_when2processScript_before`. On line 20430 the **end** radio button is associated with id `r_when2processScript_after`.
```python
<object class="GtkRadioButton" id="r_when2processScript_before">
  <property name="label" translatable="yes">start</property>
...
<object class="GtkRadioButton" id="r_when2processScript_after">
  <property name="label" translatable="yes">end</property>
...
```

But on line 66 in `texmodel.py` the following code associates `project/when2processscript` with `r_when2processScript` not `r_when2processScript_before` or `r_when2processScript_after`.
```python
"project/when2processscript": ("r_when2processScript", None),
```
Then on line 1153 in `texmodel.py` a check is made to see if `project/when2processscript` is `before`. 
```python
if self.dict['project/when2processscript'] == "before":
            infpath = self.runConversion(infpath, outdir)
```

Similar issue on line 1236 in `texmodel.py` to check if the script should be run `after`.
```python
if self.dict['project/when2processscript'] == "after":
            bn = os.path.basename(self.runConversion(outfpath, outdir))
```

It seems `runConversion()` can never be called because `project/when2processscript` is never set to `before` or `after`. In fact, `project/when2processscript` is associated with a UI element that I can't find.

Any help in making sense of this would be appreciated. 

EDIT: I did read through the changes made in commit https://github.com/sillsdev/ptx2pdf/commit/3fc9c639ce5efa8b0be335d972d0b17cadbe78b1 and they seemed to be relevant.

**Comment by mhosken** [comment]
Not sure why the script isn't running for you. But to explain how radio buttons are handled in the GTK layer of ptxprint. We process radio buttons by id so "r_group_button" to allow us to look up "r_group" and get "button" as the returned value. So the coded behaviour is as expected.

If you want to dig into this more deeply, I suggest the following approach, which presumes you are running from source .This is most easily done on linux, since getting the necessary GTK dependencies and msys set up on windows machine is not for the faint of heart. See [here](https://github.com/sillsdev/ptx2pdf/blob/master/docs/dev/WinDevEnvSetupGuide.md) for the gory details. But since you have forked this project, I assume you are indeed not faint of heart :)

1. Set up the project how you want it (including setting the when to process the script, etc) and check it by printing from the GUI.
2. You can run ptxprint headless to in effect load a project and hit print. The command line options are -c config -P projectid (so for example `ptxprint -c Short -P WSG`)
3. Having tested that you get the same result (if wrong at the moment) then you can add a debug statement (`import pdb; pdb.set_trace()`) at the key point in the program and have the debugger run without having to start gtk and have them fight.

Then find and fix the bug and submit a PR or just tell us what to do whichever is easiest for you.

**Comment by da4396** [comment]
Thank you for that explanation. I wondered if there was something magical happening with the ids in GTK. I'll try running from source to see what's happening. Thanks for the suggestion.

**Comment by markpenny** [comment]
There are a couple of code snippets on [this documentation page](https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/snippets.md#process-a-file-beforeafter-ptxprint-has-processed-it) showing how to call a script before/after PTXprint has processed the text.

Closing this issue.
