### ISSUE TITLE
Psalm chapters 100-150 overwrite parts of second line

### ISSUE THREAD

**Issue by jstnlth** [sillsdev/ptx2pdf#682]
[](url
[ptxprint-Default-PSAAVU.pdf](https://github.com/sillsdev/ptx2pdf/files/8737090/ptxprint-Default-PSAAVU.pdf)
)

The chapter number can overwrite some of the characters on the second line. Seen when printing Psalms.
I also saw the problem with chapter 10 - which has two consecutive q1's. It also happens almost every time with the 3-digit chapter numbers 100-150.

**Comment by davidg-sil** [comment]
Right... Now I understand the problem better. The code is trying to be clever and not ending up clever enough.
It is assuming that a 2nd line of the paragraph will be from the first marker. If that second line would naturally be clear of the chapter number, it is (trying to be clever and) not providing any extra space, so the natural indent is preserved, rather than needlessly adding to the indent.
However when a new paragraph is started. It is counting all the cutout stuff done, so just sets a normal paragraph. If it just indented the 1st two lines by the width of the number then there would be no clash

**Comment by cmahte** [comment]
When we had this issue come up when the Psalms are set with drop cap
chapter numbers, it was treated as a manual typesetting activity. The
solution we used is to set the cursor at the end of the first line, then
(shift-right,) then (shift-enter.)  This makes the 2nd line a 2nd line
(hard return) of the first paragraph, instead of a 2nd paragraph, and the
drop cap space is respected... but verse numbers are not properly
negatively aligned. This isn't a round-trippable edit.

**Comment by cmahte** [comment]
But for ptx2pdf that isn't possible.  The solution would likely be to
replace the 2nd \q1 with \\ , but then you will often have the issue of too
many words on that second line, and likely break out of the right margin.

This is one of the cases where interactive typesetting remains a
requirement.

**Comment by davidg-sil** [comment]
Nope. I didn't read far enough into the code. It was already plenty clever enough, just the boolean was getting accidentally trashed by the pdf bookmarking code.

**Comment by markpenny** [comment]
@jstnlth Could you please check to see if you're happy with the fix. And if so, please close the issue. If we haven't heard back in a few days, then we will just have to assume all is well and I'll close the issue myself.

**Comment by jstnlth** [comment]
The last version of linux available
     PTXPrint Linux 22.04 2.1.22     for
      Linux Ubuntu 22.04 LTS     DEB | 5.85 MB | 13 May 2022 
    
    does not include these patches.
    
    
    
    
    
    On 5/26/22 5:21 AM, Mark Penny wrote:
    
    
      
      @jstnlth
        Could you please check to see if you're happy with the fix. And
        if so, please close the issue. If we haven't heard back in a few
        days, then we will just have to assume all is well and I'll
        close the issue myself.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/sillsdev/ptx2pdf/issues/682#issuecomment-1138107285",
"url": "https://github.com/sillsdev/ptx2pdf/issues/682#issuecomment-1138107285",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by markpenny** [comment]
Sorry @jstnlth -- my bad! We're about to push out 2.1.26 in an hour or so, and I'll be able to upload the .DEBs for that a few hours later (tomorrow). BTW - you can always find the latest .DEBs [here](https://launchpad.net/~silnrsi/+archive/ubuntu/ptxprint/+packages). One day we'll get around to automating this so that they show up on the SIL site as soon as they've been built, and not just when I remember!

**Comment by markpenny** [comment]
@jstnlth The 2.1.26 DEBs are up on the [SIL site](https://software.sil.org/ptxprint/download/) now.
![image](https://user-images.githubusercontent.com/12962708/170694761-a40f914b-bd76-4b4a-a84e-0334e5f68ea8.png)
Oops! Looks like the little penguin can almost run headless ;-)
