### ISSUE TITLE
PrintDraftChanges does not get applied

### ISSUE THREAD

**Issue by KentSpiel** [sillsdev/ptx2pdf#687]
I  wrote the following change in Advanced | changes.txt and applied it to the usNIV11  PSA text:
'\\ms(?=\s)' > '\\zms'
The Generate Final SFM  output was as expected:
````
\id PSA ‑ English-US: New International Version® NIV® 2011, updated 2016
\h Psalm
\toc1 Psalms
\toc2 Psalm
\toc3 Ps
\mt1 Psalms
\imt Introduction
\im The book of Psalms is a collection of song lyrics. Like many songs, they were first written in response to events in the lives of their
  . . . 
\ie
\c 1

\zms Book I
\mr Psalms 1–41
\cl Psalm 1
````
I moved the code to  PrintDraftChanges.txt and applied it to the usNIV11  PSA text in exactly thew same way.
The Generate Final SFM  output was not affected by the change:
````
\id PSA ‑ English-US: New International Version® NIV® 2011, updated 2016
\h Psalm
\toc1 Psalms
\toc2 Psalm
\toc3 Ps
\mt1 Psalms
\imt Introduction
\im The book of Psalms is a collection of song lyrics. Like many songs, they were first written in response to events in the lives of their
  . . . 
\ie
\c 1

\ms Book I
\mr Psalms 1–41
\cl Psalm 1
````
The result was confirmed by PDF output and other various attempts to use  PrintDraftChanges.txt

**Comment by markpenny** [comment]
![image](https://user-images.githubusercontent.com/12962708/170894539-e53e6076-e262-4881-b714-114d3b26f5dd.png)
As far as I am aware, only changes.txt gets called BUT the include statement (which is in there by default) and explained at the top of the file pulls in the PrintDraftChanges.txt file. Of course, a user who doesn't want to use it can just comment it out with a 3 at the start of the line.

![image](https://user-images.githubusercontent.com/12962708/170894635-98cc60f8-0ad3-49d5-909f-26bdb733df60.png)

@KentSpiel Are you saying that you're not seeing this behaviour? If so, that's a bug.

**Comment by KentSpiel** [comment]
First of all thank you @markpenny  for the response. You can probably close this issue, as this was a failure on my part to understand the instructions. 

When I first opened advance tab, and note I did this as someone who hasmd never used this tab before. All I wanted to do was to first see if I could get changes applied to the text. I didn’t want interference from an include statement , which I honestly still don’t know what to expect  if it’s included.** So what I did was to delete all the text and just put a simple find replace. Once I did that I lost all of that information. 

**Having reflected on the instructions I believe I may now understand them.  If I’m correct the include statement will pull all the Regex from PrintDraftChanges.txt and put it in that location in the series of Regexes that will be applied to the project. Since the Regexes are applied sequentially, any Regex before the include statement will be applied to the text first, and any Regex after will be applied after all of the Regexes in PrintDraftChanges.txt are applied.

To someone who’s a programmer this is probably obvious. But I doubt if most of our users will understand what’s going on without some instruction.

A couple other comments:
* Since it looks like a series of relative path statements before the file name, I also assume I could specify DBLchanges.txt or any other file just as easily. 
* It’s perhaps not obvious that the Print Draft Changes window is an actual editing window for the PrintDraftChanges.txt file In the project directory.
*  That said, once you understand what’s going on it’s a very nifty  place for making changes, very convenient. Especially with the output text available immediately.

**Comment by markpenny** [comment]
Our hope is that 'normal' users never have to dabble with the changes.txt and PrintDraftChanges.txt files (as usually all the settings they need to tweak should be in the basic area of the UI).

Yes, you could include any other changes file as long as you get your relative path right.
The decision to keep changes.txt and PrintDraftChanges.txt independent was due to having [extended functionality](https://docs.google.com/presentation/d/1johZJH26dep3Z4mS9UTQhmrwZjuMfx7y1IWZn28RcUk/edit#slide=id.g1194f7726d1_0_8) available in changes.txt (which isn't available for the regular PrintDraft feature). 
We do use tooltips quite a bit to hide useful information; and if you hover over the names, they will tell you exactly which file you're editing:
![image](https://user-images.githubusercontent.com/12962708/171078524-09ae9996-2b85-4712-a834-1ffec3c4b7f6.png)

and

![image](https://user-images.githubusercontent.com/12962708/171078557-5bc26b6b-a2b6-4f57-9543-feca53e7ce90.png)
