### ISSUE TITLE
interline spacing in footnotes

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#69]
Compared to the interline spacing in my text (which is a larger font size), the interline spacing in my footnotes is way too large:
![image](https://user-images.githubusercontent.com/14953913/82420686-fa56ce00-9a77-11ea-9b96-65f7c2e13fd5.png)

I don't see an option to adjust that in PTXPrint. Is there at least a manual override that I could put into ptxprint-mods.tex?

**Comment by davidg-sil** [comment]
Try setting \BaseLine in the style file for \Marker f  (and x, etc). Rather unconventionally,  this takes an absolute measurement, not one affected by \FontSpaceUnit or \LineSpacingFactor. (Maybe this ought to be changed, in the interests of scalable output?,  @mhosken, opinion please; it came in as part of the ptxplus macros). Example:
\Marker f
\BaseLine 10pt

Note that if you set it to a very small number (e.g. 0pt), then the lines will (mainly) not overwrite one another, but will be stacked without any extra space (the bottom of y and top of T, say,  would touch). 'Mainly' because things like a superscript caller don't seem to contribute to the height of a line.  I can't remember about accents.

**Comment by markpenny** [comment]
MH has just added the option to adjust this with \LineSpacing (in the .sty file) so that you have complete control over this. Given that this will be a common request, I'll be adding a control to the UI later today and hopefully sharing 0.6.7 tonight.
![image](https://user-images.githubusercontent.com/12962708/82429165-1e7ed300-9aa9-11ea-937a-0c480bb8acdb.png)

**Comment by markpenny** [comment]
0.6.7 is now available, and allows you to change the FontSize and LineSpacing for the notes in the UI, but this *can* be overridden by the PrintDraft-mods.sty file settings (so you may need to delete settings in there - if it is being applied).

**Comment by jeffheath-sil** [comment]
This seems to do the trick. (Once styles were commented out in the PrintDraft-mods.sty file...) Thanks!
