### ISSUE TITLE
Pop-up help for settings search not localisable

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#695]
As seen here in the French UI, and a search in Crowd-in doesn't find that string:

![image](https://user-images.githubusercontent.com/14953913/173603865-403d1951-44b3-427f-8e75-a8ca0caf1c72.png)

**Comment by markpenny** [comment]
Thanks for the heads-up. Sorry there was a mismatch between the Crowdin and program string which I have now fixed. It will be working correctly in the next version. [My hope is to use F1 to jump to the Help tab rather than have 2 shortcuts to do the "Find".]

BTW - there was a mixup of branches which meant that the most recently translated strings didn't get into 2.2 as I was hoping. They are, however, now in 2.2.1 which was released yesterday.

![image](https://user-images.githubusercontent.com/12962708/173695376-a5888623-1149-4f7b-b6e6-87b4db09b524.png)
