### ISSUE TITLE
Adding tabs in the in the Strongs Index list

### ISSUE THREAD

**Issue by KentSpiel** [sillsdev/ptx2pdf#699]
I want to use the Strong's index function to encourage translators to do a better job on their Biblical terms list. I am teaching a Workshop starting this Monday. Languages are Indonesian Malaysian and Hiligaynon. 
I created a Strong's index from from their unfinished NT project. I thin it would look better if the list were tabbed after the Strong's numbers. is this possible?
I saw Mark Penny's out put and am wondering if the settings could be improved for this project. 

Other issues: I cannot share this configuration with another project because of the number of protects I have in my system. Please watch video: https://screencast-o-matic.com/watch/c3iibJV04WZ

[ptxprint-Strongs-XXSidKKH21_1.pdf](https://github.com/sillsdev/ptx2pdf/files/9067000/ptxprint-Strongs-XXSidKKH21_1.pdf)

[idKKH21-StrongsPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/9066998/idKKH21-StrongsPTXprintArchive.zip)

**Comment by markpenny** [comment]
@KentSpiel I loved the video :-)  Will try to add a scroll button to that Copy Config dialog. But I must confess we weren't thinking of users with 400 projects on their system!

As to the tab after the Strong's number - we'll see what is possible when the TeXperts return from their summer break.

**Comment by davidg-sil** [comment]
I'm not 'returned' but I'm around occasionally, and I'm wondering what you mean by 'tabbed' in this context. Do mean allocating a fixed width for the strongs number? (as if there were a tab there)?

**Comment by markpenny** [comment]
@KentSpiel I've fixed the "cannot share this config" because of too many projects. There is now a scroll-bar which should make it easier to work with 400+ projects!
![image](https://user-images.githubusercontent.com/12962708/178663948-6a311c7a-3887-40db-9fa3-08cfdeddacc8.png)

This will be available in 2.2.4 (hopefully later today).

**Comment by markpenny** [comment]
> I'm not 'returned' but I'm around occasionally, and I'm wondering what you mean by 'tabbed' in this context. Do mean allocating a fixed width for the strongs number? (as if there were a tab there)?

Yes, I'm pretty sure @KentSpiel means that after the strongs number we need to 'tab' to the indent position of the paragraph. (I have no idea how to do this, but can't imagine it would be too hard in TeX).

So what he is saying is that this looks really bad:

![image](https://user-images.githubusercontent.com/12962708/178664823-b78adef6-ae94-442e-892f-a01e8b398974.png)

...and that this is slightly better (because of wider numbers), but is still not quite right (and needs a tab to align the start of the Greek/Hebrew words):

![image](https://user-images.githubusercontent.com/12962708/178664894-741738b4-5ab6-453c-b502-4c18b77cd916.png)

**Comment by KentSpiel** [comment]
> So what he is saying is that this looks really bad:

Yes that is exactly what I am saying. 
K

**Comment by mhosken** [comment]
This hook off the top of my head, untested, written on my phone. Put this
code in your ptxprint-mods.tex

```
\sethook{start}{k}{\setbox0=\hbox{9999}\hbox to \wd0\bgroup}
\sethook{end}{k}{\hfil\egroup}
```


GB,
Martin

**Comment by markpenny** [comment]
@mhosken I just tried that and *something* happens, but not quite what any of us were expecting:

![image](https://user-images.githubusercontent.com/12962708/178990936-09755903-2725-4c82-aa31-0ba3bd97a626.png)

Can you suggest a tweak to that code that might fix it?
