### ISSUE TITLE
What are the measurements used in Custom.sty and PrintDraft-mods.sty?

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#71]
MEASUREMENTS?
So anybody know what the measurements being used in Custom.sty and PrintDraft-mods.sty? 

Seems like it is sometimes points, and sometimes inches, and sometimes a %. So maybe we need a field at the top of the file that specifies the units of measure used, like:

\units inch
or
\units mm
or 
\units pt   (as in point size -- like in fonts) 
or 
whatever. 
Right now it feels like we are just guessing. 

I suppose it would complicate the whole program to do like Office, where you can add a code to indicate what you mean:

\FontSize 10pt
\LeftMargin 0.5"
\RightMargin 127mm
\FontScale 95%

I'm *not* suggesting any particular direction. But I'm pretty sure the current loose Paratext standard will confuse any normal person trying to use PTXprint. 

So minimally a header section in PrintDraft-mods.sty that lists what the current standard is would help:

Line 1: # FONT Specifications
Line 2: # \FontSize 10     (this is given in POINT sizes)
Line 3: # \FontScale 0.95  (this is given in the decimal equivalent of a %)
Line 4: #
Line 5: # PARAGRAPH Specifications
Line 6: # \LeftMargin .50 (this is given in INCHES)
etc.

So, yeah, the current specs are messy. Any help in getting it right would be a big bonus to the rest of us!
(If these oddities are documented somewhere, then disregard this "issue" and kindly direct us to that documentation. Thanks.)

**Comment by markpenny** [comment]
I fully agree that it is rather confusing. Sometimes it is a "factor" other times it is an absolute value (in mm pts inches or ???) and now we've also added a scale/percentage.
When we have things in the UI, I've tried to ensure that the tooltip specifies the unit. But your observation is about the .sty files (which *we* don't control). People already have these on their system (as they came with Paratext or got generated by PTs PrintDraft).
So yes, we do need to document them somewhere (in the short term) for people like you who are not shy to dabble in the .sty files to achieve the results needed. @davidc86 - I'd like to share the FAQ GDoc with you to EDIT so that you can also add to it (and be a blessing to all who follow in your footsteps).
But our longer-term plan is to have a UI Stylesheet editor inside PTXprint where it would be clear to the user what the units are and what options can be turned on/off or tweaked for each marker (I'm guessing something like SAB's style editor).
