### ISSUE TITLE
v2.2.8 "nopagenums" does not work in the INT book

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#711]
I was hoping to suppress the page numbers in the INT book (which follows the FRT book). I added a "\nopagenums" field into the Paratext INT book, and I see that SF in the "Final SFM" tab for INT, but it is not at the left margin, it is appended to the previous line: 

\id INT ‑ Selaru
\periph Introduction
\toc1 Tun Mamunake

\toc3 Tunke
\zthumbtab PND \nopagenums
\imt1 TUN MAMUNAKE
\is1 TATA BAHASA
...
Not sure if that makes a difference, but it doesn't appear to work, as page numbers still appear in the INT part of the PDF file.

**Comment by markpenny** [comment]
Could you try moving \nopagenums earlier up in the INT book so that it comes before any of the content (as shown in this example)?

Also note that if you want i, ii, iii, iv, v style of numbering for your introductory matter, you can use a negative value when you \resetpagenums

![image](https://user-images.githubusercontent.com/12962708/182485560-4bef4c57-6af5-43aa-81aa-0adf8df0df1f.png)

**Comment by davidc86** [comment]
I tried this field in the INT book and it has no effect.
It does work in the FRT (local) book. Maybe it only works there?

**Comment by davidg-sil** [comment]
I'm not aware of much magic happening that should stops things working in INT but leave them happily working in FRT. 

So, I'm guessing here, but I expect the issue here may be TeX reading ahead. D.E.Knuth (p.38, The TeXbook) writes it being useful to use the analogy TeX being an animal with mouth and a stomach. It also has output mechanism which we can call its guts, I guess, where stuff is stored up ready to output (don't over-think the analogy, please). Most things happen in the stomach, but they affect what happens at the mouth and guts. `nopagenums` and `dopagenums` work by turning off/on the bits of code that are used in the guts to make page numbers.
 That change takes effect as soon as the input gets to the stomach. But the processed material might not have left the guts yet.

There is nothing magic about the `\rem ---page3 ---` etc. markers in Mark's example. They don't make it stop 'digesting' stuff until the guts are empty. So if it's finished digesting the `dopagenums` before it has output the earlier page, then dopagenums will have come back into force.  Verse numbering  makes use of a special mechanism so that they survive the the 'stomach'. It may be that we need to do something like that with page styles, too.
 
Having said all that, if it *is* a read-ahead issue, then you could try *only* having `nopagenums` in the INT book, and then put this into the your ptxprint-mods.tex:
```tex
\sethook{bookstart}{GEN}{\dopagenums}
```
Which will run `dopagenums` at the start of GEN. (use `all` instead of `GEN` for it to  every book). The start of a book should be met after any end-of book page-break.

**Comment by mhosken** [comment]
We have made a change to how INT is processed. It is assumed that INT contains a bunch of periphs that are going to be used elsewhere. Thus you would reference the various periphs from the FRT book, for example. You can do this using:
```
\zgetperiph|title\*
```
Then you can set up the breaks and page numberings how you want in the FRT (is probably the safest place).

**Comment by mhosken** [comment]
Secondly, I advise against randomly placing a \nopagenums on the same line as a \zthumbtab that is parsing to the end of the line to get its value. We try our best but poor old TeX isn't psychic, even if we want it to be!
