### ISSUE TITLE
Strange diglot (alignment/layout) issue

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#721]
I'm raising this issue so that we don't lose track of it.
![image](https://user-images.githubusercontent.com/12962708/185533967-740abe2e-7d9b-43b9-8f0b-a2d2c157761d.png)

 I'm guessing it is because of the footnote (in the WSGEngBT text at the end of v22) being pushed onto the next page, and then it is getting muddled...

I changed the margins from 12mm to 11mm and the problem disappeared (i.e. the aligner did the right thing -- after all these are parallel texts with identical structure) but because of the footnote shifting at the last moment, it gets in a muddle [I think... without knowing anything about TeX]

**Comment by davidg-sil** [comment]
Interesting facts about this bug after an afternoon of digging... 
* The footnote caller for v22 is lost, along with 2 lines of text. The note text ought to be on p.31.
* The error is noticed in the log file with some  `EEK` messages. - execution flow has ended up where it shouldn't have.  But by this time the missing lines of text have already been lost.
* There are also some `ODD` messages. These are probably due to footnotes that don't fit, and are relatively normal.
* If I turn on `VisTracetrue`, then the text is laid out correctly (even though there ought to be no difference at all):

![image](https://user-images.githubusercontent.com/58848232/195176532-7ee7aa4a-2169-47b5-bdcf-134075b0ab4b.png)
![image](https://user-images.githubusercontent.com/58848232/195176607-4ae762ae-ed38-40c9-b64c-80c7b2a31014.png)

* The vanishing text happens to the chunk that is rebuilt (twice) at log-references 5876 and 5927. But these numbers  change with VisTrace  on. Probably this is due to the /~1sp/ mark kern that is used as a joint marker.

More digging is needed!

**Comment by davidg-sil** [comment]
For reference, the actual divergence between working and broken is here:

![image](https://user-images.githubusercontent.com/58848232/195183307-635084f3-b9d5-4c12-8ac5-b41686e180c8.png)

In the broken mode, code flows off the bottom of diglotanytrial, and doesn't get an output-causing penalty.
Presumably because there's less material to pick up?
Why doesn't TeX break at the penalty in both cases??

**Comment by davidg-sil** [comment]
Probable bug-fix pushed.
For the sake of documentation, the above behaviour was caused by an undesired page-break slipping in, combined with a 'tail' that was all discardable items.  Note to self: glue,kern and penalty are all discardable, but it's only a break-point if it is followed by glue. Glue is a breakpoint if it is preceeded by something undiscardable.
[Page 110 TeXbook.]
Thus the sequence kern,glue,kern gives TeX a break-point.

![image](https://user-images.githubusercontent.com/58848232/195355971-d15aa60b-f5af-470e-b97c-fc8f830fcee1.png)
