### ISSUE TITLE
Help | PTXPrint Docs Path link opens app not help

### ISSUE THREAD

**Issue by cdfarrow** [sillsdev/ptx2pdf#730]
PTXPrint 2.2.22
Clicking on the link above opens the app, whereas the description implies it is going to open a help folder or something. (I can't see anything in that folder that looks like help or documentation, besides the about file.)

**Comment by markpenny** [comment]
@cdfarrow  - this points to the Program Files\PTXprint folder because at one point in time, there was no other documentation at all, and the only place we said something useful was in the readme.txt file there! Fortunately those days are behind us now. But I'm still left pondering....

As a user, would you prefer this to link to [this page](https://software.sil.org/ptxprint/documentation/) (on the main site) which is targeted to everyday users? 
   OR
Would you prefer it to point to [something like this](https://github.com/sillsdev/ptx2pdf/tree/master/docs#readme) with a lot more technical detail than most care to read?

Or the compromise solution would be to point "Basic" view users to the 1st and Full view users to the second?

**Comment by cdfarrow** [comment]
I don't think the *link* should change depending on the view -- that would create confusion. I suggest linking to the first, with the heading "PTXPrint documentation" and _include this in the Mini and Basic views_. For more advanced documentation, [this file](https://github.com/sillsdev/ptx2pdf/tree/master/docs/documentation) (or the PDF version) seems better and looks really helpful. I suggest making it a second documentation link called "PTXPrint technical documentation" that is added in Full View.

**Comment by markpenny** [comment]
Mini view:
![image](https://user-images.githubusercontent.com/12962708/193222448-b2f18c13-6291-4228-b03c-a17616939b50.png)

Basic view:
![image](https://user-images.githubusercontent.com/12962708/193222566-b3502390-a6d1-4303-863d-8729d3493890.png)

Full View:
![image](https://user-images.githubusercontent.com/12962708/193222662-6fd73f48-8d7b-46c5-a31c-53a0132d7417.png)


> For more advanced documentation, [this file](https://github.com/sillsdev/ptx2pdf/tree/master/docs/documentation) (or the PDF version) seems better and looks really helpful.

Most of the information in that old/historical document is no longer relevant as the UI takes care of almost everything in there. However, the link to [this page](https://github.com/sillsdev/ptx2pdf/tree/master/docs#readme) contains lots more links to specific and up-to-date information.
