### ISSUE TITLE
The Front Matter tab on the View and Edit page is confusing

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#733]
The behavior of the Front Matter tab and other tabs on the View and Edit page are confusingly different.
If the Front Matter tab is selected, the drop-down list above it doesn't work.
If I click on Final SFM, then the drop-down list becomes active and might even point to some other book.

The Front Matter and some other tabs can be edited, whereas the Final SFM tab content cannot. (Understood that Final SFM is displaying the results after processing, so editing at that point is moot, yet this difference in behavior in the same window is a bit confusing.)   

I'm not sure how to make the UI easier to comprehend, but it currently feels a bit like two or more different functions merged into one display.

Would it be easier to comprehend if the Front Matter file had its own page? Since this is NOT the FRT book from Paratext. 

Also, providing a "Starting SFM" before the "Final SFM" would be useful to me. If I'm looking for "what changed" this would give a quick and easy way to compare what processes had altered the SFM file.

I'm sure you all have scratched your heads a lot over this page. And maybe just leaving it for now is fine. But it catches me out almost every time I go to it. I suspect I'm not alone. But sorry I don't have any great ideas either!

**Comment by markpenny** [comment]
I agree that the View+Edit page is confusing. Part of the reason is that has continued to grow/evolve to take on additional functions that weren't originally intended to be there. But, having said that, at least you know if there's something longer than a few lines that needs to be seen or edited, it should be available on that page/tab.

I'm wondering if just a simple re-ordering of the buttons on the left would help:
![image](https://user-images.githubusercontent.com/12962708/191628521-a065f6b0-86ba-4b09-883a-6062cdd1c3f6.png)

The (i)nfo button ONLY applies to Front Matter, the Generate applies to the 1st three tabs, the book in focus applies to tab 2 and 3 and so is "above" them.

I think we have removed the FRT book from (all) the book lists intentionally as we don't want people to believe that they can EDIT Paratext's FRT file here in PTXprint. What they are creating/generating/editing here is a "local" PTXprint-specific Front Matter file.

I agree that it would often be nice to be able to see the "Starting SFM" BUT the next question would be, "Why can't we edit the starting SFM?" and then we're really in trouble. So to keep us from that scenario, we have intentionally stayed clear of making that an option. Even if we opened it in a "View Only..." tab, there is nothing stopping someone from clicking View, and then EDITING their USFM text in an editor, and getting clashes with Paratext etc. So I'd rather not go there. Those who know what they're doing (and are less likely to mess things up) know how to get there anyway...

**Comment by markpenny** [comment]
> which widget goes with what tab?

The bottom line is that the buttons/widgets at the top either gray-out (to show that they are inactive/inaccessible) or disappear altogether depending on which tab is active at the time. So anything that is still Black (and not gray) applies to that tab.
