### ISSUE TITLE
Problems with the bottom margin values, for positioning footer

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#742]
I think there is a bug, or a mislabeling of the bottom margin fields in the Layout tab > Margins. In my PDF I have this at the bottom of a page:
![image](https://user-images.githubusercontent.com/14953913/192356373-f2e1bfed-fc9a-446c-b119-286568c3b56c.png)

I would like to move the page number down. Here are the current values for the margins:
![image](https://user-images.githubusercontent.com/14953913/192356430-9c88b757-9145-48b3-a1c6-6efbe299d4c6.png)

So looking at the helpful little picture, I see that I want to make the blue line shorter, "Top of Footer to End of Page (mm)". so I change this from 9.0 to 7.0. Now this is what I get:
![image](https://user-images.githubusercontent.com/14953913/192356738-a940bb2f-e9f6-4ad7-9986-6e486310e021.png)

The page number hasn't moved at all, and there is less text fitting within the box.

To get what I want, it seems like I need to decrease "Bottom of Text to End of Page (mm)" and decrease the "Top of Footer to End of Page (mm)". This seems incorrect to me, or am I missing something?

**Comment by markpenny** [comment]
@jeffheath-sil We added an option (on the Advanced tab) a few weeks ago which allows the Intro page number(s) to go down into the margin (previously no-ink area). Please check if that is turned on, as it seems to be important in this instance:

![image](https://user-images.githubusercontent.com/12962708/192703468-0189f912-15c4-410b-84f6-9fc20c3d8633.png)

Then when you adjust the Top of Footer to End of Page setting, you should get the behavior you're expecting:

![image](https://user-images.githubusercontent.com/12962708/192704453-6906b813-f500-4f9b-bba0-3b198534c385.png)

**Comment by jeffheath-sil** [comment]
That doesn't really make sense to me. (And if I'm confused, there might be others...) In your PDF above, where is the page number and reference in the right-hand page (i.e. the "normal" page)? It's in the header, which is found in the top margin. And you set the parameters to adjust the size of the colored arrows. So if you want the page number at the bottom (in my case, they want the page numbers for all of the pages at the bottom of the page, not just the first page of the book), you would put it in the footer, which should be found where? I would say in the bottom margin, i.e. outside the normal text space, right? If you uncheck your new "Put Footer in Margin Area", then where would the footer go? In the normal text area? I guess if it's just for the first page of each book, I could see why that might be important, e.g. normally the text of each page goes down quite far on the page, and you don't want the page number of the intro page to go below that.

Regardless, your blue and red arrows and text descriptions in the footer do NOT do what they say they do. Maybe they should say what they say now if the checkbox is checked, but if it isn't, it should look differently? And if so, maybe that checkbox should move to this layout page (under the footer parameters), so people know that there are different options and how the options affect the parameters they are entering.

And as a side note, I find it interesting that there are not more ways to format the footer. E.g. in my case we want the page numbers at the bottom of each page, as the team didn't want it confused with the reference at the top of the page. As far as I can tell, the only possibility for putting the page number at the bottom is to put it in the center of the page. I can't put it in the "Outer" position, like I can with the header. Is that because it is generally not recommended behavior for Scripture typesetting (to put the page number at the bottom of the page), so you don't want to offer more options for how to do it? I see that Paratext print draft only allows putting information in the header, so maybe I shouldn't complain...

**Comment by mhosken** [comment]
Looking at the macros. It looks like the blue arrow is wrong and should be to the bottom of the footer line rather than the top. That is the Bottom of Text to End of Page is right, but the top of footer to end of page should be 'bottom of footer to end of page'. Does that fit with your understanding? In effect, the only thing that adjusts the position of the footer is that blue figure.

As to "Put Footer in Margin Area". This is included for those who hold that no ink should go into the bottom margin. The margin is whitespace and all else exists above that. The effect, therefore is to move the whole footer up such that the bottom of the footer has the space below it of the red value. The question is what is the best way to present this to users. Perhaps the diagram needs to change if the flag is set.

Here's a proposal to change those settings. The red value remains the same, except if the flag is set, it changes to "Bottom of Footer to end of Page". The blue value becomes "Bottom of Text to Bottom of Footer" and remains that way. Then we have two diagrams. Without the flag set the red line remains and the blue line goes from the bottom of the text to the bottom of the footer. With the flag set, the red line goes from the bottom of the page to the bottom of the footer and the blue line goes, as in the non-flag case, from the bottom of the text to the bottom of the footer.

This will involve a little maths in the code, but nothing too hard. It'll also take a version bump in the config to change the blue value (to red - blue)

**Comment by mhosken** [comment]
OK, well the current system doesn't work the way described in my last message. The plan is to refactor the footer to be described much like the header. That is to specify the size of the margin and the distance from the text to the top of the footer. If the Footer in Margin is unset, then the footer will rise to sit on the margin and the text go up above that. Notice that this flag results in a dynamic movement, if the footer for a page is empty the main text runs down to the margin. If there is content in the footer then the text rises to give space for the footer above the margin. So in the case of a bordered page, it would allow the footer to go inside the border, if that were desireable.

We'll move the "Footer in Margin" control onto the layout page and have the graphics adapt so that people can see what they are doing.

**Comment by markpenny** [comment]
I'm still wondering if we need to disambiguate the "Footer in Margin" label. Does this mean, place the footer in the margin area, or does it mean keep the footer WITHIN the margins?

![image](https://user-images.githubusercontent.com/12962708/193195555-f053c9c1-2f64-4b6f-bb10-fe16235b3f8a.png)

![image](https://user-images.githubusercontent.com/12962708/193195622-cd13e2e2-2b72-4c4c-8e9c-d4b574b36f85.png)

**Comment by markpenny** [comment]
Fixed wording:
![image](https://user-images.githubusercontent.com/12962708/193369370-2f5019d3-f2cd-42fc-8999-62f93cd1b3f5.png)

**Comment by jeffheath-sil** [comment]
Sorry, I haven't had the time to follow the last couple of posts. But I'm still wondering about how this is coming out. The checkbox says "Don't Place Footer in Margin Area", but what is the bottom margin area? Where is that defined? It seems like those two numbers are the only thing defining the size of the bottom margin (the red number) and then where the footer is placed within that (the purple number). So what would checking that box do or not do?

**Comment by markpenny** [comment]
@jeffheath-sil Please try out 2.2.30 which was just released last night. I think it should be much clearer for everyone in this latest release which ALSO animates the effect of checking that "Don't Place Footer in Margin Area".

![image](https://user-images.githubusercontent.com/12962708/194949500-45e8f058-2909-41de-963f-b262051a65a9.png)
