### ISSUE TITLE
Add hourglass for long running actions

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#743]
v2.2.25 "Not Responding" when switching from one Paratext Project folder to another.
It eventually switched, but it took PTXprint an inordinately long time to switch.

**Comment by davidc86** [comment]
Well... bummer. The first time I did this it crashed. The second time I did this it hung for quite a while. But now the third time (when I had my watch ready to measure the hang time) it instantly switched! Sigh.

**Comment by mhosken** [comment]
If you had lots of subdirectories with no Settings.xml in them, then the first time you switch to that Projects folder then it will take a while whilst it goes through creating Settings.xml files and reading ALL the SFMs in all the subdirs. So that could account for the rather long wait.

**Comment by davidg-sil** [comment]
Maybe there should be an hour-glass icon or a message that says what it's up to and why it might take ages?

**Comment by davidc86** [comment]
Well, hmmm. I just installed v2.2.26, I use the projects in SLU and FRD all the time yesterday and for many days previous. I started v2.2.26 in FRD (because that is what I was working on before). 
Then after working in FRD, I wanted to test picture import from back matter in SLU, so I switched to Basic page and selected SLU from the list. PTXprint HUNG. Or if not hung, it's pretty darn close to it. It won't respond to clicks or anything. After several minutes I had to kill the process.

After killing it and restarting it, I was able to switch to SLU almost instantly.

**Comment by davidc86** [comment]
Well, when thinks are working as they should these events are usually very quick. 
And the longest process (printing the PDF) already has an indicator.
So, I'm not convinced this is too important for the software, when it is running, but it does need something to let users know that it is starting up, because PTXprint can take a very long time to display after the icon has been clicked on.

**Comment by markpenny** [comment]
We recently found a bug where it was (unnecessarily) reading ALL the SFM files on startup to figure out which books were present. Instead of only doing this for specific cases where no settings.xml file had been found, it was doing it every time. That's been fixed now, so hopefully we won't see these delays as much now.

Most of the long waits are when XeTeX is away processing everything we've told it to typeset, and we can't really update the UI then, just each time it comes back for a re-run we can move the status indicator along...
