### ISSUE TITLE
Select by verse as well as by chapter

### ISSUE THREAD

**Issue by davidg-sil** [sillsdev/ptx2pdf#76]
If someone wants to print out the account of Abraham, say, they might not want Babel (beginning of Gen 11), or the line  of Ishmael and the beginning of the 'generations' of Isaac. It would be nice if chapter & verse could be  selected, rather than just chapter. It would be even nicer if multiple ranges of  chapters and verses could be selected. E.g.  one project has these passages consultant checked in Exodus: **1—20; 32—33; 34:1-7; 35:4-35; 36:1-7; 40:34-38**, but there are potentially other verses in the book that have been asked for since and might have only had community checking.

Limiting based on the [\sts ](http://ubs-icap.org/chm/usfm/3.0/identification/index.html#sts)code is of course one way to do this, but I don't know how many actually use it. Older documents suggested  the codes be **1**: first draft, **2**: community checked, **3**: consultant checked, **4**: published)

**Comment by davidc86** [comment]
Excellent. Does current behavior already allow for selecting non-contiguous chapters? I'm just thinking of Psalms, where several projects have completed "selections" of that book, rather than every chapter in it. So some chapters are "draft" while others are "approved". For these projects, being able to select only approved chapters for publication would be sweet.

**Comment by davidc86** [comment]
For those who use it, the current the "Paratext Progress Chart" feature tracks the "status" of each chapter of a book. Might this be leveraged for this purpose? (But not down to the verse level) Rather than depending on the human to keep their \sts fields up-to-date (if they even know about that field). I believe most Translation Orgs are pushing the use of the Progress Chart, and anything "completed" up through Level 5 (or 6, depending on the org), would be "Good to Go".  
Just a thought.

**Comment by davidg-sil** [comment]
The progress checking stuff is burried inside XML. I don't wish parsing it
on anyone!

**Comment by davidg-sil** [comment]
ptxprint doesn't have this behaviour yet, the command-line ```diglot_merge.pl``` program that merges 2 .sfm files for diglot typesetting (see branch 'diglot') does seem to have the capability, so maybe when a python expert who also reads perl  can merge it into ptxprint, that capability will become available.

**Comment by mhosken** [comment]
How do we say whether to include introductory material? If you ask for 1:1 you get the intro material as well?

**Comment by davidg-sil** [comment]
I think if you say 1:0 you get the intro material, but saying 1:1 means you're skipping it.

**Comment by markpenny** [comment]
@mhosken  as you think about and work on subsets of USFM, you now (also) need to be aware of Paratext **Priorities** (subsets of scripture books/chapters) which are explained well by @philleckrone in [this video](https://vimeopro.com/lingtransoft/paratext91/video/450506600)

**Comment by markpenny** [comment]
@viverechristus I think the last of your wishes has already been in place from pre ver 1.0

![image](https://user-images.githubusercontent.com/12962708/139823900-32ec304f-7d55-41ca-956e-43273d9baa15.png)

Is that what you mean? Anyway, it has been a long time since I tested that feature. Try it out and let me know if it does what you're after, or if it is broken/buggy.

**Comment by viverechristus** [comment]
@markpenny  I'm afraid that clicking "Filter Glossary" doesn't affect whether a glossary is produced -- only which entries show up if it is. To produce a glossary at all, it still has to be one of the books chosen on the Basic tab, and the only way to select the GLO is to select it along with another (complete) book (or print the GLO as a stand-alone).

So if I select GEN 1-11 under Basic > Single Book, then select "Filter Glossary..." under Body, no glossary is printed.

Incidentally, the "Filter Glossary..." option seems to do no work at all for me these days (2.0.4). I selected Body > Multiple Books > GEN GLO, then Body > "Filter Glossary...", then Print. What I got was a complete glossary rather than one filtered to include only entries from Genesis.

Thanks for following up about this.

**Comment by markpenny** [comment]
@viverechristus Ah, yes, now I remember. It is the fact that you can't select the GLO book (as well) if you are printing selected chapters (as that option is only available for single-book publications).

@mhosken Could we enhance the book-list system to parse for specific chapters so that someone could do these kinds of things?
**GEN 1-11**; GLO
INT **LUK 16-24**; **ACT 1-4**; GLO; BAK

**Comment by davidg-sil** [comment]
IF code is being added to do this, then (as per my initial issue requests) please can it allow Gen 1:1-11:26, etc.? I think that when the request initially went in, there was no parsing in the code-base. That's not the case now. 

Verse ranges are a bit of a pain, as are sub-verses, but (a) no one can split \v 1-3a by hand, so they shouldn't expect the computer to, and (b) someone can always craft a custom script if they really need to not print a particular sub-verse, so I think that we can come up with something relatively sane.

**Comment by markpenny** [comment]
So we need to be able to specify **books** and/or individual or ranges of **chapters** and/or **verses**:

> INT LUK ACT GLO
> GEN 1-11; GLO
> INT LUK 16-24; ACT 1-4; GLO; BAK
> GEN 1:1-11:26; PSA 119:1-40; JAS
> PSA 23,51,86,91-95,118

Is there anything else?

**Comment by viverechristus** [comment]
I didn't have anything else in mind, no.

Josh Jensen

**Comment by markpenny** [comment]
This has been implemented and will be available in 2.1.5 whenever that is released.
