### ISSUE TITLE
The illustration copyright info is not correct/as useful as it used to be

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#763]
v2.2.34 
The illustration copyright info is no longer in the correct format. Or if this is the new format, it is NOT as useful as it used to be.

These illustration copyright lines USED to give the page numbers for the pictures of the relevant artist. Now they do it backwards! And since we use David C. Cook mostly, and rarely use Louise Bass or Horace Knowles, it is better that the copyright lines for LB and HK and BK illustrations **_just list exactly which pages they occur on_**. As it is now, it says it all backwards:

![image](https://user-images.githubusercontent.com/65363206/197668759-9a2c0291-54f1-4a7b-9e9c-c625247ce9e8.png)

From this result we can't even tell if this publication even used a Louise Bass illustration. We just know that her illustrations don't occur on a whole pile of pages. Can we get back the old way? Where only the David C. Cook copyright line says "All other illustrations are ...."

**Comment by markpenny** [comment]
We are not aware of any changes made in this area recently. But, it is strange to see the doubling of the page numbers, and the fact that DCC pictures aren't even listed/credited in the example above. I'm wondering whether it is a diglot-specific issue. Obviously something else seems to have gone wrong with the above configuration, as it is working fine here, as shown below:

![image](https://user-images.githubusercontent.com/12962708/197737026-73c94c26-63e7-478a-b4ff-e8685f3f665e.png)

I'm scratching around for clues... Have you checked the copyright info on the individual pictures?

**Comment by davidc86** [comment]
I haven't had time to further debug the picture copyright issues. The odd thing is I have not changed anything, either in the pictures (copyright info, etc.) or even the structure of the copyright fields. So I'm as surprised as you all are that things went sideways.

But here are a few comments:

  *   Seems the filename of the illustrations should verify the copyright information (without the user having to physically enter that info) for all the Bass, Knowles, and Cook pictures.
  *   I don't see where I've used the copyright lines more than once (only in the colophon, I've not used them in the Front Matter text)
  *   But it shouldn't matter, right? It should be okay to allow users to use the same copyright field more than once, because if a person is building their own FRT copyright page, they might want the colophon printed also, so they can confirm page numbers, etc. (Maybe it is silly, and using something twice would only happen when testing something, but it shouldn't be a problem to output the same copyright info more than once, right?)
  *   So the Indonesian/etc. version of the copyright lines are kept where? I'm thinking it is important this be a UI accessible thing (even if somewhat buried).
  *   The ONLY copyright line that should say "all the others..." is the David C. Cook copyright line.
  *   I don't think any other publisher has give us such a blanket authorization. So Louise Bass, Horace Knowles, and Louise Bass/Horace Knowles pictures all must be sited directly as to which page each occurs on.

Here are the relevant copyright lines I've manually put in the PTXPrint FRT file:
\b
\ipc Gambar-gambar oleh Horace Knowles pada ayat \xt Mrk. 2:23; 12:15\xt*; \xt Luk. 1:10\xt*; \xt 4:17\xt*; \xt 6:1; 20:24; 2Tim. 4:13\xt* (c) The British & Foreign Bible Society, 1954, 1967, 1972, 1995.
\ipc Gambar-gambar oleh Louise Bass pada ayat \xt Kej. 9:20\xt*; \xt Mrk. 2:22; 10:25; 12:1; 13:2\xt*; \xt Luk. 3:17; 5:20; 15:6; 20:9; 21:5; Kis. 7:44; 9:25; 12:5; Ef. 6:12; Yak. 3:2; 3:12\xt*; (c) The British & Foreign Bible Society, 1994
\ipc Gambar-gambar oleh Horace Knowles pada ayat \xt Kej. 4:21\xt* yang direvisi oleh Louise Bass, (c) The British & Foreign Bible Society, 1994
\ipc Semua gambar yang lain hak cipta pada (c) David C. Cook, dan dipakai dengan izin pemegang hak cipta.
\b
\ipc Illustrations in verses Mrk. 2:23; 12:15; Luke 1:10; 4:17; 6:1; 20:24; 2Tim. 4:13 are by Horace Knowles, (c) The Bible Society, London, England, 1954, 1967, 1972, 1995.
\ipc Illustrations in verses Gen. 9:20; Mrk. 2:22; 10:25; 12:1; 13:2; Luke 3:17; 5:20; 15:6; 20:9; 21:5; Acts 7:44; 9:25; 12:5; Eph. 6:12; James 3:2; 3:12 are by Louise Bass, (c) The British & Foreign Bible Society, 1994.
\ipc Illustrations in verse Gen. 4:21 are by Horace Knowles and revised by Louise Bass, (c) The British & Foreign Bible Society, 1994.
\ipc All other illustrations are copyrighted by (c) David C. Cook, and used with permission.

NOTE: This FRT came from the Paratext FRT file, where I've used the verse references, as this works for the SAB app as well (page numbers make no sense there). But for printed books, I'm thinking page numbers is preferred.
Also NOTE: the \xt brackets are put in for the Indonesian lines, to make it easier (in the app) to jump to the various illustrations.

Of course this is a test run. So the references are static, not variable, and need to be edited for each publication! So it would be really nice not to have to do that anymore, but rather use the built-in copyright feature in PTXprint-thus getting the correct set of references for the currently selected set of books.

Blessings on you all -- David

**Comment by markpenny** [comment]
I think it would be worth discussing this with Darrell Eppler at the workshop to decide the best way forward. These are legal requirements that we're obligated to meet, and we need to find out how much "wiggle room" we have here to tweak the words, or the way we specify this information. We can make the code do almost anything we want; but the point is that not everything we want is always desirable or even permitted.
I can see us having options to say "Show [x] Page numbers; or [ ] References" for illustrations (or even both!?) and it should all be easy to generate, but first we need to know the boundaries within which we're allowed to operate.

**Comment by davidg-sil** [comment]
It seems to me that since, as you say, there are different legal/contractual/licencing requirements for different image sources, and possibly even different images from the same artist, there ought to be some kind of a per-image/per-artist  library that records such things, or metadata on/with the image.

We've gone some way towards that with the images tested/ checked-by-consultant dialogue, it'd be great to have that cultural awareness / process developed and used inter-organisationally.

I'd like to suggest that  we make use of exif/XMP  tagging, in particular, the Picture Licensing Universal System (PLUS) looks like a very promising set of tags, but with XMP tagging, we can add our own tags/namespace if relevant.
Documentation [from exiftool here](https://www.exiftool.org/TagNames/PLUS.html#XMP) and [here, from the org itself](http://ns.useplus.org/LDF/ldf-XMPReference)

If images happened to be already tagged, then PTXprint could look into the tagging for things like the [required image credit](http://ns.useplus.org/LDF/ldf-XMPSpecification#CreditLineText), whether the credit [should overlay the image](http://ns.useplus.org/LDF/ldf-XMPSpecification#CreditLineRequired) and use that information. 
If it hasn't been tagged, then ptxprint (or a separate program?) could tag the image with at least the relevant bits of information.

Of course, if tagging survives insertion into PDFs, then some of that tagging info might be appropriate to *remove* before the image is included in the PDF in sensitive places, but I'm sure that's not beyond our python expert's expertise.

**Comment by markpenny** [comment]
@davidc86 Is this old issue one that can be closed now, or are there still things in here that need to be addressed? I'm trying to do some housekeeping to close issues that don't need to still be open.
