### ISSUE TITLE
Can't change Font settings for \p

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#777]
I can no longer change Font size settings for \p as they remain grayed out.

![image](https://user-images.githubusercontent.com/65363206/202849771-a649ddec-3260-47d9-bc7c-45462e4fadf1.png)

And for some very strange reason there are numerous odd looking \p "styles" like "p_93" etc. in the list which I didn't enter and which are not in the file (that I know of). And they can't be deleted. Even more odd is that there is not difference between these "compressed" and "expanded" styles.

Weird. 

We need to be able to adjust the \p style's font and we would like to get rid of those weird \p styles. Is this possible?

**Comment by markpenny** [comment]
Some of this is "by design". In other words, we are trying to teach the user that you need to change the main/base/default font size and line spacing on the Layout tab, and NOT fiddle directly with the \p style. Because if you make the appropriate changes there, EVERYTHING else will be updated accordingly RELATIVE to the change that you just made. If you just go and "hack the \p style, then everything else might be out of proportion. So, that's why we don't let people change \p.

The other new _93 - _107 styles were added to the styles to help with shrinking and growing text. See [this video](https://vimeo.com/684503993) for more details. [I'm not sure why they don't show up with the right amount of stretch; that's a bug we need to fix.]
