### ISSUE TITLE
Header/footer for the Intro material for a book isn't working correctly 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#782]
If the intro material is longer than a page (in the case of our Rev. it is 2 1/2 pages long), the header and footer don't behave correctly. Here is page 2 and 3: 

![image](https://user-images.githubusercontent.com/65363206/202889130-1d8a8f21-a937-4a80-a081-2cf449a6864a.png)

From here you can see that on the left even page, it is showing the even page header with no bottom page number, but then in page 3, the header is NOT showing, but the bottom page number is! So page 1 and 3 get a bottom page number, while page 2 does not.  This is odd behavior, right? Not just me thinking this is weird?

We would prefer that ALL pages that have ANY text on them from the Intro area of the book (BEOFRE \c 1) would be displayed with NO HEADER and only display the page number at the bottom.  But if the UI doesn't allow for that, then ... could it? Next best option: Only the first page has a bottom page number and the rest get a header. But mixing like this is weird.

(After the main scripture text starts, things setting out and we only have the header showing.)

**Comment by mhosken** [comment]
Send an archive. Tia.

GB,
Martin

**Comment by davidc86** [comment]
I tried, but I get this error: 

Please send to: ptxprint_support@sil.org



Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 3187, in onCreateZipArchiveClicked
  File "ptxprint\view.py", line 1575, in createArchive
TypeError: __init__() missing 1 required positional argument: 'args'

<class 'TypeError'>: __init__() missing 1 required positional argument: 'args'


PTXprint Version 2.2.40

**Comment by davidg-sil** [comment]
The ptx2pdf macros know about 3 classes of pages:
* title pages
* normal pages
* noV (no verses, also known as 'extra books' pages)
Each class has 2 versions (left and right), each version has 6 positions where you might put something.
Hence the UI presents a very simplified version of things

See [the documentation](https://github.com/sillsdev/ptx2pdf/tree/master/docs/documentation#running-headerfooter) for complete control of the 6 * 2 * 3 controls you actually have..

I'd guess you're getting a noV header and footer on your page2, and you're clearly getting a title page for page 3. I'm not really sure why that is. Does the biblical text start with a normal `\s1` ?
Anyway, it's just occurred to me that to force a given page to be a title page, you can almost certainly cheat like this (in your ptxprint-mods.tex):
```
\sethook{page}{2}{\mark{title}}
```
This is because the page hook is the first thing that ends up on the page, and if the first mark that is found on a page is `{title}` then the code decides that it is setting a title page.

**Comment by mhosken** [comment]
I've made a change to how footers are output. This may or may not work for you.
