### ISSUE TITLE
TeX crashes when \fr is set as not bold

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#791]
I have a project which is currently not printing. It will go back to working in any 1 of the following 3 situations.
1) "Contextual Spaces" is turned off
2) "Spacing Adjustments: Between Words" is turned off
3) Styles--\fr : I had turned the default of Bold _off_. If I change it back to default, it will start printing again.

[[ I can work around this problem, so this issue is low priority to me; but it may be a bug which causes problems for others in the future. ]]

**Comment by mhosken** [comment]
Please send an archive

**Comment by mnjames** [comment]
Archive was sent at the time of the original post.

**Comment by markpenny** [comment]
@mhosken and @davidg-sil Note that I have started to put any Archives that have been sent to me in a [Shared Google Drive Folder](https://drive.google.com/drive/folders/1S63WeFUg96ZdlA5IdS4E3AI7kC3HaxUo?usp=sharing) (within the account of ptxprint_support@sil.org). This will stop us having to keep pinging the users to send an archive; and you can pick them up directly from there without me having to send them to you via Slack.

If the support e-mail mentions the issue number, I'll append that to the front of the archive name (so in this case, 791-GRN-DefaultPTXprintArchive.zip). If it doesn't then I'll put the user's first name and surname initial followed by the date it was submitted.

@mnjames Note that you can also post items directly to this "PTXprint Archive Dropbox" as long as you're logged in with an @sil.org account (I don't want this open for the world due to sensitivity issues).

**Comment by markpenny** [comment]
@mnjames Presumably you're still waiting for a fix for this issue. Could you confirm that it is outstanding, or that it has been fixed in the last few months? Thanks.

**Comment by mnjames** [comment]
I can't recreate the problem given what I wrote above, and I don't think I've accidentally triggered it again since our workshop, so I'll assume it's fixed.
