### ISSUE TITLE
Suppressing logging for "ornaments"

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#798]
I'm using the dynamic borders, specifically copied almost exactly from the `DG:ornaments` presentation
```
\Marker textborder
\TextProperties publishable
\BorderStyle ornaments
\BorderRef Vectorian3
\BorderWidth 10
\BoxPadding 5
\BorderColour 0 0 0
\BorderFillColour 0 0 0
\BorderVPadding 8
\BorderHPadding 8
```

My final xetex log file has thousands of lines similar to `(d:/Documents/github/ptx2pdf/src/contrib/ornaments/vectorian48.pgf)`.

Could those be suppressed, and maybe only turned on with some sort of tracing flag?

**Comment by davidg-sil** [comment]
The lines are produced by TeX when it's reading the file. The solution would be to *not* let TeX read the file multiple times, and instead read it once and remember the input. 
But that'll take a rewrite of the code, not just better configuration of messages I put in there, sorry.
If I'm going to rewrite the code, then.... there are other things I'd like to optimise too.

**Comment by davidg-sil** [comment]
The code on github since just before Christmas (but probably not in a release yet) allows you to set `\CacheOrnamentstrue`. It does not cache every repeat of an ornament, only *exact* repeats  (exactly the same size, rotation, colours etc), and therefore may not reduce the number of repeated file-reads, depending on circumstances. For a border where most of it is from repeated elements, it ought to help.

**Comment by mnjames** [comment]
Thanks for working on that. When printing the full NT this reduced the number of lines in the log file from 50k down to 26k, which is both amazing also somewhat insignificant.

But if this isn't an easy fix, it's probably not worth messing with. Any time I really need to read the log file I can probably remove the extraneous lines with a simple regex search, since they're so consistent.
