### ISSUE TITLE
Picture Cutout positioning across pages

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#806]
In an effort to avoid the text-wrapping problem discussed in #805 I changed the anchor verse from v10 to v9, and I changed the position to +5 lines. This is a bit sneaky, because v9 actually starts at the bottom of the previous page (above a pile of footnotes) and the +5 lines is to try to push the position of the picture over to the next page, so it ends up about where it was before.

But this revealed two more problems with the Cutout feature:
1) If the settings are the same as before (in #805) i.e., Outer, Mirror on Odd pages, then we get this:

![Screenshot_20230103_095016](https://user-images.githubusercontent.com/65363206/210382259-a2035792-e90d-446b-85c6-fb2fa99873b1.png)
 
Here PTXprint appears to be basing the positioning of the picture on where the VERSE starts, not where the PICTURE is supposed to be sitting. I.e., because v9 starts on an Even page, the cutout gets set to "Outer" for an Even page (so it cuts out the text on the LEFT side of the page, but because the positioning setting is set to +5 lines, this then moves the cutout to the ODD page, so the Cutout ends up looking like an INNER, not an Outer. And notice that the picture is NOT mirrored, because it too was calculated as being on an Even page, when in fact, it is positioned to sit on an odd page. But the biggest problem is the picture sitting off the bottom of the page.

2) To try to fix these errors, I changed the Cutout settings to Right, Mirror Always, with the position the same (+5 lines), then we get this:  

![Screenshot_20230103_094912](https://user-images.githubusercontent.com/65363206/210384219-3afbd30a-3f62-459a-aa37-c7b49d188b2f.png)

Here PTXprint does a better job with the Cutout. None of the text in v9 gets truncated (like it does in #805), but the picture is still off the bottom of the previous page - which is never a good thing.

WHAT WE NEED:
It is preferable that the use can set this up using the settings as laid out in 1) above (Outer, Mirror ODD, +5 lines), as this should make it look right regardless of what page the picture ends up on. 

So, PTXprint needs to first use the position settings to figure out what page the Picture will end up on, and not base this on the position of the verse number. Then it figures out the look of the Cutout ("outer"), and then mirrors the picture based on that final position. 

And maybe a picture should never end up off the end of the page? (Though there might be an artistic need for this?)

So, maybe allowing a user to push a picture to the next page is too hard to do? If so, then bug #805 really needs to be fixed, so that negative positioning doesn't cause the picture to truncate the previous verse's text. Because as PTXprint is now, I can't get this picture to print in this book. 

Just wanted to say though that this Cutout feature is **_super cool_**, and well worth getting it to work nicely. 

It is only a problem when a verse breaks across the page like this, and the verses contain poetry, so the lines are short, and only a few verses take up the whole page. But these are exactly the kinds of verses where tall skinny pictures fit best.

**Comment by davidg-sil** [comment]
As the [documentation (see note 6 under the table)](https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/figures.md) says, the image gets included in the same column/page as where the anchor occurs. Getting the behaviour you're asking for is probably possible but  it's likely to be error prone and would involve quite a number of challenges. As it would effectively be changing the anchor point every run,  which would interact messily  the settings from the piclist, I expect it'd end up rather messy.

You can, however,  anchor to a particular paragraph after a verse number (or after a keyword, etc).  Look at  the [documentation on anchor references](https://github.com/sillsdev/ptx2pdf/blob/master/docs/documentation/figures.md#anchor-references) for full details, but the TLDR version is try anchoring to  `GEN 5.9=3` rather than just verse 9.
