### ISSUE TITLE
Need a way to specify a Table's column-width 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#84]
The "Read the Bible in a Year" table at the back of our publication looks "almost right", but we need a bit more column width for the verses and don't need it in the "Day" column (the 1st one): 

![image](https://user-images.githubusercontent.com/65363206/82674084-c7940d80-9c10-11ea-8164-116546ba6376.png)

As you can see, the *Sekwe* column never needs to be wider than the word "Sekwe", whereas we could use the extra space in the Psalms column when it gets to such big numbers. Is this possible in the STY file?

**Comment by markpenny** [comment]
I have no idea, and am thinking that this is kind of beyond the scope of what PTXprint was designed to do. Others reading these issues may have some ideas. Personally I'd use a different tool to generate that kind of para-scripture material and then add it on to the end of the publication using the option called "Include Back Matter PDFs" available on the Advanced tab.

**Comment by davidc86** [comment]
Ah, that's a possibility too (adding a PDF), but these kinds of things are found in OT lists of "fighting men" etc. which might be helpful there as well (not just for para-scripture material). But as you have indicated, clearly an "enhancement" that ranks pretty low, unless someone knows of a dead-simple way to specify this.

**Comment by davidg-sil** [comment]
I've not looked at the code at all, but to me it looks like the columns are not forced to a set size, but it's trying to do a 'width of most items in the column plus constant' kind of thing.  In which case what you're saying is that you want to (a) lie about how wide 'Sekwe' is, or (b) for the constant to be smaller. I don't know what the constant is,  @mhosken might know.

The first can be done (in a .tex file) by saying:
\def\shortSekwe{\hbox to 2.5em{Sekwe\hss}}
And then use \shortSekwe instead of the word. In the interests of education, the above defines a macro \shortSekwe to be a horizontal box 2.5em [1em=width of a capital M in the font, or maybe the font size, I can't remember which definition TeX uses] that contains the word Sekwe followed by some infinite horizontal stretch or shrink.

A cleverer option, if you want to do this sort of thing a lot might look something like this code:
```
\def\OneEmShorter#1\end{\leavevmode\setbox0\hbox{#1}\dimen0=\wd0 \advance\dimen0 by -1em\hbox to \dimen0{#1\hss}}
```
Use would then be: \OneEmShorter Sekwe\end

**Comment by mhosken** [comment]
The plan is to set the width in \tc3 or whatever. The outstanding question is what to call the property in the .sty sheet. We are adding lots of properties and we need to name them wisely.

**Comment by mhosken** [comment]
setting \SpaceBefore on a \tc cell will ensure that that cell is at least the given width.
