### ISSUE TITLE
PTXprint does not correctly handle centered table headers (\thc*)

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#85]
The fields \thc1 etc. are "centered" header cells for tables. PTXprint does not handle them. 
Here is the SF code for the table in PT9: 

\tr | \th1 Sekwe | \thc2 Tnyetak Harharkwe | \thc3 Tnyetak Harharkwe | \thc4 Tnyetak Mamunake | \thc5 Tnyetak Mamunake
-- | -- | -- | -- | -- | --
\tr | \tc1 1 | \tc2 \xt Mat. 1:1-17 \xt* | \tc3 Kis. 1:1-11 | \tc4 Mzm. 1 | \tc5 Kej. 1-2

Here is how it comes out in PTXprint:

![image](https://user-images.githubusercontent.com/65363206/82675721-383c2980-9c13-11ea-9b30-6429efce6cf9.png)

Note: PTXprint DOES correctly handle \th* (left-align) and \thr* (right-aligned) table headers. 
[I have not checked normal tables cells fields, \tcr* (right-align) and I assume \tcc* (centered).]

**Comment by mhosken** [comment]
I have added code to support \thc and \tcc, but I have no idea whether it works. You'll find it in commit a7b75ee and in the next release of ptxprint. If you find problems, please send me an sfm file I can play with. TIA.

**Comment by davidc86** [comment]
It does NOT work yet in v.0.7.0, so I'll check again with the next released update.

**Comment by davidc86** [comment]
Well, bummer, it is not yet fixed in 0.8.1, if I make the table headings row centered, I get this:

![image](https://user-images.githubusercontent.com/65363206/84582498-e5d9cd00-adba-11ea-8a68-a4e5333a5f7e.png)

The offending file is SLU XXB (I can always change the heading row to left or right, but it just looks better centered.

Here is the file (I changed the extension to .TXT since Github doesn't recognize .SFM files): 

[95XXBSLU.TXT](https://github.com/sillsdev/ptx2pdf/files/4775719/95XXBSLU.TXT)

Hope this gives you something to play with. (I'd like to make all the heading rows centered, not just the first one).

**Comment by mhosken** [comment]
Thanks for the sample file. Fixed a typo in the macros. Should be fixed in 0.8.2.

**Comment by davidc86** [comment]
Yup, it no longer crashes, but now it seems to format \thcX (*centered*) as though it is \thrX  (*right-aligned*)
Here is a screen shot: 

![image](https://user-images.githubusercontent.com/65363206/84719877-801c4b00-af4a-11ea-91b4-55f908ad3022.png)

**Comment by mhosken** [comment]
I just committed a fix to handle centred columns. Note that the default stylesheet has a really bad value for LeftMargin for \tr. The TeX macros use the \tr styling to control column margins. I would set something like:
```
\Marker tr
\LeftMargin 0.1
\RightMargin 0.1
\FirstLineIndent 0
```
It's unfortunate that it is all hardwired to \tr since that means you can only have one type of table layout per document. But there is no other way to pass table styling in USFM so I guess it's as good as we can do at the moment.

**Comment by davidc86** [comment]
Thanks for that “trick”. Setting the \tr to those settings does seem to improve the layout of the table. (I’m waiting for 0.8.3 to comment on the centering. Again, thanks for working on that!)

Right, concerning the hardwired table fields. This is one reason I thought \toc fields should at least allow the Table of Contents to be treated differently.

PT8+ treats front matter and back matter settings (frtbak.sty) differently from scripture (custom.sty). Might that be something we could leverage?

David
---

I just committed a fix to handle centred columns. Note that the default stylesheet has a really bad value for LeftMargin for \tr. The TeX macros use the \tr styling to control column margins. I would set something like:

\Marker tr

\LeftMargin 0.1

\RightMargin 0.1

\FirstLineIndent 0

It's unfortunate that it is all hardwired to \tr since that means you can only have one type of table layout per document. But there is no other way to pass table styling in USFM so I guess it's as good as we can do at the moment.

**Comment by davidc86** [comment]
Okay. Bummer, but I just tried to print my configuration (which printed just fine in v0.8.2) and this is what I see:

![image](https://user-images.githubusercontent.com/65363206/85411469-683e5b80-b536-11ea-8bb3-27239334873a.png)

**Comment by davidc86** [comment]
Okay. I had to create a configuration WITHOUT spaces in the name, and restart PTXprint a few times, but now it formats the Centered Table Heading correctly! Woohoo! 

So, I've no idea what the error above is talking about. The documents haven't changed from one PTXprint version to the next. But now it formats without error, so that must again be related to either the "space" in the name, or the fact PTXprint does tend to crash after an initial install.

**Comment by markpenny** [comment]
Unfortunately, we've made some changes to what is/isn't allowed in the Saved Config filename - which will cause some of the previous saved configs to do strange things. One of the "joys" of being on the bleeding edge of a Beta test programme :-(

I trust that new users won't experience the pain that you've had to put up with as you followed each release through the valleys and mountaintops! I need to update the help/FAQ or Tooltip so that people know that spaces aren't allowed in the Config Name any more. Yes, your guess was right - it was to help those working under Linux (especially as we now include the saved name as part of the output .tex and ,pdf filename).

Closing this one based on the "Woohoo!" response above :-)
