### ISSUE TITLE
Binding/Outer Gutter bug

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#855]
I think the Layout --> Outer Gutter tooltip needs more information in it. I'm not exactly sure what information, because I'm not exactly sure what it's supposed to do 😃 If it's possible to set the size (in mm) of that outer margin, then information on how to set it would be helpful.

-----------

Originally I was using the Binding Gutter to set a binding gutter, but in a RTL language it was on the outside of the page. So I thought, "Oh, maybe the Outer Gutter will let me add space to the inside". But it didn't work.

**Comment by davidg-sil** [comment]
Hmm.  I think the tool tip is on the binding gutter. You either get a binding gutter (extra space for gluing the binding) or outer gutter (extra space on the outer side), not both. Otherwise the pages just obey the side margin width on both sides.

Was it a diglot project which didn't get the binding gutter correct? The binding gutter  certainly *ought* to be on the correct side for binding. Since diglot might have a mixture of directions, the UI should ask for a manual decision on which side opens (which turns into TeX setting `\BookOpenLefttrue` for RTL or `false` otherwise). I can't actually find where to set it, though.
If the UI isn't setting that boolean correctly,  well, there **used** to be TeX code to force it for non-diglots, but it looks like @mhosken  commented that out in early March.

**Comment by mnjames** [comment]
Thanks. The Binding Gutter tooltip does explain things, and it seems like it's supposed to work the way I was guessing.

Okay, then I think this is actually a bug report. Now it's just figuring out what the bug is...

The project is a single column monoglot. I've submitted an archive to the Drive folder (file name starting with 855).

With the script direction set to RTL, when I set the Binding Gutter the extra space appears on the outer edge, not the binding. I thought that was just another place where we RTL people are supposed to switch our rights and lefts. So, this problem doesn't _have_ to be treated as a bug, though your reply makes me think maybe it is.

The bigger issue is that the "solution" I was expecting doesn't work. When I check off "Outer Gutter" with the hope that it would move my extra Binding measurement into the gutter, it doesn't have any effect. Even if the Binding Gutter behaviour gets changed, this checkbox will _also_ need to be fixed.

**Comment by davidg-sil** [comment]
Ohh...  look what I've found.. (full view only)

Could you check on the "Fonts and scripts"  page, next to "Text flow direction", there ought to be a checkbox called "RTL Book Binding"
![image](https://user-images.githubusercontent.com/58848232/231535220-8ad7d452-9261-460c-9c04-3933bf59aac5.png)

If that wasn't ticked, can you try flipping it?  Then you can complain about it not following with RTL fonts on basic view / old projects as appropriate.

If it *was* already ticked, could you try putting `\BookOpenLefttrue` in `ptxprint-changes.tex`? If that makes the binding gutter work properly,  then that narrows down the bug quite a lot, I expect.

**Comment by mnjames** [comment]
Well, ***that's*** super embarrassing. No, it wasn't checked off, and yes, checking it fixed (some) of the problems.

1) Binding Gutter now works exactly as expected.
2) Outer Gutter still has no effect, so that's a bug (though not one that *I* need fixed at this point). `\BookOpenLefttrue` doesn't appear to have any effect (I put it in `ptxprint-mods.tex`, which is what I assumed you meant).
3) I'm going to backtrack and say that I think Outer Gutter still needs a better tooltip. Maybe something as simple as one additional paragraph that says something like `This works in conjunction with Binding Gutter. See above.`
4) Why have I never noticed the RTL Book Binding option? Probably because the main thing I look at for binding--the pdf binding option documented in #525--works based on "Text Flow Direction" and so I've never needed to set the RTL Book Binding checkmark. But now that I know it exists, I wonder a) why it's necessary--would you ever have a flow direction and a binding direction be different, and b) why the pdf binding isn't controlled by the RTL Book Binding rather than by the flow direction.

**Comment by davidg-sil** [comment]
re: (4) I'm guessing that it's a new control. Until March, TeX was taking control of the setting for monoglots anyway (making it follow text flow). That was probably undesired,  because it meant that there was very little you could do to force it to do the other thing, if you were the one person in a hundred (or less?) who wanted that.
For diglots, as I've said, people need the separate control, or at least if it's a mixed diglot.

**Comment by mnjames** [comment]
I've created a pull request (#856) to make that minor change for (4).
