### ISSUE TITLE
Disconnected footnote

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#862]
I have a project where half a footnote is showing up at the bottom of a page with no caller or reference number. I suspect it's somehow copied from the following page (where it occurs in full).

For privacy reasons I'll put an archive in the Drive Folder and send more details via email, but I wanted to add an issue here because it helps me track and remember things.

**Comment by mnjames** [comment]
In the pdf, there are two lines of a footnote at the bottom of p.23, but they don't have a footnote caller nor a reference.

Then, at the bottom of p.24, there a 4 line footnote. The bottom two lines of p.23 are identical to the bottom two lines of p.24. So I'm assuming the footnote on 24, which is part of v.6, is getting half-repeated on p.23 (which also contains a part of v.6).

I'm struggling with bisecting it because my current printjob depends too much on very recent changes, and so if I go back even to 2.3 it doesn't print correctly. And, probably obviously, one pagination changes whatever strange situation triggers this error disappears.

**Comment by davidg-sil** [comment]
Well,  even *with* things changed so they don't depend on recent changes, bisecting was a dead loss as changes to the layout change the page position and so on.
 I made a  minimum crashing example (just chapter 6) added even more  debug code  and was able to work out what was going on... non-paragraphed footnotes in single column mode obeyed original TeX rules on being able to break onto the next page, which then in turn broke the 'shrink the page if it doesn't fit' process by hanging around for the 'next page',  when they were about to be repeated / moved. The 'next page' was the actually the first page with a smaller size,  just as you saw.
  Since we *do* actually want notes to break in some circumstances,  (e.g. study bibles) rather that trying to kill the 'notes can split' rule, I've tried to clean up the left-over bits of notes. It *seems* to work. Please test, and please be on the look-out for lost verses near footnotes.

**Comment by davidg-sil** [comment]
The approach I've used, if it proves robust enough, can possibly be leveraged to help splitting of notes in study Bibles, etc. but that almost certainly depends on a lot of other changes.

**Comment by mnjames** [comment]
I'm now getting this error (and no output)

```
! OK.
\clearthenbackup ...insertpenalties }\showbox 255 
                  \setbox 0\box 255 \ifnum \...
<output> {\clearthenbackup 
         }
\p@r ...interchartokenstate }\fi \fi \fi \endgraf 
                  \ifvmode \ifinn@te \else \...
\endit@P ...xpos }{\the \pdflastypos }}\endL \p@r 
                  \ifvmode \else \ifinner \t...
\d@ ...ex pop endit@#1}\csname endit@#1\endcsname 
                  \else \trace {sa}{Simple p...
\cstackdown ... \cstack@tmp \empty \else \d@ #1\E 
                  \fi \edef \cstack@tmp {#2}...
...
l.24 \q1 
   اَے پروردگار! تُوں جہڑا عرش اُتے ویں، 
```

**Comment by davidg-sil** [comment]
Ah... that'd be debug code. Oops, sorry!
Fix psuhed.

**Comment by mnjames** [comment]
I wrote an email couple of days ago with one further bug I found--in the preceding example (archive 862b), after the bug was fixed but footnote caller was on the first line of text, all subsequent lines were off grid. I worked around the problem by stretching the paragraph so that the caller was on the 2nd line of text (but there's still a bug there somewhere).

Likewise, this new bug doesn't need immediate attention because I will "solve" is by stretching/shrinking paragraphs.

I've submitted archive 862c. Sorry, it's as minimal as I could get but I needed to start from ch.23 because it starts a new page. On the bottom of page 18 a footnote caller shows up looking like this:
![image](https://user-images.githubusercontent.com/30174022/233779491-b3188f21-e519-4202-a2a3-567ee03b7c8e.png)
There's a huge amount of blank space below it--enough for the footnote (which is on the next page). Oddly, neither the footnote nor 3 more lines of regular text flow into the space at the bottom of p. 18.

**Comment by mnjames** [comment]
I've added archive 862d to the Drive folder. The issue is that footnote 1.13 is on page 2, while it should be on page 3.

Once again, I'm working around this issue by stretching and shrinking paragraphs. So this is low priority.

In this case, this change fixed the problem:
`at 2JN 1:13 '$' > '\\eject'`
so, it's quite possible the problem is due to the end of the book not being closed out properly. In fact, I have to add an \\eject at the end of _every_ book or else the borders don't look correct (which now that I've written this up, makes me wonder if the footnote problem is just a symptom of the end-of-book problem).

**Comment by davidg-sil** [comment]
I've just spent about 6 hours scratching my head over your 862c archive.  The issue seems to  be that a break seems to be possible between a kern and glue, even if the glue is an automatically inserted lineskip, but when footnotes started to get `spacebefore`, a couple of years ago,  the code seems to have  assumed you don't get breaks at kerns.   
The reason that the text does not continue, is that TeX's engine was trying to split the footnote  in 2, and the it seems to have assumed that the split note was 'filling the page'.

**Comment by mnjames** [comment]
Thank you for the hard (and long) work on this.

I worked around this problem in May be stretching and shrinking paragraphs, and so I don't have anything other than the original archives to test it on. I'm going to assume you've actually solved the problem (including for 862d) and resolve this.
