### ISSUE TITLE
Red diacritics for Arabic script

### ISSUE THREAD

**Issue by markpenny** [sillsdev/ptx2pdf#870]
One of the potential PTXprint users at EMDC asked if it is possible to color all the diacritics in red. Apparently this isn't currently possible, but could be done using a post-processing step when creating the final PDF. I am adding this issue as an enhancement request.

Current priority: Unknown.

If there are other PTXprint users who would also like this idea to become a reality, then now is the time to chip in... (even if anonymously).

**Comment by LornaSIL** [comment]
I know of one major project that had the whole book printed with every page where the diacritics were in red and another major project printed about 30 pages with the diacritics in red. Of course, both projects were costly, but they felt it was worth it. They used InDesign. So, I'm sure this would be a benefit.

**Comment by mhosken** [comment]
My suggested way to implement this is to add three new specials:

- dialist _id_ _numglyphs_ _glyph ids_
- diastart _fontid_ _color_ _dialistid_
- diastop

I'm not sure if the glyph ids should be glyph ids or USVs. That is an implementation detail. 

The coloring is achieved using an xdvi filter that converts and xdvi file to another xdvi file. The filter reads the new specials and inserts color specials around to identified glyphs in the given font.

IITC eTeX allows one to access the fontid for a font, failing that we can use the fontname

Expected time to implement is about 1 week (including UI, TeX macro work and the xdvi filter). For that reason we need a formal request to implement this, otherwise this will remain in the queue. The formal request implies that if we implement it, someone will use it. Of course this could be picked up as a volunteer project.

**Comment by mhosken** [comment]
Simpler yet. Include colour in the dialist to become diadeclare. Also allow glyph ids by usv (cmap lookup), name (post table) or number because not all glyphs are accessible from the cmap. Then diastart needs only the id (which can default to 1, saving even that):

- diadeclare _id_ _colour_ _glyph\_ids_

Probably don't need a numglyphs.

**Comment by davidg-sil** [comment]
Just wondering...  what would happen if the colour-switching was via XeTeXcharclass and XeTeXinterchartoks? Would inserting \specials there that interfere with Graphite rendering?

**Comment by mhosken** [comment]
Yes it would. It does for interchar spacing hence the categories.

GB,
Martin

**Comment by markpenny** [comment]
This feature has now been added and is documented here: https://software.sil.org/ptxprint/documentation/how-to-color-diacritics/
