### ISSUE TITLE
Pictures scattered apparently randomly in glossaries

### ISSUE THREAD

**Issue by JDNystrom** [sillsdev/ptx2pdf#874]
I describe this in detail here: (https://docs.google.com/document/d/1rjpnv0t_PZH9JSK_5e-wFBbULgW3Ue9RnFM6eAOaKXc/edit#bookmark=id.or2r6uhaj6gr). 

In my diglot publications, pictures in my glossaries are appearing in random places. T1 and T2 glossaries both contain T1 and T2 pictures and appear in seemingly random places.

**Comment by davidg-sil** [comment]
The glossary piclist entries don't seem to distinguish between L and R - they're all `GLO p001`, etc.  
It's probably not *too* hard for you to use an external editor on the piclist and change the `GLO` in to `GLOL` / `GLOR`  as appropriate, based on the caption, and that'll probably help quite a lot.
As I've tried to convince Martin and Mark, probably the **best** thing to do for glossary entries is to anchor them to the glossary entry itself. 
e.g. `GLOL k.wit` instead of `GLOL p042`

**Comment by markpenny** [comment]
This 'issue' was caused by trying to use a 'monoglot' PicList on a 'Diglot'. In order for it to all work well, you need to ensure the PicList is generated WHILE the Diglot setting is enabled. By doing this, you automatically get the L and R in the appropriate places, and everything works as expected.
