### ISSUE TITLE
Repeated core dumps

### ISSUE THREAD

**Issue by kahunapule** [sillsdev/ptx2pdf#899]
INPUTFILE: "/home/kahunapule/Documents/typeset/spapddpt_bwmaps.pdf" [845]
(/home/kahunapule/Paratext8Projects/PdDpt/local/ptxprint/Default/PdDpt_Default_
GEN-REV_ptxp.parlocs)
(/home/kahunapule/Paratext8Projects/PdDpt/local/ptxprint/Default/PdDpt_Default_
GEN-REV_ptxp.notepages)
(/home/kahunapule/Paratext8Projects/PdDpt/local/ptxprint/Default/PdDpt_Default_
GEN-REV_ptxp.picpages) )
Output written on PdDpt_Default_GEN-REV_ptxp.xdv (855 pages, 61055084 bytes).
Transcript written on PdDpt_Default_GEN-REV_ptxp.log.
cd /home/kahunapule/Paratext8Projects/PdDpt/local/ptxprint/Default; xetex PdDpt_Default_GEN-REV_ptxp.tex -> 0
Rerunning because the table of contents changed
Segmentation fault (core dumped)

Trying again:
INPUTFILE: "/home/kahunapule/Documents/typeset/spapddpt_bwmaps.pdf" [845]
(/home/kahunapule/Paratext8Projects/PdDpt/local/ptxprint/Default/PdDpt_Default_
GEN-REV_ptxp.parlocs)
(/home/kahunapule/Paratext8Projects/PdDpt/local/ptxprint/Default/PdDpt_Default_
GEN-REV_ptxp.notepages)
(/home/kahunapule/Paratext8Projects/PdDpt/local/ptxprint/Default/PdDpt_Default_
GEN-REV_ptxp.picpages) )
Output written on PdDpt_Default_GEN-REV_ptxp.xdv (855 pages, 61055084 bytes).
Transcript written on PdDpt_Default_GEN-REV_ptxp.log.
cd /home/kahunapule/Paratext8Projects/PdDpt/local/ptxprint/Default; xetex PdDpt_Default_GEN-REV_ptxp.tex -> 0
malloc(): unaligned tcache chunk detected
Aborted (core dumped)

And again:
INPUTFILE: "/home/kahunapule/Documents/typeset/spapddpt_bwmaps.pdf" [845]
(/home/kahunapule/Paratext8Projects/PdDpt/local/ptxprint/Default/PdDpt_Default_
GEN-REV_ptxp.parlocs)
(/home/kahunapule/Paratext8Projects/PdDpt/local/ptxprint/Default/PdDpt_Default_
GEN-REV_ptxp.notepages)
(/home/kahunapule/Paratext8Projects/PdDpt/local/ptxprint/Default/PdDpt_Default_
GEN-REV_ptxp.picpages) )
Output written on PdDpt_Default_GEN-REV_ptxp.xdv (855 pages, 61055084 bytes).
Transcript written on PdDpt_Default_GEN-REV_ptxp.log.
cd /home/kahunapule/Paratext8Projects/PdDpt/local/ptxprint/Default; xetex PdDpt_Default_GEN-REV_ptxp.tex -> 0
Segmentation fault (core dumped)

Running Ubuntu LTS. It works for just the New Testament + Psalms & Proverbs, but memory corruption sets in on the larger whole Bible.

**Comment by markpenny** [comment]
@kahunapule Michael, I'm guessing this is an issue in 2.3.35 which was fixed in 2.3**.36** (but as you are on Linux [?]) you didn't have that version available to you. I've just pushed the Linux versions out there for 2.3.36 (please see if that solves it). If not, I'll look deeper tomorrow.

**Comment by devosb** [comment]
I recently updated the [XeTeX](https://github.com/sillsdev/ptx2pdf/commit/d17b27a02b3c1842cc06fd96a397d7e342da2353) binaries in PTXprint for use on Windows, and saw similar crashes while testing on Windows. Since I had created a developer environment for PTXprint on Windows, I was able to update to the latest source (which should have contained the fixes that went into 2.3.36)

Since PTXprint on Linux would be using xetex from the system package manager, and not the Windows binaries that I updated, it seems that the crashes are not coming from the update I made. But maybe there are multiple sources of the crashes, if so, I might need to do more testing with the Windows binaries.
