### ISSUE TITLE
Seems to be a line spacing bug when footnotes are found inside words of Jesus 

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#910]
The PT file has this: 
![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/6fac3d48-d3a0-49e8-ad3e-86ac5b753409)

The footnote is: 
![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/78dfe8e0-6277-4c26-803a-9aa56ab94c9d)

The output file looks like this: 
![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/9ed0d246-a577-490c-828b-6c01f38bd014)

If I move the footnote to the end of the verse, it shifts the spacing down.
I don't see any reason for this in the SFM files. (There are no codes in the footnote that call for a "large font" or "large line spacing".) 

Any ideas. I know I have used this structure many times before and have never noticed this odd spacing before.

**Comment by davidc86** [comment]
Here it shows up in another place: 

![image](https://github.com/sillsdev/ptx2pdf/assets/65363206/dc1a6e5d-0086-424d-8a05-4f42dca8b1fc)

FYI, if I move the footnote caller to the end of the verse, PTXprint scrunches up the Section Heading too close to the end of the verse.

**Comment by davidg-sil** [comment]
To help me track it down, can you tell me which version you're seeing this in? Thanks! That sort of thing should show up in our test files, which I've just updated the standards for, so urm... eek!

**Comment by davidc86** [comment]
Removing the \wj from around the footnote make the footnote caller red. I'd rather it not be considered part of the quote.
The weird thing about this is that we use this exact structure all over the NT. In Matthew alone it is used a lot, but only in chapter 9 is there this weird spacing. In fact, in ch 9 it is used maybe 3 times and only 2 of them have the weird spacing. 

The archive for Matthew is 38MB. Not sure where to drop such a big file (sending only part of it might not have whatever it is that is triggering the spacing issue).

**Comment by davidg-sil** [comment]
Probably too big for email, I'm not sure. There are things like wetransfer.com and transfernow.com, but most of the time big archives get transferred to us by emailing a link to a file on  a google drive (to the support email).

**Comment by markpenny** [comment]
@davidg-sil The archive is now in the usual place and named: SLU-PublikasiSelaru-MatthewPTXprintArchive.zip

**Comment by davidg-sil** [comment]
OK... Based on my testing, it looks like the issue is not the `\wj` at all, but the combination of the previous page having space for the line, but not the line + the footnote., so it gets put back, and the  praragraph breaking tries again.  
**Something is going wrong in the 'putting it back'  process.**  
Probably because the font has a high ascent, (Bigger than the line spacing) and you are not running with `XeTeXuseglyphmetrics=1`.  @mhosken will moan at me if I tell you to turn that on, because it sometimes causes other issues, and in your case, it is certainly moving the footnotes' baseline up and down, and that's affecting where the  pagebreak is on page 4.... 

I  know I spent a few days getting this working properly in the diglot code a year or 2 ago, so I'll try and work out if I can reuse the diglot 'join stuff back together' code, or if I need to examine that code and reapply it for this circumstance.

**Comment by davidc86** [comment]
Looks like this works fine in v2.4.7, thanks!
