### ISSUE TITLE
Marginal Verse Verse bridge hyphen missing again

### ISSUE THREAD

**Issue by RCraigWebb** [sillsdev/ptx2pdf#913]
[KHTTyp-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/12801421/KHTTyp-DefaultPTXprintArchive.zip)
When working with marginal verses the hyphen for verse bridges was working for a few versions of PTXPrint, but it seems to not be again. In Mark, the first verse bridges are located in 1: 33-34 and 36-37.

If possible, the default setting for verse brides has the numbers way to far apart, This can be adjusted in the style sheets, but can a default be set to have them close together instead of looking like there is a blank line between them?

I'm working with several projects and several translators and they have all reported this to be a problem.

One requested if the verse bridge numbers could be on one line, but I think that may require a very wide margin. In InDesign we always use two lines for bridges, too.

Thanks!
Craig

**Comment by mhosken** [comment]
One day, perhaps. But for now perhaps try sharing templates with the styles
already in. Not only do we need to set a sensible linespacing, but
superscript needs to turn off and a smaller fontsize used. There's quite a
few settings there. Also don't forget the extra space setting next to the
turn on marginal verses. You will want to set that appropriately too.

Let's start from "hey, the 7 projects of 2000 can do what they need to do,
even if it involves a bit of clicking" and in due course perhaps refine it.

So  step 1. I suggest writing a procedure document on how to do marginal
verses well in ptxprint. Once that procedure is down, send it to us and
we'll look at how we might reduce the number of steps.

**Comment by RCraigWebb** [comment]
Yes, in Paratext they are listed as a verse bridge, or as one combined verse. There isn’t a marker separating what is from one verse or the other. Sometimes the bridge can be just two verses together as in this case or can be many. Another project has many bridges such as 2-6a, or 11-17.

 

Craig

 

________________________________

 

R. Craig Webb
Publishing Coordinator
MSEAG 

Mobile: 099-136-7746
________________________________

**Comment by davidg-sil** [comment]
Ah, OK, I  now see some of those at `1:43-44`  and `2:6-7`  I'm guessing it was one of those 'too many screens open' things.
So, I've done some digging:
*  to generate a hyphen you need to:
   -  have enabled `ptxprint-mods.tex`
![image](https://github.com/sillsdev/ptx2pdf/assets/58848232/c0b8de00-3ec9-43bc-a771-3c2f8b261954)
   - include a line in it that says `\versehyphentrue`.
 ![image](https://github.com/sillsdev/ptx2pdf/assets/58848232/ee08a60a-425e-465c-a91d-5c28b33bd5d5)

* to control the inter-line space,  you need to change the linespacing for `\v` (yes I know `\v` a verse style, but if it's breaking into lines then it needs a linespacing, doesn't it?).
*  As mentioned earlier, you might want to turn off the superscript, and adjust the `Raise` parameter to 0.01 (There  still seems to be a bug in the UI thinks 0 means unchanged).
* Since superscript automatically reduces the font size too, so you probably want to reduce the fontsize.
![image](https://github.com/sillsdev/ptx2pdf/assets/58848232/2421fef3-26d3-4e6b-a9ef-13878a5b4ef7)
* You might also want to adjust the space between the verse and the text, by adding something like `\def\AfterVerseSpaceFactor{5}`  or similar to ptxprint-mods.tex. The units are the same pseudo-points  that the stylesheet uses - 5 is 5/12 of the main font height.

Please don't take the values I've picked as perfect... they just seem to work.

 Perhaps @mhosken  can tell me why the `versehyphentrue` control is in the texhacks.py file, but commented out, and AfterVerseSpaceFactor  seems to be missing?

**Comment by markpenny** [comment]
Found `AfterVerseSpaceFactor `promoted to greater prominence over here:

![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/6dcc26b2-1beb-43e5-a6ce-5fd68a807f0f)

**Comment by markpenny** [comment]
Also, I don't know if this is helpful, but there is a command which prevents them from overlapping:

![image](https://github.com/sillsdev/ptx2pdf/assets/12962708/7974551b-8eba-4da1-b792-9c22883694a0)

**Comment by RCraigWebb** [comment]
Thanks David! The \versehyphentrue line has the hyphen showing again and the suggestions on the verse settings are helpful. 

 

Craig

________________________________

 

R. Craig Webb
Publishing Coordinator
MSEAG 

Mobile: 099-136-7746
________________________________
