### ISSUE TITLE
Problem on pages (Issue #935)

### ISSUE THREAD

**Issue by KNNettey** [sillsdev/ptx2pdf#936]
Yes, I installed the newest version before I did the job.
[GBVN96-DefaultPTXprintArchive.zip](https://github.com/sillsdev/ptx2pdf/files/13752070/GBVN96-DefaultPTXprintArchive.zip)
[GBVN96_Default_MRK_ptxp.pdf](https://github.com/sillsdev/ptx2pdf/files/13752077/GBVN96_Default_MRK_ptxp.pdf)

You will notice that some of the pages do NOT have the suggested number of lines on them. Page 1 has the title of the book and then 2 text lines. 

How do I get all the to have the same number lines except the last page which may be shorter. 
 
Thank you. 

Kingsley Nettey

**Comment by mhosken** [comment]
As a quick workaround, you can set the unbalanced lines (max) to 1 on the laying out tab. That will get you going. If you want to really balance the columns then you'll have to stretch a paragraph somewhere on that page. 11pt text is certainly generous!
There's nothing actually wrong with the engine, it's just with the short paragraphs being out of sync in the two columns, the engine can't find a better place to break if you insist on balanced columns (as in it does an emergency break). But at least you see it!

**Comment by mhosken** [comment]
The general principle is if you get a really bad break and you don't want to fix it by stretching paragraphs (or whatever), then increasing the number of allowed bad lines should help.
For example, I modified the \r style to increase the space above to 0.33 and decrease the space below to -.0.2 (since Charis has a huge descender space), and that reduced the references to only take 2 lines, but that made the page break bad again and I had to increase the maximum unbalanced lines to 2.
It all depends if you are after: something that looks OK for a test print, versus: it must be perfect for a final typesetting. If the latter, then you will need to stretch and shrink paragraphs and get the max unbalanced lines down to 0 again.

**Comment by KNNettey** [comment]
[GBVN96_Default_MRK_ptxp 1 Column.pdf](https://github.com/sillsdev/ptx2pdf/files/13758569/GBVN96_Default_MRK_ptxp.1.Column.pdf)

I have used 1 column and attached is the results. The Parallel Reference \r seems to break to the next page because of the line spacing below. I am still don't understand why in the 2 column PDF first page breaks after the first line and only the left column is set.

My goal is to typeset a diglot with the old orthography of the same text as secondary text.

**Comment by KNNettey** [comment]
[GBVN96_Charis_MRK_ptxp.pdf](https://github.com/sillsdev/ptx2pdf/files/13758822/GBVN96_Charis_MRK_ptxp.pdf)

I checked the text again and made a few corrections. i have attached the resulting PDF.

**Comment by mhosken** [comment]
Since you are setting one paragraph per verse (which is bad practise) you
have many short paragraphs which makes it hard to balance pages. You have a
choice:

- balance pages with bad breaks, as you have now
- inbalance the pages by setting the maximum number of unbalanced lines to
above 0, and get better page breaking
- do full typesetting where you stretch papagraphs (which is hard when they
are short like this) to get both good breaks and balanced pages.

Things only get worse for single columns where paragraphs are even shorter.

I wish you well.
