### ISSUE TITLE
The "Quick Run" check box seems to always return to checked state

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#939]
v2.4.7
The "Quick Run" check box always returns to an active checked state whenever PTXprint restarts, even though I've cleared the checkbox and Saved the configuration. Expectation: PTXprint will remember the last state of that checkbox when it starts up again.

I've verified this several times. So, I'm thinking it's consistent.

**Comment by mhosken** [comment]
This is by design. Although such a decision may be questioned. For example
should we remember the setting per project? Per user? Or always just set it
on startup?

We chose the latter since most of the time people want a quick run and only
want long runs when they consciously want them.

**Comment by markpenny** [comment]
Having just seen a new user confused by this last week, "Why haven't the pictures been put in the right place?" I'm wondering whether we should flip the switch again, and leave Quick Run **OFF** by default (so that it always does a decent print, even if it has to run multiple times, and is slower) BUT make it a user-level preference - so that if a user turns it on/off, it will remember that for the next run (regardless of which project is being worked on).

I think the main UI issue here is that it is non-sticky by design, and people don't like software turning things on/off for them behind the scenes without their knowledge.

**Comment by markpenny** [comment]
This setting is now saved with the user config, so it won't keep changing every time you open a project. It defaults to OFF, but will stay on/off until it is changed by the user. Will behave like this in 2.4.10 and beyond.
