### ISSUE TITLE
Footnote caller bug

### ISSUE THREAD

**Issue by pungati** [sillsdev/ptx2pdf#951]
My PTX project footnote callers consist of varying starry shaped symbols, but in the ptx2pdf they all appear uniformly as a rectangular box.

**Comment by mnjames** [comment]
Those rectangular boxes are almost a sign that you're trying to type a character that isn't in the font you're using.

You may need to do some testing to find a font that works. In Paratext if you go to 
`Project Menu --> Project Settings --> Language Settings --> Other Characters (tab)`
then you'll see the Footnote caller sequence. You could then copy those into Word or something and experiment with what font displays them.

Once you have a font that works, in ptxprint you can go to Style, the Footnote style, search down near the bottom for Other Setting > Note Settings > Caller style
![image](https://github.com/sillsdev/ptx2pdf/assets/30174022/bfb9625a-e25b-4262-b002-ca5685266d5d)
you'll need to add a new style name there. I typed `z_foot_caller`

Now you'll need to create the new style. Since the original was based off of \v, it might be a good idea to go to the Verse Number style and click "Add" in the upper right
![image](https://github.com/sillsdev/ptx2pdf/assets/30174022/a1f28f63-dc11-4e37-bc00-0ec7a773925d)
Type your new name in
![image](https://github.com/sillsdev/ptx2pdf/assets/30174022/98751298-a82e-4290-8306-718fd4e0af58)

Finally, find that new style and use "Set Font" to change to the font that works.
![image](https://github.com/sillsdev/ptx2pdf/assets/30174022/23000616-1891-454b-b293-df950c5098d4)

**Comment by pungati** [comment]
Excellent and well detailed instructions; thank you mnjames. Works great now.
