### ISSUE TITLE
Prevent Glossary widows?

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#98]
If the Glossary is formatted with the headword in its own paragraph (\p) and the definition in the subsequent paragraph (another \p), is there a way to ensure that the headword doesn't show up at the bottom of a page?

**Comment by markpenny** [comment]
I'm afraid there are a few limitations with the glossary output - and one of them is that we only support the "simple" one-para per entry model (which Paratext almost forces on people). I will have a think about a work-around, but for the moment I don't see any. [And I'm guessing that this system of having a \p for headword and then another \p for the glossary entry also breaks the filtered glossary, right?] Could you paste a small sample of a few entries so that I can see what it looks like in practice.

**Comment by viverechristus** [comment]
It really doesn't look too bad. Here's a screen shot showing a widow.

![image](https://user-images.githubusercontent.com/915182/83608731-80f6c980-a5a7-11ea-8307-e537b3178dd0.png)

As you suggest, the glossary filtering doesn't work. If I print RUT, JON, GLO (easy test, since Ruth and Jonah don't have many glossary entries), I nevertheless get the full Glossary. But is that because of the layout?

I'll be honest, I suspect that at some point we'll change our Glossary layout to save a page or two - using the Paratext standard. But for now we're putting the headword on a separate line. (What if we used \b for the definition, I wonder?)

**Comment by markpenny** [comment]
Yes, it is best to standardize the way the glossary is done so that it will be easier later down the track when it comes to publishing and electronic publishing of your text and glossary.
![image](https://user-images.githubusercontent.com/12962708/83629389-9ffd5780-a5b7-11ea-9548-36268792b93a.png)
Closing this issue.
